Refactor mount plugin further to improve maintainability

diff --git a/desktop/nnn/mount b/desktop/nnn/mount
--- a/desktop/nnn/mount
+++ b/desktop/nnn/mount
@@ -10,29 +10,18 @@ mount_local_disk () {
   echo
 
   if grep -qs "$DEVICE " /proc/mounts; then
-    sync
-
-    if udisksctl unmount -b "/dev/$DEVICE"; then
-      echo "Device $DEVICE unmounted successfully"
-
-      if udisksctl power-off -b "/dev/$DEVICE"; then
-        echo "Device $DEVICE can now be ejected"
-      else
-        echo "Failed to power off device $DEVICE"
-      fi
-    else
+    sync &&
+    udisksctl unmount -b "/dev/$DEVICE" &&
+    udisksctl power-off -b "/dev/$DEVICE" &&
+      echo "Device $DEVICE unmounted successfully" ||
       echo "Failed to umount device $DEVICE"
-    fi
   else
-    if udisksctl mount -b "/dev/$DEVICE"
-    then
-      echo "Device $DEVICE mounted successfully"
-
-      if [ ! -L "$MOUNT_HOME/local" ]; then
-        ln -s "/run/media/$USER" "$MOUNT_HOME/local"
-      fi
-    else
+    udisksctl mount -b "/dev/$DEVICE" &&
+      echo "Device $DEVICE mounted successfully" ||
       echo "Failed to mount device $DEVICE"
+
+    if [ -d "/run/media/$USER" ] && [ ! -L "$MOUNT_HOME/local" ]; then
+      ln -s "/run/media/$USER" "$MOUNT_HOME/local"
     fi
   fi
 }
@@ -49,30 +38,22 @@ mount_remote_disk () {
   local SHARED_FOLDER=""
   read -rep "Shared folder: " SHARED_FOLDER
   SHARED_FOLDER="${SHARED_FOLDER,,}"
-
   echo
 
   local DEVICE="$PROTOCOL://$HOST/$SHARED_FOLDER"
 
   if gio mount -l | grep "$DEVICE"; then
-    sync
-
-    if gio mount -u "$DEVICE"; then
-      echo "Device $DEVICE unmounted successfully"
-    else
+    sync &&
+    gio mount -u "$DEVICE" &&
+      echo "Device $DEVICE unmounted successfully" ||
       echo "Failed to umount device $DEVICE"
-    fi
   else
-    gio mount "$DEVICE"
-
-    if [ $? -eq 0 ]; then
-      echo "Device $DEVICE mounted successfully"
-
-      if [ ! -L "$MOUNT_HOME/remote" ]; then
-        ln -s /run/user/${UID}/gvfs $MOUNT_HOME/remote
-      fi
-    else
+    gio mount "$DEVICE" &&
+      echo "Device $DEVICE mounted successfully" ||
       echo "Failed to mount device from $DEVICE"
+
+    if [ -d "/run/user/${UID}/gvfs" ] && [ ! -L "$MOUNT_HOME/remote" ]; then
+      ln -s "/run/user/${UID}/gvfs" "$MOUNT_HOME/remote"
     fi
   fi
 }
@@ -96,42 +77,62 @@ mount_google_drive () {
   local MOUNT_FOLDER="$MOUNT_HOME/cloud/$REMOTE_NAME"
 
   if [ ! -d "$MOUNT_FOLDER" ]; then
-    rclone config create "$REMOTE_NAME" "drive"
+    rclone config create "$REMOTE_NAME" "drive" \
       client_id="$CLIENT_ID" client_secret="$CLIENT_SECRET" scope=drive --obscure &&
       mkdir -p "$MOUNT_FOLDER" &&
       rclone mount "$REMOTE_NAME":"$SHARED_FOLDER" "$MOUNT_FOLDER" \
         --umask=002 --gid=$(id -g) --uid=$(id -u) --timeout=1h \
         --poll-interval=15s --dir-cache-time=1000h --vfs-cache-mode=full \
-        --vfs-cache-max-size=150G --vfs-cache-max-age=12h --daemon ||
-        rclone config delete "$REMOTE_NAME"; rm -rf "$MOUNT_FOLDER"
+        --vfs-cache-max-size=150G --vfs-cache-max-age=12h --daemon &&
+        echo "$REMOTE_NAME mounted successfully"
+
+    if [[ ! $? -eq 0 ]]; then
+      echo "Failed to mount $REMOTE_NAME"
+
+      rclone config delete "$REMOTE_NAME"
+      rm -rf "$MOUNT_FOLDER"
+    fi
   else
     echo "The remote name $REMOTE_NAME seems to be taken"
   fi
 }
 
-while true
-do
+while true; do
   clear
 
-  echo -e "Mount/unmount external file storages"
+  echo "Mount/unmount external storage file systems"
   read -rep "(l)ocal (r)emote (c)loud (q)uit: " REPLY
+  REPLY="${REPLY,,}"
 
-  echo -e ""
+  case "$REPLY" in
+    l|local)
+      mount_local_disk;;
 
-  if [ "$REPLY" = "l" ]; then
-    mount_local_disk
-  elif [ "$REPLY" = "r" ]; then
-    mount_remote_disk
-  elif [ "$REPLY" = "c" ]; then
-    mount_google_drive
-  else
-    clear
-    exit
-  fi
+    r|remote)
+      mount_remote_disk;;
 
-  read -rep "Enter any char to continue (q to quit): " REPLY
+    c|cloud)
+      read -rep "Provider: [Drive] " PROVIDER
+      PROVIDER="${PROVIDER:-"drive"}"
+      PROVIDER="${PROVIDER,,}"
 
-  if [ "$REPLY" = "q" ]; then
+      case "$PROVIDER" in
+        drive) mount_google_drive;;
+        *) echo "Not supported provider";;
+      esac;;
+
+    q|quit)
+      clear && exit;;
+
+    *)
+      echo "Invalid input, please try again";;
+  esac
+
+  read -rep "Do you want to quit? [Y/n] " REPLY
+  REPLY="${REPLY:-"yes"}"
+  REPLY="${REPLY,,}"
+
+  if [[ "$REPLY" =~ ^(y|yes)$ ]; then
     clear
     exit
   fi
