Refine scripts of the clock tool
This commit fixes:
* text in comments and docs
* text in output messages
* optional and required args on script mode
* DRY code to helpers
* validations of command arguments

diff --git a/tools/clock/commands b/tools/clock/commands
--- a/tools/clock/commands
+++ b/tools/clock/commands
@@ -6,37 +6,31 @@ source /opt/stack/utils
 source /opt/stack/clock/helpers
 
 # Shows the current status of system clock.
-# Arguments:
-#  None
 # Outputs:
 #  A verbose list of text data.
 show_status () {
   local query=''
-  query+='Local Time:      \(.local_time)\n'
-  query+='Universal Time:  \(.universal_time)\n'
-  query+='RTC Time:        \(.rtc_time)\n'
-  query+='Time Zone:       \(.time_zone)\n'
-  query+='Synced:          \(.system_clock_synchronized)\n'
-  query+='NTP Service:     \(.ntp_service)\n'
-  query+='RTC Local TZ:    \(.rtc_in_local_tz)\n'
-  query+='Epoch UTC:       \(.epoch_utc)'
+  query+='Local:   \(.local_time)\n'
+  query+='UTC:     \(.universal_time)\n'
+  query+='RTC:     \(.rtc_time)\n'
+  query+='Epoch:   \(.epoch_utc)\n'
+  query+='Zone:    \(.time_zone)\n'
+  query+='Clock:   \(if .rtc_in_local_tz then "Local" else "UTC" end)\n'
+  query+='Synced:  \(.system_clock_synchronized)\n'
+  query+='NTP:     \(.ntp_service)'
 
-  timedatectl | jc --timedatectl | jq -cer "\"${query}\""
-
-  if [[ $? -ne 0 ]]; then
-    echo 'Unable to resolve date time status'
-    return 2
-  fi
+  timedatectl | jc --timedatectl | jq -cer "\"${query}\"" || return $?
 
   local ntp_status=''
   ntp_status="$(timedatectl timesync-status 2> /dev/null)"
 
   if [[ $? -eq 0 ]]; then
     local query=''
-    query+='Server:          \(.server)\n'
-    query+='Poll Interval:   \(.poll_interval)\n'
-    query+='Leap:            \(.leap)'
-    
+    query+='Server:  \(.server)\n'
+    query+='Poll:    \(.poll_interval)\n'
+    query+='Leap:    \(.leap)'
+
+    echo
     echo "${ntp_status}" | jc --timedatectl | jq -cer "\"${query}\""
   fi
 }
@@ -47,71 +41,65 @@ show_status () {
 set_ntp () {
   local status="${1}"
 
-  if [[ ! "${status}" =~ ^(on|off)$ ]]; then
-    echo 'Invalid status value'
+  if [[ -z "${status}" ]]; then
+    echo 'Missing the status mode'
+    return 2
+  elif [[ ! "${status}" =~ ^(on|off)$ ]]; then
+    echo 'Invalid or unknown status mode'
     return 2
   fi
-
-  local status_name='enabled'
-  [[ "${status}" == "off" ]] && status_name='disabled'
 
   timedatectl set-ntp "${status}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to ${status_name} the NTP service"
+    echo "Failed to set NTP to ${status}"
     return 2
   fi
 
-  echo "NTP service has been ${status_name}"
+  echo "NTP has been set to ${status}"
 }
 
 # Sets the timezone to the given region.
 # Arguments:
-#  timezone: a timezone in region/city form
+#  name: the name of a timezone in region/city form
 set_timezone () {
-  local timezone="${1}"
+  local name="${1}"
 
-  if [[ -z "${timezone}" ]]; then
-    pick_timezone 'Select a timezone:' || return $?
-    timezone="${REPLY}"
+  if [[ -z "${name}" ]]; then
+    on_script_mode &&
+      echo 'Missing the timezone' && return 2
+
+    pick_timezone 'Select timezone:' || return $?
+    require 'Timezone is required' || return 2
+    name="${REPLY}"
   fi
 
-  if ! timedatectl list-timezones | grep -qw "${timezone}"; then
-    echo 'Invalid timezone value'
+  if ! validate_timezone "${name}"; then
+    echo 'Invalid or unknown timezone value'
     return 2
   fi
 
-  timedatectl set-timezone "${timezone}"
+  timedatectl set-timezone "${name}"
 
   if [[ $? -ne 0 ]]; then
     echo 'Failed to set the timezone'
     return 2
   fi
   
-  echo "Timezone set to ${timezone}"
+  echo "Timezone set to ${name}"
 }
 
 # Sets the system time to the given hours and minutes.
 # Arguments:
-#  time: the time in HH:mm form
+#  time: a 24h time in hh:mm form
 set_time () {
   local time="${1}"
 
-  if [[ ! "${time}" =~ ^[0-9][0-9]:[0-9][0-9]$ ]]; then
-    echo 'Invalid time value'
+  if [[ -z "${time}" ]]; then
+    echo 'Missing the time'
     return 2
-  fi
-
-  local hour=$(echo "${time}" | cut -d ':' -f 1)
-  local min=$(echo "${time}" | cut -d ':' -f 2)
-
-  if ((${hour} > 23)); then
-    echo 'Hour value is out of range'
-    return 2
-  fi
-
-  if ((${min} > 59)); then
-    echo 'Minute value is out of range'
+  elif ! validate_time "${time}"; then
+    echo 'Invalid or malformed time'
     return 2
   fi
 
@@ -131,22 +119,11 @@ set_time () {
 set_date () {
   local date="${1}"
 
-  if [[ ! "${date}" =~ ^[0-9][0-9]([0-9][0-9])?-[0-9][0-9]-[0-9][0-9]$ ]]; then
-    echo 'Invalid date value'
+  if [[ -z "${date}" ]]; then
+    echo 'Missing the date'
     return 2
-  fi
-
-  local year=$(echo "${date}" | cut -d '-' -f 1)
-  local month=$(echo "${date}" | cut -d '-' -f 2)
-  local day=$(echo "${date}" | cut -d '-' -f 3)
-
-  if ((${month} == 0 || ${month} > 12)) ; then
-    echo 'Month value is out of range'
-    return 2
-  fi
-
-  if ((${day} == 0 || ${day} > 31)); then
-    echo 'Day value is out of range'
+  elif ! validate_date "${date}"; then
+    echo 'Invalid or malformed date'
     return 2
   fi
 
@@ -168,8 +145,11 @@ set_date () {
 set_rtc () {
   local mode="${1}"
 
-  if [[ ! "${mode}" =~ ^(local|utc)$ ]]; then
-    echo 'Invalid rtc mode value'
+  if [[ -z "${mode}" ]]; then
+    echo 'Missing the rtc mode'
+    return 2
+  elif [[ ! "${mode}" =~ ^(local|utc)$ ]]; then
+    echo 'Invalid or unknwon rtc mode'
     return 2
   fi
 
@@ -180,24 +160,22 @@ set_rtc () {
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo 'Failed to set RTC'
+    echo 'Failed to set hardware clock'
     return 2
   fi
 
-  echo "RTC set to ${mode} time"
+  echo "Hardware clock set to ${mode} time"
 }
 
 # Synchronizes the hardware clock from the system clock.
-# Arguments:
-#  None
 sync_rtc () {
   sudo hwclock --systohc --utc
 
   if [[ $? -ne 0 ]]; then
-    echo 'Failed to sync the hardware clock'
+    echo 'Failed to sync hardware clock'
     return 2
   fi
 
-  echo 'Hardware clock synced from the system clock'
+  echo 'Hardware clock synced to system clock'
 }
 
