Use single quotes in echos, assignments, expressions and literals

diff --git a/tools/bluetooth/commands b/tools/bluetooth/commands
--- a/tools/bluetooth/commands
+++ b/tools/bluetooth/commands
@@ -32,14 +32,14 @@ show_status () {
   find_controller | jq -cer ".[0]|\"${query}\""
   
   if [[ $? -ne 0 ]]; then
-    echo "Controller:    none"
+    echo 'Controller:    none'
   fi
 
   local query=''
   query+='if .|length > 0 then .[]|.address else "" end'
 
   local devices=''
-  devices="$(find_devices "connected" | jq -cer "${query}")" || return 1
+  devices="$(find_devices connected | jq -cer "${query}")" || return 1
 
   if [[ -z "${devices}" ]]; then
     return 0
@@ -77,7 +77,7 @@ list_controllers () {
   controllers="$(find_controllers)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read controllers"
+    echo 'Unable to read controllers'
     return 2
   fi
 
@@ -85,7 +85,7 @@ list_controllers () {
   len="$(count "${controllers}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No controllers have found"
+    echo 'No controllers have found'
     return 0
   fi
 
@@ -108,7 +108,7 @@ list_devices () {
   local status="${1}"
 
   if [[ -n "${status}" ]] && [[ ! "${status}" =~ ^(paired|connected|trusted|bonded)$ ]]; then
-    echo "Invalid status value"
+    echo 'Invalid status value'
     return 2
   fi
 
@@ -116,7 +116,7 @@ list_devices () {
   devices="$(find_devices "${status^}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read devices"
+    echo 'Unable to read devices'
     return 2
   fi
 
@@ -124,7 +124,7 @@ list_devices () {
   len="$(count "${devices}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No available devices have found"
+    echo 'No available devices have found'
     return 0
   fi
 
@@ -241,7 +241,7 @@ set_controller () {
   bluetoothctl select "${address}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set default controller"
+    echo 'Failed to set default controller'
     return 2
   fi
 
@@ -255,15 +255,15 @@ set_power () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing the power mode value"
+    echo 'Missing the power mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid power mode value"
+    echo 'Invalid power mode value'
     return 2
   fi
 
   if ! find_controller &> /dev/null; then
-    echo "Unable to find default controller"
+    echo 'Unable to find default controller'
     return 2
   fi
 
@@ -284,15 +284,15 @@ set_scan () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing scanning mode value"
+    echo 'Missing scanning mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid scanning mode value"
+    echo 'Invalid scanning mode value'
     return 2
   fi
 
   if ! find_controller &> /dev/null; then
-    echo "Unable to find default controller"
+    echo 'Unable to find default controller'
     return 2
   fi
 
@@ -316,10 +316,10 @@ set_scan () {
   fi
 
   if [[ "${mode}" == "on" ]] && ! is_scanning_on ; then
-    echo "Failed to set scanning mode to on"
+    echo 'Failed to set scanning mode to on'
     return 2
   elif [[ "${mode}" == "off" ]] && is_scanning_on ; then
-    echo "Failed to set scanning mode to off"
+    echo 'Failed to set scanning mode to off'
     return 2
   fi
 
@@ -333,15 +333,15 @@ set_discoverable () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing the discoverable mode value"
+    echo 'Missing the discoverable mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid discoverable mode value"
+    echo 'Invalid discoverable mode value'
     return 2
   fi
 
   if ! find_controller &> /dev/null; then
-    echo "Unable to find default controller"
+    echo 'Unable to find default controller'
     return 2
   fi
 
@@ -362,15 +362,15 @@ set_pairable () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing the pairable mode value"
+    echo 'Missing the pairable mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid pairable mode value"
+    echo 'Invalid pairable mode value'
     return 2
   fi
 
   if ! find_controller &> /dev/null; then
-    echo "Unable to find default controller"
+    echo 'Unable to find default controller'
     return 2
   fi
 
@@ -399,7 +399,7 @@ connect_device () {
   device="$(find_device "${address}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find the device"
+    echo 'Unable to find the device'
     return 2
   fi
 
@@ -430,7 +430,7 @@ disconnect_device () {
   device="$(find_device "${address}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find the device"
+    echo 'Unable to find the device'
     return 2
   fi
 
@@ -459,7 +459,7 @@ remove_device () {
   device="$(find_device "${address}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find the device"
+    echo 'Unable to find the device'
     return 2
   fi
 
@@ -486,10 +486,10 @@ restart_bluetooth () {
   sudo systemctl restart bluetooth.service
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to restart the bluetooth service"
+    echo 'Failed to restart the bluetooth service'
     return 2
   fi
 
-  echo "Bluetooth service has been restarted"
+  echo 'Bluetooth service has been restarted'
 }
 
diff --git a/tools/cloud/main b/tools/cloud/main
--- a/tools/cloud/main
+++ b/tools/cloud/main
@@ -12,40 +12,40 @@ source /opt/stack/cloud/commands
 #  A long help message.
 show_help () {
   if [[ "${1}" == "once" ]]; then
-    echo "Usage: cloud COMMAND [OBJECT] [ARGUMENTS]..."
+    echo 'Usage: cloud COMMAND [OBJECT] [ARGUMENTS]...'
 
-    echo -e "\nCOMMANDS"
-    printf " %-15s %s\n" \
-      "help" "Show this help message." \
-      "" "" \
-      "mount remotes" "Mount all synced cloud remotes."
+    echo -e '\nCOMMANDS'
+    printf ' %-15s %s\n' \
+      'help' 'Show this help message.' \
+      '' '' \
+      'mount remotes' 'Mount all synced cloud remotes.'
 
     return 0
   fi
 
-  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."
+  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
   
-  echo -e "\nCOMMANDS"
-  printf " %-30s %s\n" \
-    "help" "Show this help message." \
-    "" "" \
-    "list remotes [service]" "List all synced remotes by service." \
-    "sync remote <service> <name>" "Sync a remote service, where service" \
-    "" "could be drive or dropbox." \
-    "delete remote [<name>]" "Delete a synced remote service." \
-    "" "" \
-    "mount remote [<name>]" "Mount an already synced remote." \
-    "unmount remote [<name>]" "Unmount an already mounted remote."
+  echo -e '\nCOMMANDS'
+  printf ' %-30s %s\n' \
+    'help' 'Show this help message.' \
+    '' '' \
+    'list remotes [service]' 'List all synced remotes by service.' \
+    'sync remote <service> <name>' 'Sync a remote service, where service' \
+    '' 'could be drive or dropbox.' \
+    'delete remote [<name>]' 'Delete a synced remote service.' \
+    '' '' \
+    'mount remote [<name>]' 'Mount an already synced remote.' \
+    'unmount remote [<name>]' 'Unmount an already mounted remote.'
 }
 
 loop () {
   clear
 
   while true; do
-    prompt "cloud" && history -s "${REPLY}"
+    prompt cloud && history -s "${REPLY}"
 
     set -f
-    set_separator "line"
+    set_separator line
     local cmd=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
@@ -62,34 +62,34 @@ loop () {
     fi
 
     case "${cmd[0]}" in
-      "list")
+      list)
         case "${cmd[1]}" in
-          "remotes") list_remotes "${cmd[2]}";;
+          remotes) list_remotes "${cmd[2]}";;
           *) echo 'Invalid or unknown command';;
         esac;;
-      "sync")
+      sync)
         case "${cmd[1]}" in
-          "remote")
+          remote)
             case "${cmd[2]}" in
-              "drive") sync_drive "${cmd[3]}";;
-              "dropbox") sync_dropbox "${cmd[3]}";;
+              drive) sync_drive "${cmd[3]}";;
+              dropbox) sync_dropbox "${cmd[3]}";;
               *) echo 'Invalid or unknown service';;
             esac;;
           *) echo 'Invalid or unknown command';;
         esac;;
-      "delete")
+      delete)
         case "${cmd[1]}" in
-          "remote") delete_remote "${cmd[2]}";;
+          remote) delete_remote "${cmd[2]}";;
           *) echo 'Invalid or unknown command';;
         esac;;
-      "mount")
+      mount)
         case "${cmd[1]}" in
-          "remote") mount_remote "${cmd[2]}";;
+          remote) mount_remote "${cmd[2]}";;
           *) echo 'Invalid or unknown command';;
         esac;;
-      "unmount")
+      unmount)
         case "${cmd[1]}" in
-          "remote") unmount_remote "${cmd[2]}";;
+          remote) unmount_remote "${cmd[2]}";;
           *) echo 'Invalid or unknown command';;
         esac;;
       *) echo 'Unknown or invalid command';; 
@@ -107,13 +107,13 @@ loop () {
 
 once () {
   case "${1}" in
-    "help") show_help "once";;
-    "mount")
+    help) show_help once;;
+    mount)
       case "${2}" in
-        "remotes") mount_all || abort;;
-        *) abort "Invalid or unknown command";;
+        remotes) mount_all || abort;;
+        *) abort 'Invalid or unknown command';;
       esac;;
-    *) abort "Invalid or unknown command";;
+    *) abort 'Invalid or unknown command';;
   esac
 
   if [[ $? -ne 0 ]]; then
diff --git a/tools/desktop/commands b/tools/desktop/commands
--- a/tools/desktop/commands
+++ b/tools/desktop/commands
@@ -90,7 +90,7 @@ list_wallpapers () {
   wallpapers="$(find_wallpapers)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find wallpaper files"
+    echo 'Unable to find wallpaper files'
     return 2
   fi
 
@@ -98,7 +98,7 @@ list_wallpapers () {
   len="$(count "${wallpapers}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No wallpaper files have found"
+    echo 'No wallpaper files have found'
     return 2
   fi
 
@@ -130,7 +130,7 @@ set_wallpaper () {
   fi
 
   if [[ "${name}" =~ /+ ]]; then
-    echo "Invalid wallpaper name"
+    echo 'Invalid wallpaper name'
     return 2
   fi
 
@@ -138,7 +138,7 @@ set_wallpaper () {
   local wallpaper_file="${WALLPAPERS_HOME}/${name}"
 
   if [[ ! "${wallpaper_file}" =~ .+\.(jpg|jpeg|png)$ ]]; then
-    echo "Invalid wallpaper file type"
+    echo 'Invalid wallpaper file type'
     return 2
   elif [[ ! -f "${wallpaper_file}" ]]; then
     echo "No wallpaper found with name ${name}"
@@ -154,19 +154,19 @@ set_wallpaper () {
     modes+='{"key": "tile", "value": "Tile"}'
     modes="[${modes}]"
 
-    pick_one "Select a mode:" "${modes}" "vertical" || return $?
+    pick_one 'Select a mode:' "${modes}" vertical || return $?
     [[ -n "${REPLY}" ]] && mode="${REPLY}" || return 0
   fi
   
   if [[ ! "${mode}" =~ ^(center|fill|max|scale|tile)$ ]]; then
-    echo "Invalid wallpaper mode"
+    echo 'Invalid wallpaper mode'
     return 2
   fi
 
   feh --no-fehbg --bg-"${mode}" "${wallpaper_file}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set wallpaper"
+    echo 'Failed to set wallpaper'
     return 2
   fi
 
@@ -234,7 +234,7 @@ list_pointers () {
   pointers="$(find_pointers)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find pointers"
+    echo 'Unable to find pointers'
     return 2
   fi
 
@@ -242,7 +242,7 @@ list_pointers () {
   len="$(count "${pointers}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No pointers have found"
+    echo 'No pointers have found'
     return 0
   fi
 
@@ -265,18 +265,18 @@ set_pointer_speed () {
   local persist="${2:-"save"}"
 
   if [[ -z "${factor}" ]]; then
-    ask "Enter the speed factor [0,1]:" "^[0-9]+\.?[0-9]*$" || return $?
+    ask 'Enter the speed factor [0,1]:' '^[0-9]+\.?[0-9]*$' || return $?
     factor="${REPLY}"
   fi
 
   if [[ ! "${factor}" =~ ^[0-9]+\.?[0-9]*$ ]]; then
-    echo "Invalid pointer speed"
+    echo 'Invalid pointer speed'
     return 2
   elif (( $(echo "${factor} < 0" | bc) )); then
-    echo "Speed factor can't be lower than 0"
+    echo 'Speed factor cannot be lower than 0'
     return 2
   elif (( $(echo "${factor} > 1" | bc) )); then
-    echo "Speed factor can't be greater than 1"
+    echo 'Speed factor cannot be greater than 1'
     return 2
   fi
 
@@ -308,23 +308,23 @@ set_pointer_speed () {
     print a[1]
   }')" || return 1
 
-  local succeed="false"
+  local succeed='false'
 
   local device=''
   while read -r device; do
     # Assume this is a mouse device and set its acceleration speed
-    xinput --set-prop "${device}" "libinput Accel Speed" "${speed}" &> /dev/null &&
-    succeed="true" && continue
+    xinput --set-prop "${device}" 'libinput Accel Speed' "${speed}" &> /dev/null &&
+    succeed='true' && continue
 
     # Otherwise assume this is a touch device and set its velocity
-    xinput --set-prop "${device}" "Device Accel Constant Deceleration" 1 &> /dev/null &&
-    xinput --set-prop "${device}" "Device Accel Adaptive Deceleration" 1 &> /dev/null &&
-    xinput --set-prop "${device}" "Device Accel Velocity Scaling" "${velocity}" &> /dev/null &&
-    succeed="true"
+    xinput --set-prop "${device}" 'Device Accel Constant Deceleration' 1 &> /dev/null &&
+    xinput --set-prop "${device}" 'Device Accel Adaptive Deceleration' 1 &> /dev/null &&
+    xinput --set-prop "${device}" 'Device Accel Velocity Scaling' "${velocity}" &> /dev/null &&
+    succeed='true'
   done <<< "${devices}"
 
   if [[ "${succeed}" == "false" ]]; then
-    echo "Failed to set pointer speed"
+    echo 'Failed to set pointer speed'
     return 2
   fi
 
@@ -399,7 +399,7 @@ list_tablets () {
   tablets="$(find_tablets)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find tablets"
+    echo 'Unable to find tablets'
     return 2
   fi
 
@@ -407,7 +407,7 @@ list_tablets () {
   len="$(count "${tablets}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No tablets have found"
+    echo 'No tablets have found'
     return 0
   fi
 
@@ -449,18 +449,18 @@ scale_tablet () {
   fi
 
   if [[ -z "${scale}" ]]; then
-    ask "Enter the scale factor [0.1-1]:" "^[0-9]+\.?[0-9]*$" || return $?
+    ask 'Enter the scale factor [0.1-1]:' '^[0-9]+\.?[0-9]*$' || return $?
     scale="${REPLY}"
   fi
 
   if [[ ! "${scale}" =~ ^[0-9]+\.?[0-9]*$ ]]; then
-    echo "Invalid pointer speed"
+    echo 'Invalid pointer speed'
     return 2
   elif (( $(echo "${scale} <= 0" | bc) )); then
-    echo "Scale can't be lower or equal to 0"
+    echo 'Scale cannot be lower or equal to 0'
     return 2
   elif (( $(echo "${scale} > 1" | bc) )); then
-    echo "Scale can't be larger than 1"
+    echo 'Scale cannot be larger than 1'
     return 2
   fi
 
@@ -555,7 +555,7 @@ map_tablet () {
   fi
 
   if [[ -z "${display}" ]]; then
-    pick_output "Select a display:" "active" || return $?
+    pick_output 'Select a display:' active || return $?
     [[ -n "${REPLY}" ]] && display="${REPLY}" || return 0
   fi
 
@@ -564,7 +564,7 @@ map_tablet () {
     xsetwacom --set "${name}" MapToOutput desktop &> /dev/null
 
     if [[ $? -ne 0 ]]; then
-      echo "Failed to reset mapping"
+      echo 'Failed to reset mapping'
       return 2
     fi
 
@@ -587,7 +587,7 @@ map_tablet () {
 
     xsetwacom --set "${name}" area "${area}" &> /dev/null || return 1
 
-    echo "Tablet mapping has been reset"
+    echo 'Tablet mapping has been reset'
     return 0
   fi
 
@@ -639,7 +639,7 @@ map_tablet () {
 #  None
 init_pointer () {
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No pointer settings found"
+    echo 'No pointer settings found'
     return 0
   fi
 
@@ -647,21 +647,21 @@ init_pointer () {
   pointer="$(jq '.pointer|if . then . else empty end' "${SETTINGS_FILE}")"
 
   if [[ -z "${pointer}" ]]; then
-    echo "No pointer settings found"
+    echo 'No pointer settings found'
     return 0
   fi
 
   local speed=''
   speed="$(get "${pointer}" '.speed')" || return 1
 
-  set_pointer_speed "${speed}" "nosave"
+  set_pointer_speed "${speed}" nosave
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set pointer speed"
+    echo 'Failed to set pointer speed'
     return 2
   fi
 
-  echo "Pointer speed has been set"
+  echo 'Pointer speed has been set'
 }
 
 # Applies the settings for those tablets being stored
@@ -670,7 +670,7 @@ init_pointer () {
 #  None
 init_tablets () {
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No tablets settings found"
+    echo 'No tablets settings found'
     return 0
   fi
 
@@ -678,12 +678,12 @@ init_tablets () {
   tablets="$(jq '.tablets|if . then . else empty end' "${SETTINGS_FILE}")"
 
   if [[ -z "${tablets}" ]]; then
-    echo "No tablets settings found"
+    echo 'No tablets settings found'
     return 0
   fi
 
   local output=''
-  output="$(find_outputs "primary" | jq -cer '.[0]|.device_name')" || return 1
+  output="$(find_outputs primary | jq -cer '.[0]|.device_name')" || return 1
 
   tablets="$(echo "${tablets}" | jq -cr '.[]|{name, scale}')" || return 1
 
@@ -698,16 +698,16 @@ init_tablets () {
     local scale=1
     scale="$(get "${tablet}" '.scale')"
 
-    scale_tablet "${name}" "${scale}" "nosave" &&
+    scale_tablet "${name}" "${scale}" nosave &&
     map_tablet "${name}" "${output}" || failed='true'
   done <<< "${tablets}"
 
   if [[ "${failed}" == "true" ]]; then
-    echo "Failed to set all tablets"
+    echo 'Failed to set all tablets'
     return 2
   fi
 
-  echo "Tablets have been set"
+  echo 'Tablets have been set'
 }
 
 # Sets the desktop wallpaper to the wallpaper
@@ -716,7 +716,7 @@ init_tablets () {
 #  None
 init_wallpaper () {
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No wallpaper settings found"
+    echo 'No wallpaper settings found'
     return 0
   fi
 
@@ -724,7 +724,7 @@ init_wallpaper () {
   wallpaper="$(jq '.wallpaper|if . then . else empty end' "${SETTINGS_FILE}")"
 
   if [[ -z "${wallpaper}" ]]; then
-    echo "No wallpaper settings found"
+    echo 'No wallpaper settings found'
     return 0
   fi
 
@@ -739,13 +739,13 @@ init_wallpaper () {
   local mode=''
   mode="$(get "${wallpaper}" '.mode')" || return 1
 
-  set_wallpaper "${name}" "${mode:-"center"}" "nosave"
+  set_wallpaper "${name}" "${mode:-"center"}" nosave
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set the wallpaper"
+    echo 'Failed to set the wallpaper'
     return 2
   fi
 
-  echo "Wallpaper has been set"
+  echo 'Wallpaper has been set'
 }
 
diff --git a/tools/desktop/helpers b/tools/desktop/helpers
--- a/tools/desktop/helpers
+++ b/tools/desktop/helpers
@@ -58,7 +58,7 @@ pick_wallpaper () {
   wallpapers="$(find_wallpapers | jq -cer "${query}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find wallpaper files"
+    echo 'Unable to find wallpaper files'
     return 2
   fi
 
@@ -66,11 +66,11 @@ pick_wallpaper () {
   len="$(count "${wallpapers}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No wallpaper files have found"
+    echo 'No wallpaper files have found'
     return 2
   fi
 
-  pick_one "Select a wallpaper:" "${wallpapers}" "vertical" || return $?
+  pick_one 'Select a wallpaper:' "${wallpapers}" vertical || return $?
 }
 
 # Returns the list of pointing devices currently
@@ -174,7 +174,7 @@ pick_pointer () {
   pointers="$(find_pointers)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find pointers"
+    echo 'Unable to find pointers'
     return 2
   fi
 
@@ -182,14 +182,14 @@ pick_pointer () {
   len="$(count "${pointers}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No pointers have found"
+    echo 'No pointers have found'
     return 2
   fi
 
   local query='[.[]|{key: .id, value: "\(.id):\(.name)"}]'
   pointers="$(echo "${pointers}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a pointer:" "${pointers}" "vertical" || return $?
+  pick_one 'Select a pointer:' "${pointers}" vertical || return $?
 }
 
 # Returns the list of stylus-pen devices currently
@@ -312,7 +312,7 @@ pick_tablet () {
   tablets="$(find_tablets)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find tablets"
+    echo 'Unable to find tablets'
     return 2
   fi
 
@@ -320,13 +320,13 @@ pick_tablet () {
   len="$(count "${tablets}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No tablets have found"
+    echo 'No tablets have found'
     return 2
   fi
 
   local query='[.[]|{key: .name, value: .name}]'
   tablets="$(echo "${tablets}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a tablet:" "${tablets}" "vertical" || return $?
+  pick_one 'Select a tablet:' "${tablets}" vertical || return $?
 }
 
diff --git a/tools/desktop/main b/tools/desktop/main
--- a/tools/desktop/main
+++ b/tools/desktop/main
@@ -12,51 +12,51 @@ source /opt/stack/desktop/commands
 #  A long help message.
 show_help () {
   if [[ "${1}" == "once" ]]; then
-    echo "Usage: desktop COMMAND [OBJECT] [ARGUMENTS]..."
+    echo 'Usage: desktop COMMAND [OBJECT] [ARGUMENTS]...'
 
-    echo -e "\nCOMMANDS"
-    printf " %-16s %s\n" \
-      "help" "Show this help message." \
-      "" "" \
-      "init pointer" "Initialize the pointer." \
-      "init tablets" "Initialize any connected tablets." \
-      "init wallpaper" "Initialize the desktop wallpaper."
+    echo -e '\nCOMMANDS'
+    printf ' %-16s %s\n' \
+      'help' 'Show this help message.' \
+      '' '' \
+      'init pointer' 'Initialize the pointer.' \
+      'init tablets' 'Initialize any connected tablets.' \
+      'init wallpaper' 'Initialize the desktop wallpaper.'
 
     return 0
   fi
 
-  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."
+  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-  echo -e "\nCOMMANDS"
-  printf " %-36s %s\n" \
-    "help" "Show this help message." \
-    "" "" \
-    "show status" "Show the status of the desktop environment." \
-    "show pointer [<id>]" "Show a pointing device." \
-    "show tablet [<name>]" "Show a tablet device." \
-    "" "" \
-    "list wallpapers" "List the available wallapers." \
-    "list pointers" "List the available pointing devices." \
-    "list tablets" "List the connected tablets." \
-    "" "" \
-    "set wallpaper [<name> [<mode>]]" "Set the desktop wallpaper in center" \
-    "" "fill, scale, max or tile mode." \
-    "speed pointer [<factor>]" "Set the pointer's speed to a factor between" \
-    "" "[0, 1] where 0 means slow and 1 fast." \
-    "scale tablet [<name> [<factor>]]" "Scale down the area of a tablet (e.g. 0.5)" \
-    "" "or use factor 1 to reset scaling." \
-    "map tablet [<name> [<display>]]" "Map a tablet to a screen display" \
-    "" "or just use desktop to reset mapping."
+  echo -e '\nCOMMANDS'
+  printf ' %-36s %s\n' \
+    'help' 'Show this help message.' \
+    '' '' \
+    'show status' 'Show the status of the desktop environment.' \
+    'show pointer [<id>]' 'Show a pointing device.' \
+    'show tablet [<name>]' 'Show a tablet device.' \
+    '' '' \
+    'list wallpapers' 'List the available wallapers.' \
+    'list pointers' 'List the available pointing devices.' \
+    'list tablets' 'List the connected tablets.' \
+    '' '' \
+    'set wallpaper [<name> [<mode>]]' 'Set the desktop wallpaper in center' \
+    '' 'fill, scale, max or tile mode.' \
+    'speed pointer [<factor>]' 'Set the pointer speed to a factor between' \
+    '' '[0, 1] where 0 means slow and 1 fast.' \
+    'scale tablet [<name> [<factor>]]' 'Scale down the area of a tablet (e.g. 0.5)' \
+    '' 'or use factor 1 to reset scaling.' \
+    'map tablet [<name> [<display>]]' 'Map a tablet to a screen display' \
+    '' 'or just use desktop to reset mapping.'
 }
 
 loop () {
   clear
 
   while true; do
-    prompt "desktop" && history -s "${REPLY}"
+    prompt desktop && history -s "${REPLY}"
 
     set -f
-    set_separator "line"
+    set_separator line
     local cmd=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
@@ -73,45 +73,45 @@ loop () {
     fi
 
     case "${cmd[0]}" in
-      "show")
+      show)
         case "${cmd[1]}" in
-          "status") show_status;;
-          "pointer") show_pointer "${cmd[2]}";;
-          "tablet") show_tablet "${cmd[2]}";;
-          *) echo "Invalid or unknown command";;
+          status) show_status;;
+          pointer) show_pointer "${cmd[2]}";;
+          tablet) show_tablet "${cmd[2]}";;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      "set")
+      set)
         case "${cmd[1]}" in
-          "wallpaper") set_wallpaper "${cmd[2]}" "${cmd[3]}";;
-          *) echo "Invalid or unknown command";;
+          wallpaper) set_wallpaper "${cmd[2]}" "${cmd[3]}";;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      "speed")
+      speed)
         case "${cmd[1]}" in
-          "pointer") set_pointer_speed "${cmd[2]}";;
-          *) echo "Invalid or unknown command";;
+          pointer) set_pointer_speed "${cmd[2]}";;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      "scale")
+      scale)
         case "${cmd[1]}" in
-          "tablet") scale_tablet "${cmd[2]}" "${cmd[3]}";;
-          *) echo "Invalid or unknown command";;
+          tablet) scale_tablet "${cmd[2]}" "${cmd[3]}";;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      "map")
+      map)
         case "${cmd[1]}" in
-          "tablet") map_tablet "${cmd[2]}" "${cmd[3]}";;
-          *) echo "Invalid or unknown command";;
+          tablet) map_tablet "${cmd[2]}" "${cmd[3]}";;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      "list")
+      list)
         case "${cmd[1]}" in
-          "wallpapers") list_wallpapers;;
-          "pointers") list_pointers;;
-          "tablets") list_tablets;;
-          *) echo "Invalid or unknown command";;
+          wallpapers) list_wallpapers;;
+          pointers) list_pointers;;
+          tablets) list_tablets;;
+          *) echo 'Invalid or unknown command';;
         esac;;
-      *) echo "Invalid or unknown command";; 
+      *) echo 'Invalid or unknown command';; 
     esac
     
     if [[ $? -eq 1 ]]; then
-      echo "An unknown error has occurred"
+      echo 'An unknown error has occurred'
     fi
 
     REPLY=''
@@ -122,15 +122,15 @@ loop () {
 
 once () {
   case "${1}" in
-    "help") show_help "once";;
-    "init")
+    help) show_help once;;
+    init)
       case "${2}" in
-        "pointer") init_pointer || abort;;
-        "tablets") init_tablets || abort;;
-        "wallpaper") init_wallpaper || abort;;
-        *) abort "Invalid or unknown command";;
+        pointer) init_pointer || abort;;
+        tablets) init_tablets || abort;;
+        wallpaper) init_wallpaper || abort;;
+        *) abort 'Invalid or unknown command';;
       esac;;
-    *) abort "Invalid or unknown command";;
+    *) abort 'Invalid or unknown command';;
   esac
 
   if [[ $? -ne 0 ]]; then
diff --git a/tools/disks/commands b/tools/disks/commands
--- a/tools/disks/commands
+++ b/tools/disks/commands
@@ -46,7 +46,7 @@ show_status () {
     printf "%-8s %s\n", "Used:", $4"/"$3
   }' || return 1
 
-  cat /proc/meminfo | grep -E "Swap.*" | awk -F':' '{
+  cat /proc/meminfo | grep -E 'Swap.*' | awk -F':' '{
     gsub(/^[ \t]+/,"",$1)
     gsub(/[ \t]+$/,"",$1)
     gsub(/^[ \t]+/,"",$2)
@@ -127,7 +127,7 @@ show_disk () {
   echo "${disk}" | jq -cer "\"${query}\""
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to parse disk data"
+    echo 'Failed to parse disk data'
     return 2
   fi
 }
@@ -211,7 +211,7 @@ show_partition () {
   echo "${part}" | jq -cer "\"${query}\""
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to parse partition data"
+    echo 'Failed to parse partition data'
     return 2
   fi
 }
@@ -266,7 +266,7 @@ show_rom () {
   echo "${rom}" | jq -cer "\"${query}\""
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to parse rom data"
+    echo 'Failed to parse rom data'
     return 2
   fi
 }
@@ -281,7 +281,7 @@ list_disks () {
   disks="$(find_disks)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find disks"
+    echo 'Unable to find disks'
     return 2
   fi
 
@@ -289,7 +289,7 @@ list_disks () {
   len="$(count "${disks}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No disks have found"
+    echo 'No disks have found'
     return 0
   fi
 
@@ -327,7 +327,7 @@ list_partitions () {
   parts="$(find_partitions "${path}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find partitions"
+    echo 'Unable to find partitions'
     return 2
   fi
 
@@ -335,7 +335,7 @@ list_partitions () {
   len="$(count "${parts}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No partitions have found"
+    echo 'No partitions have found'
     return 0
   fi
 
@@ -359,7 +359,7 @@ list_roms () {
   roms="$(find_roms)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find roms"
+    echo 'Unable to find roms'
     return 2
   fi
 
@@ -367,7 +367,7 @@ list_roms () {
   len="$(count "${roms}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No roms have found"
+    echo 'No roms have found'
     return 0
   fi
 
@@ -396,20 +396,20 @@ list_shared_folders () {
     [[ -n "${REPLY}" ]] && host="${REPLY}" || return 0
   fi
 
-  ask "Enter the username:" || return $?
+  ask 'Enter the username:' || return $?
   local username="${REPLY}"
 
-  ask "Enter the workgroup [WORKGROUP]:" || return $?
+  ask 'Enter the workgroup [WORKGROUP]:' || return $?
   local workgroup="${REPLY:-"WORKGROUP"}"
 
-  ask_secret "Enter the password:" || return $?
+  ask_secret 'Enter the password:' || return $?
   local password="${REPLY}"
 
   local folders=''
   folders="$(find_shared_folders "${host}" "${username}" "${workgroup}" "${password}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find shared folders"
+    echo 'Unable to find shared folders'
     return 2
   fi
 
@@ -417,7 +417,7 @@ list_shared_folders () {
   len="$(count "${folders}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No shared folders have found"
+    echo 'No shared folders have found'
     return 0
   fi
 
@@ -445,7 +445,7 @@ list_mounts () {
   local disk=''
   while read -r disk; do
     local parts=''
-    parts="$(find_partitions "${disk}" "mounted" |
+    parts="$(find_partitions "${disk}" mounted |
       jq -cer '[.[]|{name: .path, point: (if .mountpoint then .mountpoint else .veracrypt.mountpoint end)}]')" || return 1
 
     # Merge disk partitions to mounts array
@@ -453,7 +453,7 @@ list_mounts () {
   done <<< "${disks}"
 
   local roms=''
-  roms="$(find_roms "mounted" | 
+  roms="$(find_roms mounted | 
     jq -cer '[.[]|{name: .path, point: .mountpoint}]')" || return 1
   
   # Merge roms to mounts array
@@ -505,7 +505,7 @@ list_mounts () {
   len="$(count "${mounts}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No mounts have found"
+    echo 'No mounts have found'
     return 0
   fi
 
@@ -527,7 +527,7 @@ mount_partition () {
     pick_disk || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
 
-    pick_partition "${path}" "unmounted" || return $?
+    pick_partition "${path}" unmounted || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
@@ -548,13 +548,13 @@ mount_partition () {
   fi
 
   # Otherwise try to mount it as encrypted partition
-  ask_secret "Enter the encryption password:" || return $?
+  ask_secret 'Enter the encryption password:' || return $?
   local password="${REPLY}"
 
   mount_encrypted "${path}" "${password}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to mount partition"
+    echo 'Failed to mount partition'
     return 2
   fi
 
@@ -572,7 +572,7 @@ unmount_partition () {
     pick_disk || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
 
-    pick_partition "${path}" "mounted" || return $?
+    pick_partition "${path}" mounted || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
@@ -583,7 +583,7 @@ unmount_partition () {
     echo "Partition ${path} is already unmounted"
     return 2
   elif is_system_partition "${path}"; then
-    echo "Cannot unmount system partition"
+    echo 'Cannot unmount system partition'
     return 2
   fi
 
@@ -597,7 +597,7 @@ unmount_partition () {
   unmount_encrypted "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to unmount partition"
+    echo 'Failed to unmount partition'
     return 2
   fi
 
@@ -611,7 +611,7 @@ mount_rom () {
   local path="${1}"
 
   if [[ -z "${path}" ]]; then
-    pick_rom "unmounted" || return $?
+    pick_rom unmounted || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
@@ -626,7 +626,7 @@ mount_rom () {
   mount_device "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to mount rom"
+    echo 'Failed to mount rom'
     return 2
   fi
 
@@ -640,7 +640,7 @@ unmount_rom () {
   local path="${1}"
 
   if [[ -z "${path}" ]]; then
-    pick_rom "mounted" || return $?
+    pick_rom mounted || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
@@ -655,7 +655,7 @@ unmount_rom () {
   unmount_device "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to unmount rom"
+    echo 'Failed to unmount rom'
     return 2
   fi
 
@@ -670,7 +670,7 @@ mount_image () {
   local path="${1}"
 
   if [[ ! -f "${path}" ]]; then
-    echo "Not valid image file"
+    echo 'Not valid image file'
     return 2
   fi
 
@@ -686,7 +686,7 @@ mount_image () {
   fuseiso -p "${path}" "${mount_point}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to mount image file"
+    echo 'Failed to mount image file'
 
     rm -rf "${mount_point}"
     return 2
@@ -719,23 +719,23 @@ unmount_image () {
     len="$(count "${mounts}")" || return 1
 
     if [[ ${len} -eq 0 ]]; then
-      echo "No image mounts have found"
+      echo 'No image mounts have found'
       return 0
     fi
 
-    pick_one "Select an image mount:" "${mounts}" "vertical" || return $?
+    pick_one 'Select an image mount:' "${mounts}" vertical || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
   if [[ ! -d "${path}" ]]; then
-    echo "No valid image mount path"
+    echo 'No valid image mount path'
     return 2
   fi
 
   fusermount -u "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to unmount image file system"
+    echo 'Failed to unmount image file system'
     return 2
   fi
 
@@ -755,26 +755,26 @@ mount_shared_folder () {
     [[ -n "${REPLY}" ]] && host="${REPLY}" || return 0
   fi
 
-  ask "Enter a shared folder:" || return $?
+  ask 'Enter a shared folder:' || return $?
   local folder="${REPLY}"
 
-  ask "Enter the username:" || return $?
+  ask 'Enter the username:' || return $?
   local username="${REPLY}"
 
-  ask "Enter the workgroup [WORKGROUP]:" || return $?
+  ask 'Enter the workgroup [WORKGROUP]:' || return $?
   local workgroup="${REPLY:-"WORKGROUP"}"
 
   local uri="smb://${workgroup};${username}@${host}/${folder,,}"
 
   if gio mount -l | grep -q "${uri}"; then
-    echo "Shared folder is already mounted"
+    echo 'Shared folder is already mounted'
     return 2
   fi
 
   gio mount "${uri}" 2> /dev/null
   
   if [[ $? -ne 0 ]]; then
-    echo "Failed to mount shared folder"
+    echo 'Failed to mount shared folder'
     return 2
   fi
 
@@ -813,23 +813,23 @@ unmount_shared_folder () {
     len="$(count "${uris}")" || return 1
 
     if [[ ${len} -eq 0 ]]; then
-      echo "No mounted shared folders have found"
+      echo 'No mounted shared folders have found'
       return 0
     fi
 
-    pick_one "Select a shared folder:" "${uris}" "vertical" || return $?
+    pick_one 'Select a shared folder:' "${uris}" vertical || return $?
     [[ -n "${REPLY}" ]] && uri="${REPLY}" || return 0
   fi
 
   if ! gio mount -l | grep -q "${uri}"; then
-    echo "Shared folder is not mounted"
+    echo 'Shared folder is not mounted'
     return 2
   fi
 
   sync && gio mount -u "${uri}" 2> /dev/null
   
   if [[ $? -ne 0 ]]; then
-    echo "Failed to umount shared folder"
+    echo 'Failed to umount shared folder'
     return 2
   fi
 
@@ -853,11 +853,11 @@ format_disk () {
     echo "Unable to find disk ${path}"
     return 2
   elif is_system_disk "${path}"; then
-    echo "Cannot format the system disk"
+    echo 'Cannot format the system disk'
     return 2
   fi
 
-  ask "Enter the disk label:" ".+" || return $?
+  ask 'Enter the disk label:' '.+' || return $?
   local label="${REPLY}"
 
   local fs_type=''
@@ -869,23 +869,23 @@ format_disk () {
     jq -cr '"\(.vendor|gsub("^\\s+|\\s+$";"")) \(.model) \(.size)"')" || return 1
 
   echo "ALL DATA in ${model} [${path}],"
-  echo "will be irreversibly gone forever!"
-  confirm "Do you really want to proceed?" || return $?
+  echo 'will be irreversibly gone forever!'
+  confirm 'Do you really want to proceed?' || return $?
   [[ "${REPLY}" != "yes" ]] && return 0
 
-  echo "Unmounting disk partitions..."
+  echo 'Unmounting disk partitions...'
   unmount_partitions "${path}" || return 1
 
-  echo "Cleaning disk partitions..."
+  echo 'Cleaning disk partitions...'
   clean_partitions "${path}" &&
-  echo "Partition table is ready" || return 1
+  echo 'Partition table is ready' || return 1
 
-  echo "Creating disk partition..."
-  create_partition "${path}" "${fs_type}" "1Mib" "100%" &&
-  echo "Primary partition created" || return 1
+  echo 'Creating disk partition...'
+  create_partition "${path}" "${fs_type}" 1Mib 100% &&
+  echo 'Primary partition created' || return 1
 
-  echo "Formatting disk partition..."
-  format_partition "${path}" "1" "${fs_type}" "${label}"
+  echo 'Formatting disk partition...'
+  format_partition "${path}" 1 "${fs_type}" "${label}"
 
   if [[ $? -ne 0 ]]; then
     echo "Failed to format disk ${path}"
@@ -910,27 +910,27 @@ eject_disk () {
     echo "Unable to find disk ${path}"
     return 2
   elif is_system_disk "${path}"; then
-    echo "Cannot eject the system disk"
+    echo 'Cannot eject the system disk'
     return 2
   fi
 
-  echo "Unmounting disk partitions..."
+  echo 'Unmounting disk partitions...'
 
   unmount_partitions "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to unmount disk partitions"
+    echo 'Failed to unmount disk partitions'
     return 2
   fi
 
   udisksctl power-off -b "${path}" &> /dev/null
 
   if [[ $? -eq 0 ]]; then
-    echo "Disk power set to off"
-    echo "Unplug safely the disk device"
+    echo 'Disk power set to off'
+    echo 'Unplug safely the disk device'
   else
-    echo "Unable to power disk off"
-    echo "Unplug the disk device at your own risk"
+    echo 'Unable to power disk off'
+    echo 'Unplug the disk device at your own risk'
   fi
 }
 
@@ -954,7 +954,7 @@ scan_disk () {
   fi
   
   if ! sudo smartctl -i "${path}" &> /dev/null; then
-    echo "Unable to retrieve SMART data"
+    echo 'Unable to retrieve SMART data'
     return 2
   fi
 
@@ -1024,10 +1024,10 @@ scan_disk () {
 
   sudo smartctl -iHj "${path}" | jq -cer "\"${query}\""
 
-  local code="$?"
+  local code=$?
 
   if [[ ${code} -ne 0 ]] && [[ ${code} -ne 24 ]]; then
-    echo "Failed to parse SMART data"
+    echo 'Failed to parse SMART data'
     return 2
   fi
 }
@@ -1048,7 +1048,7 @@ create_encrypted () {
     echo "Unable to find disk ${path}"
     return 2
   elif is_system_disk "${path}"; then
-    echo "Cannot encrypt the system disk"
+    echo 'Cannot encrypt the system disk'
     return 2
   fi
 
@@ -1056,10 +1056,10 @@ create_encrypted () {
   pick_fs_type || return $?
   [[ -n "${REPLY}" ]] && fs_type="${REPLY}" || return 0
 
-  ask_secret "Enter the encryption password:" ".+" || return $?
+  ask_secret 'Enter the encryption password:' '.+' || return $?
   local password="${REPLY}"
 
-  if ! confirm_secret "Retype the encryption password:" "${password}"; then
+  if ! confirm_secret 'Retype the encryption password:' "${password}"; then
     echo 'Encryption password does not match'
     return 2
   fi
@@ -1069,23 +1069,23 @@ create_encrypted () {
     jq -cr '"\(.vendor|gsub("^\\s+|\\s+$";"")) \(.model) \(.size)"')" || return 1
 
   echo "ALL DATA in ${model} [${path}],"
-  echo "will be irreversibly gone forever!"
-  confirm "Do you really want to proceed?" || return $?
+  echo 'will be irreversibly gone forever!'
+  confirm 'Do you really want to proceed?' || return $?
   [[ "${REPLY}" != "yes" ]] && return 0
 
-  echo "Unmounting disk partitions..."
+  echo 'Unmounting disk partitions...'
   unmount_partitions "${path}" || return 1
 
-  echo "Cleaning disk partitions..."
+  echo 'Cleaning disk partitions...'
   clean_partitions "${path}" &&
-  echo "Partition table is ready" || return 1
+  echo 'Partition table is ready' || return 1
 
-  echo "Creating disk partition..."
-  create_partition "${path}" "${fs_type}" "1Mib" "100%" &&
-  echo "Primary partition created" || return 1
+  echo 'Creating disk partition...'
+  create_partition "${path}" "${fs_type}" 1Mib 100% &&
+  echo 'Primary partition created' || return 1
 
-  echo "Formatting disk partition..."
-  format_partition "${path}" "1" "${fs_type}" &&
+  echo 'Formatting disk partition...'
+  format_partition "${path}" 1 "${fs_type}" &&
   echo "Partition ${path}1 has been formated" || return 1
 
   # Create a seed file with 350 random characters
@@ -1096,7 +1096,7 @@ create_encrypted () {
 
   sudo veracrypt -t --create "${path}1" --password "${password}" \
     --volume-type normal --encryption AES --hash sha-512 --filesystem "${fs_type}" \
-    --pim 0 --keyfiles "" --random-source "${rand_text_file}"
+    --pim 0 --keyfiles '' --random-source "${rand_text_file}"
 
   if [[ $? -ne 0 ]]; then
     echo "Failed to encrypt disk ${path}"
@@ -1121,11 +1121,11 @@ create_bootable () {
     echo "Unable to find disk ${path}"
     return 2
   elif is_system_disk "${path}"; then
-    echo "Cannot create bootable on the system disk"
+    echo 'Cannot create bootable on the system disk'
     return 2
   fi
 
-  confirm "Do you want to download the latest iso?" || return $?
+  confirm 'Do you want to download the latest iso?' || return $?
   [[ -z "${REPLY}" ]] && return 0
 
   local iso_file_path=''
@@ -1142,7 +1142,7 @@ create_bootable () {
     hosts="[${hosts}]"
 
     local host=''
-    pick_one "Select a mirror host:" "${hosts}" "vertical" || return $?
+    pick_one 'Select a mirror host:' "${hosts}" vertical || return $?
     [[ -n "${REPLY}" ]] && host="${REPLY}" || return 0
 
     local file='archlinux-x86_64.iso'
@@ -1154,7 +1154,7 @@ create_bootable () {
     )
 
     if [[ -f "${output}/${file}" ]]; then
-      echo "An existing iso file is found"
+      echo 'An existing iso file is found'
     else
       files+=("${host}/${file}")
     fi
@@ -1166,38 +1166,38 @@ create_bootable () {
     download "${output}" "${files[@]}"
 
     if [[ $? -ne 0 ]]; then
-      echo "Unable to download archlinux files"
+      echo 'Unable to download archlinux files'
       return 2
     fi
 
     sq --force wkd get pierre@archlinux.org -o "${output}/release-key.pgp"
 
     if [[ $? -ne 0 ]]; then
-      echo "Unable to fetch the release key"
+      echo 'Unable to fetch the release key'
       return 2
     fi
 
-    echo "Verifying the integrity of files..."
+    echo 'Verifying the integrity of files...'
 
     cd ${output} &&
     b2sum --ignore-missing -c b2sums.txt &&
     sq verify --signer-file release-key.pgp --detached "${file}.sig" "${file}" 2>&1 | awk NF
 
     if [[ $? -ne 0 ]]; then
-      echo "Failed to verify archlinux files"
+      echo 'Failed to verify archlinux files'
       return 2
     fi
 
-    echo "Files have been verified successfully"
+    echo 'Files have been verified successfully'
 
     iso_file_path="${output}/${file}"
   else
-    ask "Enter the path to the iso file:" "^/.+" || return $?
+    ask 'Enter the path to the iso file:' '^/.+' || return $?
     iso_file_path="${REPLY}"
   fi
 
   if [[ ! -f "${iso_file_path}" ]]; then
-    echo "Invalid or unknown archlinux iso file"
+    echo 'Invalid or unknown archlinux iso file'
     return 2
   fi
 
@@ -1206,30 +1206,30 @@ create_bootable () {
 
   echo ''
   echo "ALL DATA in ${model} [${path}],"
-  echo "will be irreversibly gone forever!"
-  confirm "Do you really want to proceed?" || return $?
+  echo 'will be irreversibly gone forever!'
+  confirm 'Do you really want to proceed?' || return $?
   [[ "${REPLY}" != "yes" ]] && return 0
 
-  echo "Unmounting disk partitions..."
+  echo 'Unmounting disk partitions...'
   unmount_partitions "${path}" || return 1
 
-  echo "Cleaning disk partitions..."
+  echo 'Cleaning disk partitions...'
   clean_partitions "${path}" &&
-  echo "Partition table is ready" || return 1
+  echo 'Partition table is ready' || return 1
 
-  echo "Creating disk partition..."
-  create_partition "${path}" "fat32" "1Mib" "100%" &&
-  echo "Primary partition created" || return 1
+  echo 'Creating disk partition...'
+  create_partition "${path}" fat32 1Mib 100% &&
+  echo 'Primary partition created' || return 1
 
-  echo "Formatting the bootable disk..."
-  format_partition "${path}" "1" "fat32" || return 1
+  echo 'Formatting the bootable disk...'
+  format_partition "${path}" 1 fat32 || return 1
 
-  echo "Flashing installation files..."
+  echo 'Flashing installation files...'
 
   sudo dd "if=${iso_file_path}" "of=${path}" bs=4M conv=fsync oflag=direct status=progress
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to flash installation files"
+    echo 'Failed to flash installation files'
   fi
 
   echo "Bootable disk ${path} is ready"
diff --git a/tools/disks/helpers b/tools/disks/helpers
--- a/tools/disks/helpers
+++ b/tools/disks/helpers
@@ -123,7 +123,7 @@ find_partition () {
   volume="$(echo "${volume}" | jc --veracrypt | jq -cer "${query}")" || return 1
 
   # Merge partition and volume data into an object
-  jq -ncer --argjson p "${part}" --argjson v "${volume}" "\$p + \$v" || return 1
+  jq -ncer --argjson p "${part}" --argjson v "${volume}" '\$p + \$v' || return 1
 }
 
 # Returns the list of rom block devices.
@@ -377,7 +377,7 @@ mount_encrypted () {
 
   mkdir -p "${mount_point}" &&
   sudo veracrypt -t --mount "${path}" "${mount_point}" --password "${password}" \
-    --pim 0 --keyfiles "" --protect-hidden no --non-interactive &> /dev/null
+    --pim 0 --keyfiles '' --protect-hidden no --non-interactive &> /dev/null
 
   if [[ $? -ne 0 ]]; then
     rm -rf "${mount_point}"
@@ -442,7 +442,7 @@ unmount_partitions () {
   volumes="$(echo "${volumes}" | jc --veracrypt | jq -cr '.[]|.path')" || return 1
   
   if [[ -z "${parts}" ]] && [[ -z "${volumes}" ]]; then
-    echo "No mounted partitions have found"
+    echo 'No mounted partitions have found'
     return 0
   fi
 
@@ -509,7 +509,7 @@ create_partition () {
   fi
 
   # Use ntfs as fs type for exfat file systems
-  [[ "${fs_type}" == "exfat" ]] && fs_type="ntfs"
+  [[ "${fs_type}" == "exfat" ]] && fs_type='ntfs'
   
   sudo parted --script -a optimal -- "${path}" mkpart primary "${fs_type}" "${start}" "${end}" &&
   sudo parted --script -- "${path}" align-check optimal 1 || return 1
@@ -538,12 +538,12 @@ format_partition () {
   fi
 
   case "${fs_type}" in
-    "ext2") sudo mkfs.ext2 -L "${label}" "${path}${index}" | awk NF;;
-    "ext3") sudo mkfs.ext3 -L "${label}" "${path}${index}" | awk NF;;
-    "ext4") sudo mkfs.ext4 -L "${label}" "${path}${index}" | awk NF;;
-    "ntfs") sudo mkfs.ntfs -f -L "${label}" "${path}${index}" | awk NF;;
-    "exfat") sudo mkfs.exfat -L "${label}" "${path}${index}" | awk NF;;
-    "fat32") sudo mkfs.fat -F 32 -n "${label}" "${path}${index}" | awk NF;;
+    ext2) sudo mkfs.ext2 -L "${label}" "${path}${index}" | awk NF;;
+    ext3) sudo mkfs.ext3 -L "${label}" "${path}${index}" | awk NF;;
+    ext4) sudo mkfs.ext4 -L "${label}" "${path}${index}" | awk NF;;
+    ntfs) sudo mkfs.ntfs -f -L "${label}" "${path}${index}" | awk NF;;
+    exfat) sudo mkfs.exfat -L "${label}" "${path}${index}" | awk NF;;
+    fat32) sudo mkfs.fat -F 32 -n "${label}" "${path}${index}" | awk NF;;
     *) return 1;;
   esac
 
@@ -590,7 +590,7 @@ pick_disk () {
   disks="$(find_disks)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find disks"
+    echo 'Unable to find disks'
     return 2
   fi
 
@@ -598,7 +598,7 @@ pick_disk () {
   len="$(count "${disks}")" || return 1
   
   if [[ ${len} -eq 0 ]]; then
-    echo "No disks have found"
+    echo 'No disks have found'
     return 2
   fi
 
@@ -615,7 +615,7 @@ pick_disk () {
 
   disks="$(echo "${disks}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a disk:" "${disks}" "vertical" || return $?
+  pick_one 'Select a disk:' "${disks}" vertical || return $?
 }
 
 # Shows a menu asking the user to select one partition
@@ -658,7 +658,7 @@ pick_partition () {
 
   parts="$(echo "${parts}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a partition:" "${parts}" "vertical" || return $?
+  pick_one 'Select a partition:' "${parts}" vertical || return $?
 }
 
 # Shows a menu asking the user to select one rom block
@@ -700,7 +700,7 @@ pick_rom () {
 
   roms="$(echo "${roms}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a rom:" "${roms}" "vertical" || return $?
+  pick_one 'Select a rom:' "${roms}" vertical || return $?
 }
 
 # Shows a menu asking the user to select one host, where the
@@ -710,13 +710,13 @@ pick_rom () {
 # Outputs:
 #  A menu of host names.
 pick_host () {
-  echo "Searching hosts in local network..."
+  echo 'Searching hosts in local network...'
 
   local hosts=''
   hosts="$(find_hosts)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find hosts"
+    echo 'Unable to find hosts'
     return 2
   fi
 
@@ -724,7 +724,7 @@ pick_host () {
   len="$(count "${hosts}")" || return 1
   
   if [[ ${len} -eq 0 ]]; then
-    echo "No hosts have found"
+    echo 'No hosts have found'
     return 2
   fi
 
@@ -735,7 +735,7 @@ pick_host () {
 
   hosts="$(echo "${hosts}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a host:" "${hosts}" "vertical" || return $?
+  pick_one 'Select a host:' "${hosts}" vertical || return $?
 }
 
 # Shows a menu asking the user to select one file system type,
@@ -754,6 +754,6 @@ pick_fs_type () {
   values+='{"key": "fat32", "value": "FAT32"}'
   values="[${values}]"
 
-  pick_one "Select a file system type:" "${values}" "vertical" || return $?
+  pick_one 'Select a file system type:' "${values}" vertical || return $?
 }
 
diff --git a/tools/langs/commands b/tools/langs/commands
--- a/tools/langs/commands
+++ b/tools/langs/commands
@@ -48,19 +48,19 @@ set_keymap () {
     }')" || return 1
     maps="[${maps::-1}]"
 
-    pick_one "Select a keymap:" "${maps}" "vertical" || return $?
+    pick_one 'Select a keymap:' "${maps}" vertical || return $?
     [[ -n "${REPLY}" ]] && map="${REPLY}" || return 0
   fi
 
   if ! localectl --no-pager list-keymaps | grep -qE "^${map}$"; then
-    echo "Invalid keymap value"
+    echo 'Invalid keymap value'
     return 2
   fi
 
   localectl set-keymap --no-convert "${map}"
   
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set keymap"
+    echo 'Failed to set keymap'
     return 2
   fi
 
@@ -80,25 +80,25 @@ set_language () {
     }')" || return 1
     languages="[${languages::-1}]"
 
-    pick_one "Select a language:" "${languages}" "vertical" || return $?
+    pick_one 'Select a language:' "${languages}" vertical || return $?
     [[ -n "${REPLY}" ]] && language="${REPLY}" || return 0
   fi
 
   if [[ ! "${language}" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
-    echo "Invalid language value"
+    echo 'Invalid language value'
     return 2
   elif ! cat /etc/locale.gen | grep -qE "^#?${language} .*$"; then
-    echo "Invalid or unknown language"
+    echo 'Invalid or unknown language'
     return 2
   fi
 
   sudo sed -i "s/\(LANG=\).*/\1${language}/" /etc/locale.conf &&
    sudo sed -i "s/\(LANGUAGE=\).*/\1${language}:en:C/" /etc/locale.conf &&
-   unset "LANG" "LANGUAGE" &&
+   unset LANG LANGUAGE &&
    source /etc/profile.d/locale.sh
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set language"
+    echo 'Failed to set language'
     return 2
   fi
 
@@ -119,7 +119,7 @@ set_locale () {
   properties+='NAME|ADDRESS|TELEPHONE|MEASUREMENT|IDENTIFICATION'
 
   if [[ ! "${name}" =~ (${properties}) ]]; then
-    echo "Invalid locale variable name"
+    echo 'Invalid locale variable name'
     return 2
   fi
   
@@ -130,15 +130,15 @@ set_locale () {
     }')" || return 1
     locales="[${locales::-1}]"
 
-    pick_one "Select a locale:" "${locales}" "vertical" || return $?
+    pick_one 'Select a locale:' "${locales}" vertical || return $?
     [[ -n "${REPLY}" ]] && locale="${REPLY}" || return 0
   fi
 
   if [[ ! "${locale}" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
-    echo "Invalid locale value"
+    echo 'Invalid locale value'
     return 2
   elif ! cat /etc/locale.gen | grep -qE "^#?${locale} .*$"; then
-    echo "Invalid or unknown locale"
+    echo 'Invalid or unknown locale'
     return 2
   fi
 
@@ -147,7 +147,7 @@ set_locale () {
    source /etc/profile.d/locale.sh
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set locale variable"
+    echo 'Failed to set locale variable'
     return 2
   fi
 
@@ -167,12 +167,12 @@ set_options () {
     }')" ||  return 1
     options="[${options::-1}]"
 
-    pick_one "Select an options value:" "${options}" "vertical" || return $?
+    pick_one 'Select an options value:' "${options}" vertical || return $?
     [[ -n "${REPLY}" ]] && value="${REPLY}" || return 0
   fi
   
   if ! localectl --no-pager list-x11-keymap-options | grep -qw "${value}"; then
-    echo "Invalid keyboard options value"
+    echo 'Invalid keyboard options value'
     return 2
   fi
 
@@ -184,11 +184,11 @@ set_options () {
   model="$(cat /etc/X11/xorg.conf.d/00-keyboard.conf |
     awk '/XkbModel/{print $3}' | tr -d '"')" || return 1
 
-  localectl --no-convert set-x11-keymap "${layouts}" "${model}" "" "${value}" &&
+  localectl --no-convert set-x11-keymap "${layouts}" "${model}" '' "${value}" &&
    setxkbmap -layout "${layouts}" -model "${model}" -option "${value}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set keyboard options"
+    echo 'Failed to set keyboard options'
     return 2
   fi
 
@@ -208,12 +208,12 @@ set_model () {
     }')" || return 1
     models="[${models::-1}]"
 
-    pick_one "Select a model:" "${models}" "vertical" || return $?
+    pick_one 'Select a model:' "${models}" vertical || return $?
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
   
   if ! localectl --no-pager list-x11-keymap-models | grep -qw "${name}"; then
-    echo "Invalid keyboard model value"
+    echo 'Invalid keyboard model value'
     return 2
   fi
 
@@ -225,11 +225,11 @@ set_model () {
   options="$(cat /etc/X11/xorg.conf.d/00-keyboard.conf |
     awk '/XkbOptions/{print $3}' | tr -d '"')" || return 1
 
-  localectl --no-convert set-x11-keymap "${layouts}" "${name}" "" "${options}" &&
+  localectl --no-convert set-x11-keymap "${layouts}" "${name}" '' "${options}" &&
    setxkbmap -layout "${layouts}" -model "${value}" -option "${options}"
   
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set keyboard model"
+    echo 'Failed to set keyboard model'
     return 2
   fi
 
@@ -250,18 +250,18 @@ add_locale () {
     }')" || return 1
     locales="[${locales::-1}]"
 
-    pick_one "Select a locale:" "${locales}" "vertical" || return $?
+    pick_one 'Select a locale:' "${locales}" vertical || return $?
     [[ -n "${REPLY}" ]] && locale="${REPLY}"  || return 0
   fi
 
   if [[ ! "${locale}" =~ ^[a-zA-Z[:blank:]0-9_.-]+$ ]]; then
-    echo "Malformed locale value"
+    echo 'Malformed locale value'
     return 2
   elif grep -qE "^\s*${locale}\s*$" /etc/locale.gen; then
     echo "Locale ${locale} is already added"
     return 2
   elif ! grep -qE "^\s*#\s*${locale}\s*$" /etc/locale.gen; then
-    echo "Invalid or unknown locale"
+    echo 'Invalid or unknown locale'
     return 2
   fi
 
@@ -269,7 +269,7 @@ add_locale () {
    sudo locale-gen
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to add locale"
+    echo 'Failed to add locale'
     return 2
   fi
 
@@ -289,21 +289,21 @@ remove_locale () {
     }')" || return 1
     locales="[${locales::-1}]"
 
-    pick_one "Select a locale:" "${locales}" "vertical" || return $?
+    pick_one 'Select a locale:' "${locales}" vertical || return $?
     [[ -n "${REPLY}" ]] && locale="${REPLY}" || return 0
   fi
 
   if [[ ! "${locale}" =~ ^[a-zA-Z[:blank:]0-9_.-]+$ ]]; then
-    echo "Malformed locale value"
+    echo 'Malformed locale value'
     return 2
   elif grep -qE "^\s*#\s*${locale}\s*$" /etc/locale.gen; then
     echo "Locale ${locale} is already removed"
     return 2
   elif ! grep -qE "^\s*${locale}\s*$" /etc/locale.gen; then
-    echo "Invalid or unknown locale"
+    echo 'Invalid or unknown locale'
     return 2
   elif [[ "${locale}" == "en_US.UTF-8 UTF-8" ]]; then
-    echo "Cannot remove the default locale"
+    echo 'Cannot remove the default locale'
     return 2
   fi
 
@@ -311,7 +311,7 @@ remove_locale () {
    sudo locale-gen
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to remove locale"
+    echo 'Failed to remove locale'
     return 2
   fi
 
@@ -331,15 +331,15 @@ add_layout () {
     }')" || return 1
     languages="[${languages::-1}]"
 
-    pick_one "Select a language:" "${languages}" "vertical" || return $?
+    pick_one 'Select a language:' "${languages}" vertical || return $?
     [[ -n "${REPLY}" ]] && language="${REPLY}" || return 0
   fi
 
   if [[ ! "${language}" =~ ^[a-z]{2,6}$ ]]; then
-    echo "Invalid language value"
+    echo 'Invalid language value'
     return 2
   elif ! localectl --no-pager list-x11-keymap-layouts | grep -qw "${language}"; then
-    echo "Invalid or unknown language"
+    echo 'Invalid or unknown language'
     return 2
   fi
 
@@ -353,7 +353,7 @@ add_layout () {
   fi
 
   if [[ -n "${layouts}" ]]; then
-    confirm "Want to set it as default?" || return $?
+    confirm 'Want to set it as default?' || return $?
     [[ -z "${REPLY}" ]] && return 0
 
     if [[ "${REPLY}" == "yes" ]]; then
@@ -373,11 +373,11 @@ add_layout () {
   options="$(cat /etc/X11/xorg.conf.d/00-keyboard.conf |
     awk '/XkbOptions/{print $3}' | tr -d '"')" || return 1
 
-  localectl --no-convert set-x11-keymap "${layouts}" "${model}" "" "${options}" &&
+  localectl --no-convert set-x11-keymap "${layouts}" "${model}" '' "${options}" &&
    setxkbmap -layout "${layouts}" -model "${model}" -option "${options}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to add layout"
+    echo 'Failed to add layout'
     return 2
   fi
 
@@ -395,7 +395,7 @@ remove_layout () {
     awk '/XkbLayout/{print $3}' | tr -d '"')" || return 1
 
   if [[ -z "${layouts}" ]]; then
-    echo "No keyboard layouts have set yet"
+    echo 'No keyboard layouts have set yet'
     return 0
   fi
 
@@ -406,21 +406,21 @@ remove_layout () {
     }')" || return 1
     languages="[${languages::-1}]"
 
-    pick_one "Select a language:" "${languages}" "horizontal" || return $?
+    pick_one 'Select a language:' "${languages}" horizontal || return $?
     [[ -n "${REPLY}" ]] && language="${REPLY}" || return 0
   fi
 
   if [[ ! "${language}" =~ ^[a-z]{2,6}$ ]]; then
-    echo "Invalid language value"
+    echo 'Invalid language value'
     return 2
   elif ! localectl --no-pager list-x11-keymap-layouts | grep -qw "${language}"; then
-    echo "Invalid or unknown language"
+    echo 'Invalid or unknown language'
     return 2
   elif [[ "${language}" == "us" ]]; then
-    echo "Cannot remove the default layout"
+    echo 'Cannot remove the default layout'
     return 2
   elif [[ "${layouts}" == "${language}" ]]; then
-    echo "Cannot remove the only keyboard layout"
+    echo 'Cannot remove the only keyboard layout'
     return 2
   elif [[ ! "${layouts}" =~ "${language}" ]]; then
     echo "Layout ${language} not found in layouts"
@@ -441,11 +441,11 @@ remove_layout () {
   options="$(cat /etc/X11/xorg.conf.d/00-keyboard.conf |
     awk '/XkbOptions/{print $3}' | tr -d '"')" || return 1
 
-  localectl --no-convert set-x11-keymap "${layouts}" "${model}" "" "${options}" &&
+  localectl --no-convert set-x11-keymap "${layouts}" "${model}" '' "${options}" &&
    setxkbmap -layout "${layouts}" -model "${model}" -option "${options}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to remove layout"
+    echo 'Failed to remove layout'
     return 2
   fi
 
@@ -472,14 +472,14 @@ order_layouts () {
   len="$(count "${layouts}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No keyboard layouts have set yet"
+    echo 'No keyboard layouts have set yet'
     return 0
   elif [[ ${len} -eq 1 ]]; then
-    echo "Only one layout has found"
+    echo 'Only one layout has found'
     return 0
   fi
 
-  pick_many "Pick layouts by order:" "${layouts}" "all" "horizontal" || return $?
+  pick_many 'Pick layouts by order:' "${layouts}" all horizontal || return $?
   [[ -z "${REPLY}" ]] && return 0
 
   local ordered=''
@@ -493,11 +493,11 @@ order_layouts () {
   options="$(cat /etc/X11/xorg.conf.d/00-keyboard.conf |
     awk '/XkbOptions/{print $3}' | tr -d '"')" || return 1
 
-  localectl --no-convert set-x11-keymap "${ordered}" "${model}" "" "${options}" &&
+  localectl --no-convert set-x11-keymap "${ordered}" "${model}" '' "${options}" &&
    setxkbmap -layout "${ordered}" -model "${model}" -option "${options}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set layouts order"
+    echo 'Failed to set layouts order'
     return 2
   fi
 
diff --git a/tools/networks/commands b/tools/networks/commands
--- a/tools/networks/commands
+++ b/tools/networks/commands
@@ -30,7 +30,7 @@ show_status () {
   devices="$(find_devices)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read network devices"
+    echo 'Unable to read network devices'
     return 2
   fi
 
@@ -52,7 +52,7 @@ show_status () {
   curl -s 'http://ip-api.com/json' | jq -cer "\"${query}\""
 
   if [[ $? -ne 0 ]]; then
-    echo "ISP:         Unavailable"
+    echo 'ISP:         Unavailable'
   fi
 
   local proxy=''
@@ -113,8 +113,8 @@ show_device () {
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
 
-  if ! validate "device" "${name}"; then
-    echo "Invalid or unknown device"
+  if ! validate device "${name}"; then
+    echo 'Invalid or unknown device'
     return 2
   fi
 
@@ -154,8 +154,8 @@ show_connection () {
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
 
-  if ! validate "connection" "${name}"; then
-    echo "Invalid or unknown connection"
+  if ! validate connection "${name}"; then
+    echo 'Invalid or unknown connection'
     return 2
   fi
 
@@ -196,7 +196,7 @@ list_devices () {
   devices="$(find_devices)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read network devices"
+    echo 'Unable to read network devices'
     return 2
   fi
 
@@ -204,7 +204,7 @@ list_devices () {
   len="$(count "${devices}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No network devices have found"
+    echo 'No network devices have found'
     return 0
   fi
 
@@ -228,7 +228,7 @@ list_connections () {
   connections="$(find_connections)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read network connections"
+    echo 'Unable to read network connections'
     return 2
   fi
 
@@ -236,7 +236,7 @@ list_connections () {
   len="$(count "${connections}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No network connections have found"
+    echo 'No network connections have found'
     return 0
   fi
 
@@ -261,30 +261,30 @@ list_wifis () {
   local signal="${2:-"0"}"
 
   if [[ -z "${device}" ]]; then
-    pick_device "wifi" || return $?
+    pick_device wifi || return $?
     [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
   fi
 
-  if ! validate "device" "${device}"; then
-    echo "Invalid or unknown device"
+  if ! validate device "${device}"; then
+    echo 'Invalid or unknown device'
     return 2
   fi
 
   if [[ ! "${signal}" =~ ^[0-9][0-9]{,2}$ ]]; then
-    echo "Invalid signal limit value"
+    echo 'Invalid signal limit value'
     return 2
   elif (( ${signal} < 0 || ${signal} > 100 )); then
-    echo "Signal limit value out of range"
+    echo 'Signal limit value out of range'
     return 2
   fi
 
-  echo "Detecting available wifi networks..."
+  echo 'Detecting available wifi networks...'
 
   local networks=''
   networks="$(find_wifis "${device}" "${signal}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to detect wifi networks"
+    echo 'Unable to detect wifi networks'
     return 2
   fi
 
@@ -292,7 +292,7 @@ list_wifis () {
   len="$(count "${networks}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No wifi networks have been detected"
+    echo 'No wifi networks have been detected'
     return 0
   fi
 
@@ -320,7 +320,7 @@ up () {
     elif [[ "${object}" == "connection" ]]; then
       pick_connection || return $?
     else
-      echo "Invalid or unknown network object"
+      echo 'Invalid or unknown network object'
       return 2
     fi
 
@@ -328,7 +328,7 @@ up () {
   fi
 
   if ! validate "${object}" "${name}"; then
-    echo "Invalid or unknown network object"
+    echo 'Invalid or unknown network object'
     return 2
   fi
 
@@ -362,7 +362,7 @@ down () {
     elif [[ "${object}" == "connection" ]]; then
       pick_connection || return $?
     else
-      echo "Invalid or unknown network object"
+      echo 'Invalid or unknown network object'
       return 2
     fi
 
@@ -370,7 +370,7 @@ down () {
   fi
 
   if ! validate "${object}" "${name}"; then
-    echo "Invalid or unknown network object"
+    echo 'Invalid or unknown network object'
     return 2
   fi
 
@@ -401,8 +401,8 @@ remove_device () {
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
 
-  if ! validate "device" "${name}"; then
-    echo "Invalid or unknown device"
+  if ! validate device "${name}"; then
+    echo 'Invalid or unknown device'
     return 2
   fi
 
@@ -411,7 +411,7 @@ remove_device () {
   nmcli device delete "${name}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to remove device"
+    echo 'Failed to remove device'
     return 2
   fi
 
@@ -429,8 +429,8 @@ remove_connection () {
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
 
-  if ! validate "connection" "${name}"; then
-    echo "Invalid or unknown connection"
+  if ! validate connection "${name}"; then
+    echo 'Invalid or unknown connection'
     return 2
   fi
 
@@ -439,7 +439,7 @@ remove_connection () {
   nmcli connection delete "${name}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to remove connection"
+    echo 'Failed to remove connection'
     return 2
   fi
 
@@ -450,7 +450,7 @@ remove_connection () {
 # Arguments:
 #  None
 add_ethernet_connection () {
-  ask "Enter the connection name:" ".+" || return $?
+  ask 'Enter the connection name:' '.+' || return $?
   local name="${REPLY}"
 
   if find_connection "${name}" &> /dev/null; then
@@ -459,40 +459,40 @@ add_ethernet_connection () {
   fi
 
   local device=''
-  pick_device "ethernet" || return $?
+  pick_device ethernet || return $?
   [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
 
   local dhcp=''
-  confirm "Want to enable DHCP mode?" || return $?
+  confirm 'Want to enable DHCP mode?' || return $?
   [[ -n "${REPLY}" ]] && dhcp="${REPLY}" || return 0
 
   echo "Creating ethernet connection ${name}..."
 
   if [[ "${dhcp}" == "yes" ]]; then
-    nmcli connection add type "ethernet" \
-      con-name "${name}" ifname "${device}" ipv4.method "auto"
+    nmcli connection add type ethernet \
+      con-name "${name}" ifname "${device}" ipv4.method auto
   else
     local re='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
 
-    ask "Enter the static ip:" "${re}" || return $?
+    ask 'Enter the static ip:' "${re}" || return $?
     local ip="${REPLY}"
 
-    ask "Enter the gateway:" "${re}" || return $?
+    ask 'Enter the gateway:' "${re}" || return $?
     local gateway="${REPLY}"
 
-    ask "Enter the primary DNS:" "${re}" || return $?
+    ask 'Enter the primary DNS:' "${re}" || return $?
     local dns="${REPLY}"
 
-    ask "Enter the secondary DNS:" "${re}" || return $?
+    ask 'Enter the secondary DNS:' "${re}" || return $?
     dns="${dns} ${REPLY}"
 
-    nmcli connection add type "ethernet" \
+    nmcli connection add type ethernet \
       con-name "${name}" ifname "${device}" ipv4.method "manual" \
       ipv4.addresses "${ip}/24" ipv4.gateway "${gateway}" ipv4.dns "${dns}"
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to create ethernet connection"
+    echo 'Failed to create ethernet connection'
     return 2
   fi
 
@@ -504,10 +504,10 @@ add_ethernet_connection () {
 #  None
 add_wifi_connection () {
   local device=''
-  pick_device "wifi" || return $?
+  pick_device wifi || return $?
   [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
 
-  echo "Detecting available wifi networks..."
+  echo 'Detecting available wifi networks...'
 
   local networks=''
   networks="$(find_wifis "${device}")" || return 1
@@ -516,7 +516,7 @@ add_wifi_connection () {
   len="$(count "${networks}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No wifi networks have been detected"
+    echo 'No wifi networks have been detected'
     return 0
   fi
 
@@ -526,10 +526,10 @@ add_wifi_connection () {
   networks="$(echo "${networks}" | jq -cer "${query}")" || return 1
 
   local ssid=''
-  pick_one "Select a wifi network:" "${networks}" "vertical" || return $?
+  pick_one 'Select a wifi network:' "${networks}" vertical || return $?
   [[ -n "${REPLY}" ]] && ssid="${REPLY}" || return 0
 
-  ask_secret "Enter the private key:" || return $?
+  ask_secret 'Enter the private key:' || return $?
   local key="${REPLY}"
 
   echo "Connecting to network ${ssid}..."
@@ -550,7 +550,7 @@ add_wifi_connection () {
 # Arguments:
 #  None
 add_vpn_connection () {
-  ask "Enter the path to ovpn file:" "^/.+" || return $?
+  ask 'Enter the path to ovpn file:' '^/.+' || return $?
   local file_path="${REPLY}"
 
   if [[ ! -f "${file_path}" ]]; then
@@ -563,14 +563,14 @@ add_vpn_connection () {
   name="${name%.*}"
 
   if [[ "${extension}" != "ovpn" ]]; then
-    echo "Invalid ovpn file type"
+    echo 'Invalid ovpn file type'
     return 2
   fi
 
-  ask "Enter the username:" ".+" || return $?
+  ask 'Enter the username:' '.+' || return $?
   local username="${REPLY}"
 
-  ask_secret "Enter the password:" ".+" || return $?
+  ask_secret 'Enter the password:' '.+' || return $?
   local password="${REPLY}"
 
   echo "Creating VPN connection ${name}..."
@@ -578,7 +578,7 @@ add_vpn_connection () {
   nmcli connection import type openvpn file "${file_path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to create VPN connection"
+    echo 'Failed to create VPN connection'
     return 2
   fi
 
@@ -596,7 +596,7 @@ add_proxy () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    echo "Missing the proxy profile name"
+    echo 'Missing the proxy profile name'
     return 2
   fi
 
@@ -613,29 +613,29 @@ add_proxy () {
     fi
   fi
 
-  ask "Enter the host:" ".+" || return $?
+  ask 'Enter the host:' '.+' || return $?
   local host="${REPLY}"
 
-  ask "Enter the port:" "^[0-9]+$" || return $?
+  ask 'Enter the port:' '^[0-9]+$' || return $?
   local port="${REPLY}"
 
-  confirm "Is this an authenticated proxy?" || return $?
+  confirm 'Is this an authenticated proxy?' || return $?
   [[ -z "${REPLY}" ]] && return 0
 
   if [[ "${REPLY}" == "yes" ]]; then
-    ask "Enter the username:" ".+" || return $?
+    ask 'Enter the username:' '.+' || return $?
     local username="${REPLY}"
 
-    ask_secret "Enter the password:" ".+" || return $?
+    ask_secret 'Enter the password:' '.+' || return $?
     local password="${REPLY}"
   fi
 
   local no_proxy='[]'
-  confirm "Want to set no proxy hosts?" || return $?
+  confirm 'Want to set no proxy hosts?' || return $?
   [[ -z "${REPLY}" ]] && return 0
 
   if [[ "${REPLY}" == "yes" ]]; then
-    ask "Enter no proxy hosts:" ".*" || return $?
+    ask 'Enter no proxy hosts:' '.*' || return $?
 
     local query='[split(" ")|.[]|if . and .!="" then . else empty end]'
     no_proxy="$(echo "\"${REPLY}\"" | jq -cer "${query}")" || return 1
@@ -674,7 +674,7 @@ remove_proxy () {
   local name="${1}"
 
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No proxy profiles have found"
+    echo 'No proxy profiles have found'
     return 0
   fi
 
@@ -712,7 +712,7 @@ remove_proxy () {
 #  A list of proxy profiles.
 list_proxies () {
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No proxy profiles have found"
+    echo 'No proxy profiles have found'
     return 0
   fi
 
@@ -723,7 +723,7 @@ list_proxies () {
   len="$(count "${proxies}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No proxy profiles have found"
+    echo 'No proxy profiles have found'
     return 0
   fi
 
@@ -746,7 +746,7 @@ set_proxy () {
   local name="${1}"
 
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo "No proxy profiles have found"
+    echo 'No proxy profiles have found'
     return 2
   fi
 
@@ -790,37 +790,37 @@ set_proxy () {
   echo "export NO_PROXY=\"${no_proxy}\"" >> "${PROXY_ENV_FILE}" &&
   sed -i "\|source \"${PROXY_ENV_FILE}\"|d" "${SHELLRC_FILE}" &&
   echo "source \"${PROXY_ENV_FILE}\"" >> "${SHELLRC_FILE}" ||
-    echo "Failed to set environment proxy variables"
+    echo 'Failed to set environment proxy variables'
 
   if which git &> /dev/null; then
     git config --global http.proxy "http://${uri}/" &&
     git config --global https.proxy "https://${uri}/" ||
-      echo "Failed to set git proxy settings"
+      echo 'Failed to set git proxy settings'
   fi
 
   if which npm &> /dev/null; then
     npm config set proxy "http://${uri}/" &&
     npm config set https-proxy "https://${uri}/" ||
-      echo "Failed to set npm proxy settings"
+      echo 'Failed to set npm proxy settings'
   fi
   
   if which yarn &> /dev/null; then
     yarn config set proxy "http://${uri}/" &&
     yarn config set https-proxy "https://${uri}/" ||
-      echo "Failed to set yarn proxy settings"
+      echo 'Failed to set yarn proxy settings'
   fi
 
   if which docker &> /dev/null; then
-    sudo mkdir -p "/etc/systemd/system/docker.service.d"
+    sudo mkdir -p /etc/systemd/system/docker.service.d
 
     printf '%s\n%s%s%s%s' \
-      "[Service]" \
-      "Environment=" \
+      '[Service]' \
+      'Environment=' \
       "\"HTTP_PROXY=http://${uri}/\" " \
       "\"HTTPS_PROXY=https://${uri}/\" " \
       "\"NO_PROXY=${no_proxy}\"" | sudo tee "${DOCKER_PROXY_FILE}" > /dev/null &&
     sudo systemctl daemon-reload ||
-      echo "Failed to set docker proxy settings"
+      echo 'Failed to set docker proxy settings'
   fi
 
   local host=''
@@ -829,7 +829,7 @@ set_proxy () {
   local port=''
   port="$(get "${proxy}" ".port")" || return 1
 
-  gsettings set org.gnome.system.proxy mode "manual"
+  gsettings set org.gnome.system.proxy mode manual
   gsettings set org.gnome.system.proxy.http host "${host}"
   gsettings set org.gnome.system.proxy.http port "${port}"
   gsettings set org.gnome.system.proxy.https host "${host}"
@@ -851,11 +851,11 @@ set_proxy () {
     gsettings set org.gnome.system.proxy.http authentication-password "${password}"
   else
     gsettings set org.gnome.system.proxy.http use-authentication false
-    gsettings set org.gnome.system.proxy.http authentication-user ""
-    gsettings set org.gnome.system.proxy.http authentication-password ""
+    gsettings set org.gnome.system.proxy.http authentication-user ''
+    gsettings set org.gnome.system.proxy.http authentication-password ''
   fi
 
-  local query=".no_proxy|if .|length > 0"
+  local query='.no_proxy|if .|length > 0'
   query+=" then \"[\([.[]|\"'\(.)'\"]|join(\",\"))]\" else [] end"
 
   local no_proxy=''
@@ -863,7 +863,7 @@ set_proxy () {
 
   gsettings set org.gnome.system.proxy ignore-hosts "${no_proxy}"
   
-  echo "Proxy settings have been applied"
+  echo 'Proxy settings have been applied'
 }
 
 # Reverts any proxy settings have been applied to
@@ -873,48 +873,48 @@ set_proxy () {
 unset_proxy () {
   rm -f "${PROXY_ENV_FILE}" &&
   sed -i "\|source \"${PROXY_ENV_FILE}\"|d" "${SHELLRC_FILE}" ||
-    echo "Failed to unset environment proxy variables"
+    echo 'Failed to unset environment proxy variables'
 
   if which git &> /dev/null &&
     git config --global --get http.proxy &> /dev/null; then
     git config --global --unset http.proxy &&
     git config --global --unset https.proxy ||
-      echo "Failed to unset git proxy settings"
+      echo 'Failed to unset git proxy settings'
   fi
 
   if which npm &> /dev/null; then
     npm config delete proxy &&
     npm config delete https-proxy ||
-      echo "Failed to set npm proxy settings"
+      echo 'Failed to set npm proxy settings'
   fi
   
   if which yarn &> /dev/null; then
     yarn config delete proxy &&
     yarn config delete https-proxy ||
-      echo "Failed to unset yarn proxy settings"
+      echo 'Failed to unset yarn proxy settings'
   fi
 
   if which docker &> /dev/null; then
     sudo rm -f "${DOCKER_PROXY_FILE}" &&
     sudo systemctl daemon-reload ||
-      echo "Failed to unset docker proxy settings"
+      echo 'Failed to unset docker proxy settings'
   fi
 
-  gsettings set org.gnome.system.proxy mode "none"
-  gsettings set org.gnome.system.proxy.http host ""
-  gsettings set org.gnome.system.proxy.http port "0"
-  gsettings set org.gnome.system.proxy.https host ""
-  gsettings set org.gnome.system.proxy.https port "0"
-  gsettings set org.gnome.system.proxy.ftp host ""
-  gsettings set org.gnome.system.proxy.ftp port "0"
-  gsettings set org.gnome.system.proxy.socks host ""
-  gsettings set org.gnome.system.proxy.socks port "0"
+  gsettings set org.gnome.system.proxy mode none
+  gsettings set org.gnome.system.proxy.http host ''
+  gsettings set org.gnome.system.proxy.http port 0
+  gsettings set org.gnome.system.proxy.https host ''
+  gsettings set org.gnome.system.proxy.https port 0
+  gsettings set org.gnome.system.proxy.ftp host ''
+  gsettings set org.gnome.system.proxy.ftp port 0
+  gsettings set org.gnome.system.proxy.socks host ''
+  gsettings set org.gnome.system.proxy.socks port 0
   gsettings set org.gnome.system.proxy.http use-authentication false
-  gsettings set org.gnome.system.proxy.http authentication-user ""
-  gsettings set org.gnome.system.proxy.http authentication-password ""
-  gsettings set org.gnome.system.proxy ignore-hosts "[]"
+  gsettings set org.gnome.system.proxy.http authentication-user ''
+  gsettings set org.gnome.system.proxy.http authentication-password ''
+  gsettings set org.gnome.system.proxy ignore-hosts '[]'
 
-  echo "Proxy settings have been unset"
+  echo 'Proxy settings have been unset'
 }
 
 # Sets the system networking to on or off.
@@ -924,10 +924,10 @@ power_network () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing mode value"
+    echo 'Missing mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid mode value"
+    echo 'Invalid mode value'
     return 2
   fi
 
@@ -950,10 +950,10 @@ power_wifi () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo "Missing mode value"
+    echo 'Missing mode value'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo "Invalid mode value"
+    echo 'Invalid mode value'
     return 2
   fi
 
diff --git a/tools/printers/commands b/tools/printers/commands
--- a/tools/printers/commands
+++ b/tools/printers/commands
@@ -24,7 +24,7 @@ show_status () {
   echo "API:       $(cups-config --api-version)"
   echo "Dir:       $(cups-config --datadir)"
 
-  find_jobs | jq -cer "\"Jobs:      \(length)\"" || return 1
+  find_jobs | jq -cer '"Jobs:      \(length)"' || return 1
 
   local destinations=''
   destinations="$(find_destinations |
@@ -41,7 +41,7 @@ show_status () {
 
     local destination=''
     while read -r destination; do
-      echo ""
+      echo ''
       find_destination "${destination}" | jq -cer "${query}" || return 1
     done <<< "${destinations}"
   fi
@@ -57,7 +57,7 @@ list_printers () {
   destinations="$(find_destinations)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read print destinations"
+    echo 'Unable to read print destinations'
     return 2
   fi
 
@@ -65,7 +65,7 @@ list_printers () {
   len="$(count "${destinations}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No printers have found"
+    echo 'No printers have found'
     return 0
   fi
 
@@ -126,7 +126,7 @@ add_printer () {
   local uri="${2}"
 
   if [[ -z "${name}" ]]; then
-    echo "Missing the name value"
+    echo 'Missing the name value'
     return 2
   elif exists_destination "${name}"; then
     echo "Printer with name ${name} already exists"
@@ -134,7 +134,7 @@ add_printer () {
   fi
 
   if [[ -z "${uri}" ]]; then
-    echo "Discovering print destinations..."
+    echo 'Discovering print destinations...'
 
     local query=''
     query+='{key: .uri, value: "\(.uri)\(.name|if (. and . != "") then " [\(.)]" else "" end)"}'
@@ -147,18 +147,18 @@ add_printer () {
     len="$(count "${destinations}")" || return 1
 
     if [[ ${len} -eq 0 ]]; then
-      echo "No printers have been discovered"
+      echo 'No printers have been discovered'
       return 0
     fi
 
-    pick_one "Select a printer:" "${destinations}" "vertical" || return $?
+    pick_one 'Select a printer:' "${destinations}" vertical || return $?
     [[ -n "${REPLY}" ]] && uri="${REPLY}" || return 0
   fi
 
-  ask "Enter a description:" ".+" || return $?
+  ask 'Enter a description:' '.+' || return $?
   local desc="${REPLY}"
 
-  ask "Enter a location name:" ".+" || return $?
+  ask 'Enter a location name:' '.+' || return $?
   local loc="${REPLY}"
 
   local driver=''
@@ -175,12 +175,12 @@ add_printer () {
   fi
 
   local is_default=''
-  confirm "Want to set this printer as default?" || return $?
+  confirm 'Want to set this printer as default?' || return $?
   [[ -n "${REPLY}" ]] && is_default="${REPLY}" || return 0
 
   if [[ "${is_default}" == "yes" ]]; then
     lpoptions -d "${name}" &> /dev/null ||
-      echo "Failed to set printer as default"
+      echo 'Failed to set printer as default'
   fi
 
   echo "Printer ${uri} has been added"
@@ -289,7 +289,7 @@ set_option () {
   fi
 
   if [[ -z "${key}" ]]; then
-    echo "Missing the option key value"
+    echo 'Missing the option key value'
     return 2
   elif [[ ! "${key}" =~ ^(Quality|PageSize|MediaType|TonerSaveMode|printer-error-policy)$ ]]; then
     echo "Option ${key} is not supported"
@@ -298,12 +298,12 @@ set_option () {
 
   if [[ -z "${value}" ]]; then
     case "${key}" in
-      "Quality") pick_quality || return $?;;
-      "PageSize") pick_page_size || return $?;;
-      "MediaType") pick_paper_type || return $?;;
-      "TonerSaveMode") pick_toner_mode || return $?;;
-      "printer-error-policy") pick_error_policy || return $?;;
-      *) echo "Unknown or invalid printer option" && return 2;;
+      Quality) pick_quality || return $?;;
+      PageSize) pick_page_size || return $?;;
+      MediaType) pick_paper_type || return $?;;
+      TonerSaveMode) pick_toner_mode || return $?;;
+      printer-error-policy) pick_error_policy || return $?;;
+      *) echo 'Unknown or invalid printer option' && return 2;;
     esac
 
     [[ -n "${REPLY}" ]] && value="${REPLY}" || return 0
@@ -317,7 +317,7 @@ set_option () {
   re+='abort-job|retry-current-job|retry-job|stop-printer'
 
   if [[ ! "${value,,}" =~ ^(${re,,})$ ]]; then
-    echo "Invalid option value"
+    echo 'Invalid option value'
     return 2
   fi
 
@@ -368,7 +368,7 @@ list_jobs () {
   jobs="$(find_jobs)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read print jobs"
+    echo 'Unable to read print jobs'
     return 2
   fi
 
@@ -376,7 +376,7 @@ list_jobs () {
   len="$(count "${jobs}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No active print jobs have found"
+    echo 'No active print jobs have found'
     return 0
   fi
 
@@ -420,15 +420,15 @@ cancel_job () {
 # Arguments:
 #  None
 restart () {
-  sudo echo "Restarting the cups service..."
+  sudo echo 'Restarting the cups service...'
 
   sudo systemctl restart cups.service
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to restart cups service"
+    echo 'Failed to restart cups service'
     return 2
   fi
 
-  echo "Cups service has been restarted"
+  echo 'Cups service has been restarted'
 }
 
diff --git a/tools/security/main b/tools/security/main
--- a/tools/security/main
+++ b/tools/security/main
@@ -12,45 +12,45 @@ source /opt/stack/security/commands
 #  A long help message.
 show_help () {
   if [[ "${1}" == "once" ]]; then
-    echo "Usage: security COMMAND [OBJECT] [ARGUMENTS]..."
+    echo 'Usage: security COMMAND [OBJECT] [ARGUMENTS]...'
 
-    echo -e "\nCOMMANDS"
-    printf " %-16s %s\n" \
-      "help" "Show this help message." \
-      "" "" \
-      "init locker" "Initialize the screen locker." \
-      "" "" \
-      "lock screen" "Lock the screen." \
-      "logout user" "Logout the user."
+    echo -e '\nCOMMANDS'
+    printf ' %-16s %s\n' \
+      'help' 'Show this help message.' \
+      '' '' \
+      'init locker' 'Initialize the screen locker.' \
+      '' '' \
+      'lock screen' 'Lock the screen.' \
+      'logout user' 'Logout the user.'
 
     return 0
   fi
 
-  echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."
+  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-  echo -e "\nCOMMANDS"
-  printf " %-25s %s\n" \
-    "help" "Show this help message." \
-    "" "" \
-    "show status" "Show the status of the system security." \
-    "" "" \
-    "set password" "Set a new user password." \
-    "set attempts <max>" "Set max failed attempts before password is blocked." \
-    "set unblock <time>" "Set password unblock time in secs." \
-    "set interval <time>" "Set consecutive password fails interval in secs." \
-    "" "" \
-    "set locker <mins>" "Set the interval of the screen locker," \
-    "" "where 0 means deactivate the locker."
+  echo -e '\nCOMMANDS'
+  printf ' %-25s %s\n' \
+    'help' 'Show this help message.' \
+    '' '' \
+    'show status' 'Show the status of the system security.' \
+    '' '' \
+    'set password' 'Set a new user password.' \
+    'set attempts <max>' 'Set max failed attempts before password is blocked.' \
+    'set unblock <time>' 'Set password unblock time in secs.' \
+    'set interval <time>' 'Set consecutive password fails interval in secs.' \
+    '' '' \
+    'set locker <mins>' 'Set the interval of the screen locker,' \
+    '' 'where 0 means deactivate the locker.'
 }
 
 loop () {
   clear
 
   while true; do
-    prompt "security" && history -s "${REPLY}"
+    prompt security && history -s "${REPLY}"
 
     set -f
-    set_separator "line"
+    set_separator line
     local cmd=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
@@ -67,18 +67,18 @@ loop () {
     fi
 
     case "${cmd[0]}" in
-      "show")
+      show)
         case "${cmd[1]}" in
-          "status") show_status;;
+          status) show_status;;
           *) echo 'Invalid or unknown command';;
         esac;;
-      "set")
+      set)
         case "${cmd[1]}" in
-          "locker") set_screen_locker "${cmd[2]}";;
-          "password") set_user_password;;
-          "attempts") set_faillock_attempts "${cmd[2]}";;
-          "unblock") set_faillock_unblock "${cmd[2]}";;
-          "interval") set_faillock_interval "${cmd[2]}";;
+          locker) set_screen_locker "${cmd[2]}";;
+          password) set_user_password;;
+          attempts) set_faillock_attempts "${cmd[2]}";;
+          unblock) set_faillock_unblock "${cmd[2]}";;
+          interval) set_faillock_interval "${cmd[2]}";;
           *) echo 'Invalid or unknown command';;
         esac;;
       *) echo 'Invalid or unknown command';; 
@@ -96,23 +96,23 @@ loop () {
 
 once () {
   case "${1}" in
-    "help") show_help once;;
-    "init")
+    help) show_help once;;
+    init)
       case "${2}" in
-        "locker") init_screen_locker || abort;;
-        *) abort "Invalid or unknown command";;
+        locker) init_screen_locker || abort;;
+        *) abort 'Invalid or unknown command';;
       esac;;
-    "lock")
+    lock)
       case "${2}" in
-        "screen") lock_screen;;
-        *) abort "Invalid or unknown command";;
+        screen) lock_screen;;
+        *) abort 'Invalid or unknown command';;
       esac;;
-    "logout")
+    logout)
       case "${2}" in
-        "user") logout_user;;
-        *) abort "Invalid or unknown command";;
+        user) logout_user;;
+        *) abort 'Invalid or unknown command';;
       esac;;
-    *) abort "Invalid or unknown command";;
+    *) abort 'Invalid or unknown command';;
   esac
 
   if [[ $? -ne 0 ]]; then
diff --git a/tools/trash/commands b/tools/trash/commands
--- a/tools/trash/commands
+++ b/tools/trash/commands
@@ -32,7 +32,7 @@ list_files () {
   elif [[ -z "${filter}" ]]; then
     query='.'
   else
-    echo "Invalid filter value"
+    echo 'Invalid filter value'
     return 2
   fi
 
@@ -40,7 +40,7 @@ list_files () {
   files="$(find_files | jq -cer "${query}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read trashed files"
+    echo 'Unable to read trashed files'
     return 2
   fi
 
@@ -48,7 +48,7 @@ list_files () {
   len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No trashed files have found"
+    echo 'No trashed files have found'
     return 0
   fi
 
@@ -81,7 +81,7 @@ restore_files () {
   }')"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read trashed files"
+    echo 'Unable to read trashed files'
     return 2
   fi
 
@@ -96,12 +96,12 @@ restore_files () {
   len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No files have found to restore"
+    echo 'No files have found to restore'
     return 0
   fi
 
   local selected=''
-  pick_many 'Select the files to restore:' "${files}" "1," "vertical" || return $?
+  pick_many 'Select the files to restore:' "${files}" '1,' vertical || return $?
   [[ -n "${REPLY}" ]] && selected="${REPLY}" || return 0
 
   selected="$(echo "${selected}" | jq -rec 'join(",")')" || return 1
@@ -111,7 +111,7 @@ restore_files () {
   trash-restore "${path}" &> /dev/null <<< "${selected}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to restore trashed files"
+    echo 'Failed to restore trashed files'
     return 2
   fi
 
@@ -132,7 +132,7 @@ remove_files () {
   files="$(find_files)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read trashed files"
+    echo 'Unable to read trashed files'
     return 2
   fi
 
@@ -140,7 +140,7 @@ remove_files () {
   len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No trashed files have found"
+    echo 'No trashed files have found'
     return 0
   fi
 
@@ -148,13 +148,13 @@ remove_files () {
     local query='[.[]|{key: .path, value: "\(.date) \(.path)"}]'
     files="$(echo "${files}" | jq -cer "${query}")" || return 1
 
-    pick_many "Select the files to remove:" "${files}" "1," "vertical" || return $?
+    pick_many 'Select which files to remove:' "${files}" '1,' vertical || return $?
     [[ -z "${REPLY}" ]] && return 0
 
     readarray -t paths < <(echo "${REPLY}" | jq -cr '.[]')
   fi
 
-  confirm "File(s) will be gone forever, proceed?" || return $?
+  confirm 'File(s) will be gone forever, proceed?' || return $?
   [[ "${REPLY}" != "yes" ]] && return 0
 
   local index=0
@@ -171,7 +171,7 @@ remove_files () {
   if [[ ${len} -gt 0 ]]; then
     echo "${len} trashed file(s) removed"
   else
-    echo "No trashed files have been removed"
+    echo 'No trashed files have been removed'
   fi
 }
 
@@ -186,17 +186,17 @@ empty_files () {
   len="$(find_files | jq -cer 'length')" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No trashed files have been found"
+    echo 'No trashed files have been found'
     return 0
   fi
   
   local prompt=''
   if [[ -z "${days}" ]]; then
-    prompt="ALL trashed files will be gone, proceed?"
+    prompt='ALL trashed files will be gone, proceed?'
   elif [[ "${days}" =~ ^[0-9]+$ ]]; then
     prompt="Files trashed more than ${days} days ago will be gone, proceed?"
   else
-    echo "Invalid days value"
+    echo 'Invalid days value'
     return 2
   fi
 
@@ -209,7 +209,7 @@ empty_files () {
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to remove trashed files"
+    echo 'Failed to remove trashed files'
     return 2
   fi
 
@@ -220,7 +220,7 @@ empty_files () {
   if [[ ${len} -gt 0 ]]; then
     echo "${len} trashed file(s) removed"
   else
-    echo "No trashed files have been removed"
+    echo 'No trashed files have been removed'
   fi
 }
 
@@ -232,7 +232,7 @@ trash_files () {
   local len=${#files[@]}
 
   if [[ ${len} -eq 0 ]]; then
-    abort "No files have given"
+    abort 'No files have been given'
   fi
 
   local trashed_len=0
