Add on script mode option to any tool

diff --git a/tools/bluetooth/commands b/tools/bluetooth/commands
--- a/tools/bluetooth/commands
+++ b/tools/bluetooth/commands
@@ -102,7 +102,7 @@ list_devices () {
   local status="${1}"
 
   if [[ -n "${status}" ]] && [[ ! "${status}" =~ ^(paired|connected|trusted|bonded)$ ]]; then
-    echo 'Invalid status value'
+    echo 'Invalid device status'
     return 2
   fi
 
@@ -140,13 +140,12 @@ show_controller () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
+    on_script_mode &&
+      echo 'Missing controller address' && return 2
+
     pick_controller || return $?
+    require 'Controller address required' || return 2
     address="${REPLY}"
-    
-    if [[ -z "${address}" ]]; then
-      echo 'No controller selected'
-      return 2
-    fi
   fi
 
   local controller=''
@@ -184,13 +183,12 @@ show_device () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
+    on_script_mode &&
+      echo 'Missing device address' && return 2
+  
     pick_device || return $?
+    require 'Device address required' || return 2
     address="${REPLY}"
-
-    if [[ -z "${address}" ]]; then
-      echo 'No device selected'
-      return 2
-    fi
   fi
 
   local device=''
@@ -230,13 +228,12 @@ set_controller () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
-    pick_controller || return $?
-    address="${REPLY}"
+    on_script_mode &&
+      echo 'Missing controller address' && return 2
 
-    if [[ -z "${address}" ]]; then
-      echo 'No controller selected'
-      return 2
-    fi
+    pick_controller || return $?
+    require 'Controller address required' || return 2
+    address="${REPLY}"
   fi
 
   local controller=''
@@ -330,7 +327,7 @@ set_discoverable () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo 'Missing the discoverable mode'
+    echo 'No discoverable mode given'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
     echo 'Invalid discoverable mode'
@@ -359,7 +356,7 @@ set_pairable () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo 'Missing the pairable mode'
+    echo 'No pairable mode given'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
     echo 'Invalid pairable mode'
@@ -388,13 +385,12 @@ connect_device () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
+    on_script_mode &&
+      echo 'Missing device address' && return 2
+  
     pick_device || return $?
+    require 'Device address required' || return 2
     address="${REPLY}"
-
-    if [[ -z "${address}" ]]; then
-      echo 'No device selected'
-      return 2
-    fi
   fi
 
   local device=''
@@ -424,13 +420,12 @@ disconnect_device () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
+    on_script_mode &&
+      echo 'Missing device address' && return 2
+  
     pick_device || return $?
+    require 'Device address required' || return 2
     address="${REPLY}"
-
-    if [[ -z "${address}" ]]; then
-      echo 'No device selected'
-      return 2
-    fi
   fi
 
   local device=''
@@ -458,13 +453,12 @@ remove_device () {
   local address="${1}"
 
   if [[ -z "${address}" ]]; then
+    on_script_mode &&
+      echo 'Missing device address' && return 2
+  
     pick_device || return $?
+    require 'Device address required' || return 2
     address="${REPLY}"
-
-    if [[ -z "${address}" ]]; then
-      echo 'No device selected'
-      return 2
-    fi
   fi
 
   local device=''
diff --git a/tools/desktop/commands b/tools/desktop/commands
--- a/tools/desktop/commands
+++ b/tools/desktop/commands
@@ -115,13 +115,12 @@ set_wallpaper () {
   local mode="${2}"
 
   if [[ -z "${name}" ]]; then
-    pick_wallpaper || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the wallpaper file name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No wallpaper selected'
-      return 2
-    fi 
+    pick_wallpaper || return $?
+    require 'Wallpaper file name required' || return 2
+    name="${REPLY}"
   fi
 
   if [[ "${name}" =~ /+ ]]; then
@@ -141,25 +140,16 @@ set_wallpaper () {
   fi
 
   if [[ -z "${mode}" ]]; then
-    local modes=''
-    modes+='{"key": "center", "value": "Center"},'
-    modes+='{"key": "fill", "value": "Fill"},'
-    modes+='{"key": "max", "value": "Max"},'
-    modes+='{"key": "scale", "value": "Scale"},'
-    modes+='{"key": "tile", "value": "Tile"}'
-    modes="[${modes}]"
+    on_script_mode &&
+      echo 'Missing the alignment mode' && return 2
 
-    pick_one 'Select a mode:' "${modes}" vertical || return $?
+    pick_alignment_mode || return $?
+    require 'Alignment mode is required' || return 2
     mode="${REPLY}"
-
-    if [[ -z "${mode}" ]]; then
-      echo 'No wallpaper mode selected'
-      return 2
-    fi
   fi
   
   if [[ ! "${mode}" =~ ^(center|fill|max|scale|tile)$ ]]; then
-    echo 'Invalid wallpaper mode'
+    echo 'Invalid alignment mode'
     return 2
   fi
 
@@ -178,41 +168,40 @@ set_wallpaper () {
 }
 
 # Shows the data of the pointing device with the
-# given id.
+# given name.
 # Arguments:
-#  id: the id of the pointing device
+#  name: the name of the pointing device
 # Outputs:
 #  A long list of pointing device data.
 show_pointer () {
-  local id="${1}"
+  local name="${1}"
 
-  if [[ -z "${id}" ]]; then
+  if [[ -z "${name}" ]]; then
+    on_script_mode &&
+      echo 'Missing pointer name' && return 2
+
     pick_pointer || return $?
-    id="${REPLY}"
-
-    if [[ -z "${id}" ]]; then
-      echo 'No pointer id selected'
-      return 2
-    fi
+    require 'Pointer name is required' || return 2
+    name="${REPLY}"
   fi
 
   local pointer=''
-  pointer="$(find_pointer "${id}")"
+  pointer="$(find_pointer "${name}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find pointer ${id}"
+    echo "Unable to find pointer ${name}"
     return 2
   fi
 
   local query=''
-  query+='ID:       \(.id)\n'
-  query+='Name:     \(.name)'
-  query+='\(.node|if . then "\nNode:     \(.)" else "" end)'
-  query+='\(.enabled|if . then "\nEnabled:  \(.)" else "" end)'
-  query+='\(.accel_speed|if . then "\nSpeed:    \(.)" else "" end)'
-  query+='\(.accel|if . then "\nAccel:    \(.)" else "" end)'
+  query+='ID:        \(.id)\n'
+  query+='Name:      \(.name)'
+  query+='\(.node|if . then "\nNode:      \(.)" else "" end)'
+  query+='\(.enabled|if . then "\nEnabled:   \(.)" else "" end)'
+  query+='\(.accel_speed|if . then "\nSpeed:     \(.)" else "" end)'
+  query+='\(.accel|if . then "\nAccel:     \(.)" else "" end)'
   query+='\(.velocity|if . then "\nVelocity:  \(.)" else "" end)'
-  query+='\(if .const_decel then "\nDecel:    \(.const_decel) \(.adapt_decel)" else "" end)'
+  query+='\(if .const_decel then "\nDecel:     \(.const_decel) \(.adapt_decel)" else "" end)'
 
   echo "${pointer}" | jq -cer "\"${query}\"" || return 1
 }
@@ -333,13 +322,12 @@ show_tablet () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_tablet || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the table name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No tablet selected'
-      return 2
-    fi
+    pick_tablet || return $?
+    require 'Tablet name is required' || return 2
+    name="${REPLY}"
   fi
 
   local tablet=''
@@ -411,13 +399,12 @@ scale_tablet () {
   local scale="${2}"
 
   if [[ -z "${name}" ]]; then
-    pick_tablet || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the tablet name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No tablet selected'
-      return 2
-    fi
+    pick_tablet || return $?
+    require 'Tablet name is required' || return 2
+    name="${REPLY}"
   fi
 
   local tablet=''
@@ -432,9 +419,15 @@ scale_tablet () {
   fi
 
   if [[ -z "${scale}" ]]; then
-    echo 'Missing scale factor'
-    return 2
-  elif [[ ! "${scale}" =~ ^[0-9]+\.?[0-9]*$ ]]; then
+    on_script_mode &&
+      echo 'Missing the scale factor' && return 2
+
+    ask 'Enter the scale factor [0.1-1]:' || return $?
+    require 'Scale factor is required' || return 2
+    scale="${REPLY}"
+  fi
+  
+  if [[ ! "${scale}" =~ ^[0-9]+\.?[0-9]*$ ]]; then
     echo 'Invalid scale factor'
     return 2
   elif (( $(echo "${scale} <= 0" | bc) )); then
@@ -480,23 +473,23 @@ scale_tablet () {
 }
 
 # Maps the area of the tablet with the given name
-# to a display device, where the special word desktop
-# resets the tablet's mapping and ratio.
+# to a target which could be any active display device
+# ot the special desktop value that resets the tablet's
+# mapping and ratio.
 # Arguments:
-#  name:    the name of a tablet device
-#  display: the name of a display device or desktop
+#  name:   the name of a tablet device
+#  target: the name of a display or desktop
 map_tablet () {
   local name="${1}"
-  local display="${2}"
+  local target="${2}"
 
   if [[ -z "${name}" ]]; then
-    pick_tablet || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the tablet name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No tablet selected'
-      return 2
-    fi
+    pick_tablet || return $?
+    require 'Tablet name is required' || return 2
+    name="${REPLY}"
   fi
 
   local tablet=''
@@ -510,18 +503,17 @@ map_tablet () {
     return 2
   fi
 
-  if [[ -z "${display}" ]]; then
-    pick_output 'Select a display:' active || return $?
-    display="${REPLY}"
+  if [[ -z "${target}" ]]; then
+    on_script_mode &&
+      echo 'Missing the mapping target' && return 2
 
-    if [[ -z "${display}" ]]; then
-      echo 'No display selected'
-      return 2
-    fi
+    pick_mapping_target || return $?
+    require 'Mapping target is required' || return 2
+    target="${REPLY}"
   fi
 
-  # Reset mapping and area if desktop is given
-  if [[ "${display}" == "desktop" ]]; then
+  # Reset mapping and area if desktop is given as target
+  if [[ "${target}" == "desktop" ]]; then
     xsetwacom --set "${name}" MapToOutput desktop &> /dev/null
 
     if [[ $? -ne 0 ]]; then
@@ -553,13 +545,13 @@ map_tablet () {
   fi
 
   local output=''
-  output="$(find_output "${display}")"
+  output="$(find_output "${target}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find display ${display}"
+    echo "Unable to find display ${target}"
     return 2
   elif ! is_active "${output}"; then
-    echo "Display ${display} is not active"
+    echo "Display ${target} is not active"
     return 2
   fi
 
@@ -583,7 +575,7 @@ map_tablet () {
     print 0" "0" "width" "height
   }')" || return 1
 
-  xsetwacom --set "${name}" MapToOutput "${display}" &> /dev/null &&
+  xsetwacom --set "${name}" MapToOutput "${target}" &> /dev/null &&
   xsetwacom --set "${name}" area "${area}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
@@ -591,7 +583,7 @@ map_tablet () {
     return 2
   fi
 
-  echo "Tablet ${name} mapped to ${display}"
+  echo "Tablet ${name} mapped to ${target}"
 }
 
 # Applies the pointer settings being set in the
diff --git a/tools/notifications/commands b/tools/notifications/commands
--- a/tools/notifications/commands
+++ b/tools/notifications/commands
@@ -14,7 +14,7 @@ start () {
     return 2
   fi
 
-  echo 'Starting the notifications service...'
+  echo 'Starting notifications service...'
 
   dunst > /dev/null 2>&1 &
 
@@ -25,12 +25,12 @@ start () {
     return 2
   fi
 
-  echo 'Notifications service has been started'
+  echo 'Notifications service started'
 }
 
 # Restarts the notifications service.
 restart () {
-  echo 'Restarting the notifications service...'
+  echo 'Restarting notifications service...'
 
   killall dunst || return 1
   sleep 1
@@ -44,7 +44,7 @@ restart () {
     return 2
   fi
 
-  echo 'Notifications service has been restarted'
+  echo 'Notifications service restarted'
 }
 
 # Returns the notifications state.
@@ -113,25 +113,18 @@ show_status () {
 # optionally given field and order.
 # Arguments:
 #  sort_by: id or appname, default is id
-#  order:   asc or desc, default is asc
 # Outputs:
 #  A long list of notificaions data.
 list_all () {
-  local sort_by="${1:-"id"}"
-  local order="${2:-"asc"}"
+  local sort_by="${1:-id}"
 
   if [[ ! "${sort_by}" =~ ^(id|appname)$ ]]; then
     echo 'Invalid sorting field'
     return 2
   fi
 
-  if [[ -n "${order}" ]] && [[ ! "${order}" =~ ^(asc|desc)$ ]]; then
-    echo 'Invalid ordering value'
-    return 2
-  fi
-
   local notifications=''
-  notifications="$(find_all "${sort_by}" "${order}")" || return 1
+  notifications="$(find_all "${sort_by}" asc)" || return 1
 
   local len=0
   len="$(count "${notifications}")" || return 1
@@ -187,17 +180,17 @@ clean_all () {
   echo 'All notifications have been removed'
 }
 
-# Enables or disables pop-up notifications.
+# Enables or disables popup notifications.
 # Arguments:
 #  mode: on or off
 set_popup () {
   local mode="${1}"
 
   if [[ -z "${mode}" ]]; then
-    echo 'Missing the pop-up mode'
+    echo 'Missing popup mode'
     return 2
   elif [[ ! "${mode}" =~ ^(on|off)$ ]]; then
-    echo 'Invalid pop-up mode'
+    echo 'Invalid popup mode'
     return 2
   fi
 
@@ -218,14 +211,14 @@ set_popup () {
   sed -i "s/\([[:blank:]]*transparency\).*/\1 = ${value}/" "${config_file}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set pop-up notifications to ${mode}"
+    echo "Failed to set popup notifications to ${mode}"
     return 2
   fi
 
   # Restart service so changes take effect
   restart
 
-  echo "Pop-up notifications set to ${mode}"
+  echo "Popup notifications set to ${mode}"
 }
 
 # Sets the volume of the notifications sound.
diff --git a/tools/printers/commands b/tools/printers/commands
--- a/tools/printers/commands
+++ b/tools/printers/commands
@@ -30,11 +30,9 @@ show_status () {
 
   if [[ -n "${destinations}" ]]; then
     local query=''
-    query+='Printer:   \(.name) \(if .is_shared == "true" then "[shared]" else "" end)\n'
-    query+='URI:       \(.uri)\n'
-    query+='Model:     \(.model)\n'
-    query+='Desc:      \(.description)\n'
-    query+='Location:  \(.location)'
+    query+='Printer:  \(.name) \(if .is_shared == "true" then "[shared]" else "" end)\n'
+    query+='URI:      \(.uri)'
+    query+='\(.model|if . and . != "" then "\nModel:    \(.model)" else "" end)'
     query="\"${query}\""
 
     local destination=''
@@ -83,13 +81,12 @@ show_printer () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Printer name is not given' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is not selected' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -100,19 +97,20 @@ show_printer () {
   local query=''
   query+='Name:       \(.name)\n'
   query+='URI:        \(.uri)\n'
-  query+='Model:      \(.model)\n'
-  query+='Desc:       \(.description)\n'
-  query+='Location:   \(.location)\n'
-  query+='Protocol:   \(.protocol)\n'
-  query+='State:      \(.state)\n'
-  query+='Accepts:    \(.accepting_jobs)\n'
-  query+='Shared:     \(.is_shared)\n'
-  query+='Temporary:  \(.is_temp)\n'
-  query+='Color:      \(.ColorModel) [\(.color)]\n'
-  query+='Quality:    \(.Quality)\n'
-  query+='Toner:      \(.TonerSaveMode)\n'
-  query+='Page:       \(.PageSize)\n'
-  query+='Paper:      \(.MediaType)'
+  query+='Protocol:   \(.protocol)'
+  query+='\(.model|if . and . != "" then "\nModel:      \(.)" else "" end)'
+  query+='\(.description|if . and . != "" then "\nDesc:       \(.)" else "" end)'
+  query+='\(.location|if . and . != "" then "\nLocation:   \(.)" else "" end)'
+  query+='\(.state|if . and . != "" then "\nState:      \(.)" else "" end)'
+  query+='\(.accepting_jobs|if . and . != "" then "\nAccepts:    \(.)" else "" end)'
+  query+='\(.shared|if . and . != "" then "\nShared:     \(.)" else "" end)'
+  query+='\(.is_temp|if . and . != "" then "\nTemporary:  \(.)" else "" end)'
+  query+='\(.ColorModel|if . and . != "" then "\nColor:      \(.)" else "" end)'
+  query+='\(.color|if . and . != "" then " [\(.)]" else "" end)'
+  query+='\(.Quality|if . and . != "" then "\nQuality:    \(.)" else "" end)'
+  query+='\(.TonerSaveMode|if . and . != "" then "\nToner:      \(.)" else "" end)'
+  query+='\(.PageSize|if . and . != "" then "\nPage:       \(.)" else "" end)'
+  query+='\(.MediaType|if . and . != "" then "\nPaper:      \(.)" else "" end)'
   query="\"${query}\""
 
   find_destination "${name}" | jq -cer "${query}" || return 1
@@ -130,60 +128,35 @@ add_printer () {
   local driver="${3}"
 
   if [[ -z "${uri}" ]]; then
-    echo 'Discovering print destinations...'
+    on_script_mode &&
+      echo 'Printer uri is not given' && return 2
 
-    local query=''
-    query+='{key: .uri, value: "\(.uri)\(.name|if (. and . != "") then " [\(.)]" else "" end)"}'
-    query="[.[]|${query}]"
-
-    local destinations=''
-    destinations="$(discover_destinations | jq -cer "${query}")"
-
-    if [[ $? -ne 0 ]]; then
-      echo 'Unable to discover print destinations'
-      return 2
-    fi
-
-    local len=0
-    len="$(count "${destinations}")" || return 1
-
-    if [[ ${len} -eq 0 ]]; then
-      echo 'No printers have been discovered'
-      return 2
-    fi
-
-    pick_one 'Select a printer:' "${destinations}" vertical || return $?
+    pick_uri || return $?
+    require 'Printer uri is required' || return 2
     uri="${REPLY}"
-
-    if [[ -z "${uri}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
   fi
 
   if [[ -z "${name}" ]]; then
+    on_script_mode &&
+      echo 'Missing the printer name' && return 2
+
     ask 'Enter the printer name:' || return $?
+    require 'Printer name is requried' || return 2
     name="${REPLY}"
-    
-    if [[ -z "${name}" ]]; then
-      echo 'No printer name is given'
-      return 2
-    fi
   fi
 
   if exists_destination "${name}"; then
-    echo "Printer with name ${name} already exists"
+    echo "Printer ${name} already exists"
     return 2
   fi
 
   if [[ -z "${driver}" ]]; then
-    pick_driver || return $?
-    driver="${REPLY}"
+    on_script_mode &&
+      echo 'Print driver is not given' && return 2
 
-    if [[ -z "${driver}" ]]; then
-      echo 'No driver selected'
-      return 2
-    fi
+    pick_driver || return $?
+    require 'Print driver is required' || return 2
+    driver="${REPLY}"
   fi
 
   if ! is_driver_available "${driver}"; then
@@ -191,16 +164,14 @@ add_printer () {
     return 2
   fi
 
-  lpadmin -p "${name}" -E \
-    -o printer-is-shared=false \
-    -D "${name}" -L "${name}" -v "${uri}" -m "${driver}" &> /dev/null
+  lpadmin -p "${name}" -E -o printer-is-shared=false  -v "${uri}" -m "${driver}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
     echo "Failed to add printer ${uri}"
     return 2
   fi
 
-  echo "Printer ${uri} has been added"
+  echo "Printer ${uri} added"
 }
 
 # Removes the printer destination with the
@@ -211,13 +182,12 @@ remove_printer () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing printer name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is required' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -243,13 +213,12 @@ share_printer () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing printer name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is required' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -275,13 +244,12 @@ unshare_printer () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing printer name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is required' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -310,13 +278,12 @@ set_option () {
   local value="${3}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the printer name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is required' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -325,21 +292,23 @@ set_option () {
   fi
 
   if [[ -z "${key}" ]]; then
-    pick_print_option || return $?
-    key="${REPLY}"
+    on_script_mode &&
+      echo 'Missing print option key' && return 2
 
-    if [[ -z "${key}" ]]; then
-      echo 'No print option selected'
-      return 2
-    fi
+    pick_print_option || return $?
+    require 'Print option key is required' || return 2
+    key="${REPLY}"
   fi
 
   if [[ ! "${key}" =~ ^(Quality|PageSize|MediaType|TonerSaveMode|printer-error-policy)$ ]]; then
-    echo 'Invalid print option'
+    echo 'Invalid print option key'
     return 2
   fi
 
   if [[ -z "${value}" ]]; then
+    on_script_mode &&
+      echo 'Missing the print option value' && return 2
+
     case "${key}" in
       Quality) pick_print_quality;;
       PageSize) pick_page_size;;
@@ -347,16 +316,11 @@ set_option () {
       TonerSaveMode) pick_toner_mode;;
       printer-error-policy) pick_error_policy;;
       *)
-        echo 'Unknown or invalid print option'
+        echo 'Unknown or invalid print option key'
         return 2;;
     esac || return $?
-
+    require 'Print option value is required' || return 2
     value="${REPLY}"
-
-    if [[ -z "${value}" ]]; then
-      echo 'No option value selected'
-      return 2
-    fi
   fi
    
   case "${key}" in
@@ -366,12 +330,12 @@ set_option () {
     TonerSaveMode) [[ "${value}" =~ ^(Save|Standard)$ ]];;
     printer-error-policy) [[ "${value}" =~ ^(abort-job|retry-current-job|retry-job|stop-printer)$ ]];;
     *)
-      echo 'Unknown or invalid print option'
+      echo 'Unknown or invalid print option key'
       return 2;;
   esac
 
   if [[ $? -ne 0 ]]; then
-    echo 'Invalid option value'
+    echo 'Invalid print option value'
     return 2
   fi
 
@@ -393,13 +357,12 @@ set_default () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
-    pick_printer || return $?
-    name="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the printer name' && return 2
 
-    if [[ -z "${name}" ]]; then
-      echo 'No printer selected'
-      return 2
-    fi
+    pick_printer || return $?
+    require 'Printer name is required' || return 2
+    name="${REPLY}"
   fi
 
   if ! exists_destination "${name}"; then
@@ -454,13 +417,12 @@ cancel_job () {
   local id="${1}"
 
   if [[ -z "${id}" ]]; then
-    pick_job || return $?
-    id="${REPLY}"
+    on_script_mode &&
+      echo 'Missing the print job id' && return 2
 
-    if [[ -z "${id}" ]]; then
-      echo 'No print job selected'
-      return 2
-    fi
+    pick_job || return $?
+    require 'Print job id is required' || return 2
+    id="${REPLY}"
   fi
 
   if ! exists_job "${id}"; then
@@ -480,7 +442,7 @@ cancel_job () {
 
 # Restarts the cup service.
 restart () {
-  sudo echo 'Restarting the cups service...'
+  echo 'Restarting the cups service...'
 
   sudo -k systemctl restart cups.service
 
diff --git a/tools/printers/helpers b/tools/printers/helpers
--- a/tools/printers/helpers
+++ b/tools/printers/helpers
@@ -235,6 +235,36 @@ pick_printer () {
   pick_one 'Select a printer:' "${destinations}" vertical || return $?
 }
 
+# Shows a menu asking the user to select a uri print destination
+# where the answer is kept in the global var REPLY.
+# Outputs:
+#  A menu of uri print destinations.
+pick_uri () {
+  echo 'Discovering print uri destinations...'
+
+  local query=''
+  query+='{key: .uri, value: "\(.uri)\(.name|if (. and . != "") then " [\(.)]" else "" end)"}'
+  query="[.[]|${query}]"
+
+  local destinations=''
+  destinations="$(discover_destinations | jq -cer "${query}")"
+
+  if [[ $? -ne 0 ]]; then
+    echo 'Unable to discover print uri destinations'
+    return 2
+  fi
+
+  local len=0
+  len="$(count "${destinations}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No print uri destinations discovered'
+    return 2
+  fi
+
+  pick_one 'Select print uri destination:' "${destinations}" vertical || return $?
+}
+
 # Returns the list of available printer drivers.
 # Outputs:
 #  A json array list of drivers.
@@ -294,7 +324,7 @@ pick_driver () {
     return 2
   fi
 
-  pick_one 'Select a driver:' "${drivers}" vertical || return $?
+  pick_one 'Select a print driver:' "${drivers}" vertical || return $?
 }
 
 # Shows a menu asking the user to select one print job,
diff --git a/tools/trash/commands b/tools/trash/commands
--- a/tools/trash/commands
+++ b/tools/trash/commands
@@ -63,84 +63,61 @@ list_files () {
 restore_files () {
   local paths=("$@")
 
-  # Find all trashed files
-  local trashed_files=''
-  trashed_files="$(trash-restore / <<< "" | awk '/^ *[0-9]+ /{
-    schema="\"key\": \"%s\","
-    schema=schema"\"value\": \"%s\""
-    schema="{"schema"},"
-
-    path=""
-    for (i = 4; i <= NF; i++) {
-      path=path$i
-      if (i < NF) path=path" "
-    }
-
-    printf schema, $1, path
-  }')"
-
-  if [[ $? -ne 0 ]]; then
-    echo 'Unable to read trashed files'
-    return 2
-  fi
-
-  # Remove the extra comma after the last element
-  if [[ -n "${trashed_files}" ]]; then
-    trashed_files="${trashed_files::-1}"
-  fi
-  
-  trashed_files="[${trashed_files}]"
+  # Find all trashed files eligible for restoring
+  local files=''
+  files="$(find_restorable_files)" || return 1
 
   local len=0
-  len="$(count "${trashed_files}")" || return 1
+  len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
     echo 'No trashed files found'
     return 2
   fi
 
-  local selected=''
+  local file_keys=''
 
   if [[ ${#paths[@]} -eq 0 ]]; then
-    pick_many 'Select which trashed files to restore:' "${trashed_files}" '1,' vertical || return $?
+    on_script_mode &&
+      echo 'No file paths are given' && return 2
+
+    pick_many 'Select files to restore:' "${files}" '1,' vertical || return $?
+    require 'File paths are required' || return 2
     local picked="${REPLY}"
 
-    if [[ -z "${picked}" ]]; then
-      echo 'No trashed files selected'
-      return 2
-    fi
-
+    # Refuse to overwrite existing files
     picked="$(echo "${picked}" | jq -cer 'join(" ")')" || return 1
 
-    # Refuse to overwrite existing files
     local key=''
     for key in ${picked}; do
+      # Match file by trash-restore index key
       local query=".[]|select(.key == \"${key}\")|.value"
 
       local path=''
-      path="$(echo "${trashed_files}" | jq -cr "${query}")"
+      path="$(echo "${files}" | jq -cr "${query}")"
 
       if [[ -f "${path}" ]]; then
         echo "Refused to overwrite file ${path}"
         continue
       fi
 
-      selected+="${key},"
+      file_keys+="${key},"
     done
 
     # Remove extra comma from the last element
-    if [[ -n "${selected}" ]]; then
-      selected="${selected::-1}"
+    if [[ -n "${file_keys}" ]]; then
+      file_keys="${file_keys::-1}"
     fi
   else
     local index=0
     for ((index = 0; index < ${#paths[@]}; index++)); do
       local path="${paths[index]}"
 
+      # Match file by file path
       local query=".[]|select(.value == \"${path}\")|.key"
 
       local key=''
-      key="$(echo "${trashed_files}" | jq -cer "${query}")"
+      key="$(echo "${files}" | jq -cer "${query}")"
 
       if [[ $? -ne 0 ]]; then
         echo "File ${path} not found in trash"
@@ -152,20 +129,20 @@ restore_files () {
         continue
       fi
 
-      selected+="${key},"
+      file_keys+="${key},"
     done
 
     # Discard possible duplicated files
-    if [[ -n "${selected}" ]]; then
-      selected="[${selected::-1}]"
-      selected="$(echo "${selected}" | jq -cr 'unique|join(",")')"
+    if [[ -n "${file_keys}" ]]; then
+      file_keys="[${file_keys::-1}]"
+      file_keys="$(echo "${file_keys}" | jq -cr 'unique|join(",")')"
     fi
   fi
 
-  trash-restore / &> /dev/null <<< "${selected}"
+  trash-restore / &> /dev/null <<< "${file_keys}"
 
   if [[ $? -ne 0 ]]; then
-    echo 'Failed to restore trashed files'
+    echo 'Failed to restore files'
     return 2
   fi
 
@@ -174,7 +151,7 @@ restore_files () {
   len=$((len - post_len))
 
   if [[ ${len} -eq 0 ]]; then
-    echo 'No trashed files restored'
+    echo 'No files restored'
     return 2
   fi
 
@@ -187,35 +164,31 @@ restore_files () {
 remove_files () {
   local paths=("$@")
 
-  local trashed_files=''
-  trashed_files="$(find_files)"
-
-  if [[ $? -ne 0 ]]; then
-    echo 'Unable to read trashed files'
-    return 2
-  fi
+  # Collect all trashed files eligible for removal
+  local files=''
+  files="$(find_files)" || return 1
 
   local len=0
-  len="$(count "${trashed_files}")" || return 1
+  len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
     echo 'No trashed files found'
     return 2
   fi
 
+  # Convert file list into key-value pairs
   local query='[.[]|{key: .path, value: "\(.date) \(.path)"}]'
-  trashed_files="$(echo "${trashed_files}" | jq -cer "${query}")" || return 1
+  files="$(echo "${files}" | jq -cer "${query}")" || return 1
   
   if [[ ${#paths[@]} -eq 0 ]]; then
-    pick_many 'Select which trashed files to remove:' "${trashed_files}" '1,' vertical || return $?
-    local selected="${REPLY}"
+    on_script_mode &&
+      echo 'No file paths are given' && return 2
 
-    if [[ -z "${selected}" ]]; then
-      echo 'No trashed files selected'
-      return 2
-    fi
+    pick_many 'Select files to remove:' "${files}" '1,' vertical || return $?
+    require 'File paths are required' || return 2
+    local selected_paths="${REPLY}"
 
-    readarray -t paths < <(echo "${selected}" | jq -cr '.[]')
+    readarray -t paths < <(echo "${selected_paths}" | jq -cr '.[]')
   fi
 
   if [[ -z "${FORCED}" ]] || [[ "${FORCED}" != "true" ]]; then
@@ -233,7 +206,7 @@ remove_files () {
     
     local query=".[]|select(.key == \"${path}\")"
 
-    echo "${trashed_files}" | jq -cer "${query}" &> /dev/null
+    echo "${files}" | jq -cer "${query}" &> /dev/null
 
     if [[ $? -ne 0 ]]; then
       echo "File ${path} not found in trash"
