Add cmds to list installed and outdated packages

diff --git a/tools/system/commands b/tools/system/commands
--- a/tools/system/commands
+++ b/tools/system/commands
@@ -66,3 +66,86 @@ show_status () {
   fi
 }
 
+# List the currently install packages filtered
+# by the given repository.
+# Arguments:
+#  repository: pacman, aur or none
+# Outputs:
+#  A long list of packages.
+list_packages () {
+  local repository="${1}"
+
+  if is_given "${repository}" && is_not_package_repository "${repository}"; then
+    echo 'Invalid or unknown repository'
+    return 2
+  fi
+
+  local pkgs=''
+  pkgs="$(find_installed_packages)"
+
+  if has_failed; then
+    echo 'Failed to find installed packages'
+    return 2
+  fi
+
+  local query=''
+  query+='Name:    \(.name)\n'
+  query+='Version: \(.version)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  if is_given "${repository}"; then
+    query=".${repository}|${query}"
+  else
+    query=".pacman + .aur|${query}"
+  fi
+
+  echo "${pkgs}" | jq -cer "${query}" || return 1
+}
+
+# List the currently outdated packages filtered
+# by the given repository.
+# Arguments:
+#  repository: pacman, aur or none
+# Outputs:
+#  A long list of packages.
+list_updates () {
+  local repository="${1}"
+
+  if is_given "${repository}" && is_not_package_repository "${repository}"; then
+    echo 'Invalid or unknown repository'
+    return 2
+  fi
+
+  echo 'Processing outdated packages...'
+
+  local pkgs=''
+  pkgs="$(find_outdated_packages)"
+
+  if has_failed; then
+    echo 'Failed to find outdated packages'
+    return 2
+  fi
+  
+  if is_given "${repository}"; then
+    pkgs="$(echo "${pkgs}" | jq -cr ".${repository}")"
+  else
+    pkgs="$(echo "${pkgs}" | jq -cr '.pacman + .aur')"
+  fi
+
+  local len=0
+  len="$(count "${pkgs}")" || return 1
+
+  if is_true "${len} = 0"; then
+    echo 'No outdated packages have found'
+    return 2
+  fi
+
+  local query=''
+  query+='Name:    \(.name)\n'
+  query+='Current: \(.current)\n'
+  query+='Latest:  \(.latest)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  echo "${pkgs}" | jq -cr "${query}" || return 1
+}
+
