Refine scripts of the power tool
This commit fixes:
* text in comments and docs
* text in output messages
* DRY code to helpers
* set charge cmd to set charge start stop
* show charge thresholds to show status
* cmds with one argument should fail in absence of that argument

diff --git a/tools/power/commands b/tools/power/commands
--- a/tools/power/commands
+++ b/tools/power/commands
@@ -5,11 +5,7 @@ set -o pipefail
 source /opt/stack/utils
 source /opt/stack/power/helpers
 
-SETTINGS_FILE="${CONFIG_HOME}/power.json"
-
 # Shows the current status of the system's power.
-# Arguments:
-#  None
 # Outputs:
 #  A verbose list of text data.
 show_status () {
@@ -61,6 +57,21 @@ show_status () {
   if [[ -n "${tlp_status}" ]]; then
     echo "${tlp_status}"
   fi
+
+  local config_file='/etc/tlp.d/00-main.conf'
+
+  local index=0
+  for index in 0 1; do
+    local start=''
+    start="$(grep -E "^START_CHARGE_THRESH_BAT${index}=" "${config_file}" | cut -d '=' -f 2)"
+    
+    local stop=''
+    stop="$(grep -E "^STOP_CHARGE_THRESH_BAT${index}=" "${config_file}" | cut -d '=' -f 2)"
+    
+    if [[ -n "${start}" ]] || [[ -n "${stop}" ]]; then
+      echo "Charge[${index}]:    [${start:-0}%, ${stop:-100}%]"
+    fi
+  done
 
   if [[ -f "${SETTINGS_FILE}" ]]; then
     local query='.screensaver.interval|if . then . else "" end'
@@ -118,7 +129,7 @@ show_status () {
   }' || return 1
 }
 
-# Sets the action of the hander with the given name.
+# Sets the action of the handler with the given name.
 # Arguments:
 #  handler: power, reboot, suspend, lid or docked
 #  action:  poweroff, reboot, suspend or ignore
@@ -127,55 +138,35 @@ set_action () {
   local action="${2}"
 
   if [[ -z "${handler}" ]]; then
-    local handlers=''
-    handlers+='{"key":"power", "value":"power"},'
-    handlers+='{"key":"reboot", "value":"reboot"},'
-    handlers+='{"key":"suspend", "value":"suspend"},'
-    handlers+='{"key":"lid", "value":"lid"},'
-    handlers+='{"key":"docked", "value":"docked"}'
-    handlers="[${handlers}]"
+    on_script_mode &&
+      echo 'Missing the power handler' && return 2
 
-    pick_one 'Select a power handler:' "${handlers}" vertical || return $?
+    pick_power_handler || return $?
+    require 'Power handler is required' || return 2
     handler="${REPLY}"
   fi
 
-  if [[ ! "${handler}" =~ ^(power|reboot|suspend|lid|docked)$ ]]; then
+  if ! validate_power_handler "${handler}"; then
     echo 'Invalid power handler'
     return 2
   fi
 
   if [[ -z "${action}" ]]; then
-    local actions=''
-    actions+='{"key":"poweroff", "value":"poweroff"},'
-    actions+='{"key":"reboot", "value":"reboot"},'
-    actions+='{"key":"suspend", "value":"suspend"},'
-    actions+='{"key":"ignore", "value":"ignore"}'
-    actions="[${actions}]"
+    on_script_mode &&
+      echo 'Missing power action' && return 2
 
-    pick_one 'Select an action:' "${actions}" vertical || return $?
+    pick_power_action || return $?
+    require 'Power action is required' || return 2
     action="${REPLY}"
   fi
 
-  if [[ ! "${action}" =~ ^(poweroff|reboot|suspend|ignore)$ ]]; then
+  if ! validate_power_action "${action}"; then
     echo 'Invalid power action'
     return 2
   fi
 
-  local option=''
-  if [[ "${handler}" == "power" ]]; then
-    option='HandlePowerKey'
-  elif [[ "${handler}" == "reboot" ]]; then
-    option='HandleRebootKey'
-  elif [[ "${handler}" == "suspend" ]]; then
-    option='HandleSuspendKey'
-  elif [[ "${handler}" == "lid" ]]; then
-    option='HandleLidSwitch'
-  elif [[ "${handler}" == "docked" ]]; then
-    option='HandleLidSwitchDocked'
-  else
-    echo 'Invalid power handler'
-    return 2
-  fi
+  # Resolve the logind config option for the handler
+  local option="$(convert_handler_to_option "${handler}")" || return $?
 
   local config_file='/etc/systemd/logind.conf.d/00-main.conf'
 
@@ -202,14 +193,12 @@ set_action () {
 }
 
 # Resets the action of all power handlers.
-# Arguments:
-#  None
 reset_actions () {
   local config_file='/etc/systemd/logind.conf.d/00-main.conf'
 
   if [[ ! -f "${config_file}" ]]; then
     echo 'Actions already set to defaults'
-    return 0
+    return 2
   fi
 
   sudo sed -i '/^HandlePowerKey=.*/d' "${config_file}"
@@ -236,30 +225,15 @@ set_screensaver () {
   local interval="${1}"
 
   if [[ -z "${interval}" ]]; then
-    ask 'Enter the interval in mins [0-60]:' || return $?
-    interval="${REPLY}"
-  fi
-  
-  if [[ ! "${interval}" =~ ^[0-9]{,2}$ ]]; then
-    echo 'Invalid or malformed interval'
+    echo 'Missing interval time'
+    return 2
+  elif [[ ! "${interval}" =~ ^[0-9]{,2}$ ]]; then
+    echo 'Invalid interval time'
     return 2
   elif [[ ${interval} -lt 0 ]] || [[ ${interval} -gt 60 ]]; then
-    echo 'Interval is out of range'
+    echo 'Interval time out of range'
     return 2
   fi
-
-  # Save screen saver interval into settings file
-  local settings='{}'
-  local screensaver="{\"interval\": ${interval}}"
-
-  if [[ -f "${SETTINGS_FILE}" ]]; then
-    settings="$(jq -e ".screensaver = ${screensaver} " "${SETTINGS_FILE}")" || return 1
-  else
-    settings="$(echo "{\"screensaver\": ${screensaver}}" | jq -e '.')" || return 1
-  fi
-
-  mkdir -p "${CONFIG_HOME}"
-  echo "${settings}" > "${SETTINGS_FILE}"
 
   if [[ ${interval} -gt 0 ]]; then
     local secs=$((interval*60))
@@ -275,21 +249,20 @@ set_screensaver () {
   fi
 
   echo "Screen saver set to ${interval} mins"
+  
+  save_screen_saver_to_settings "${interval}" ||
+    echo 'Failed to save screen saver to settings'
 }
 
 # Initializes the screen saver to the interval saved
 # in the settings file.
-# Arguments:
-#  None
 init_screensaver () {
-  if [[ ! -f "${SETTINGS_FILE}" ]]; then
-    echo 'No screen saver settings found'
-    return 2
+  local interval=5
+
+  if [[ -f "${SETTINGS_FILE}" ]]; then
+    interval="$(jq '.screensaver.interval|if . then . else 5 end' "${SETTINGS_FILE}")"
   fi
-
-  local interval=''
-  interval="$(jq '.screensaver.interval|if . then . else 5 end' "${SETTINGS_FILE}")"
-
+ 
   if [[ ${interval} -gt 0 ]]; then
     local secs=$((interval*60))
 
@@ -313,29 +286,22 @@ set_tlp () {
   local status="${1}"
 
   if [[ -z "${status}" ]]; then
-    local statuses=''
-    statuses+='{"key":"on", "value":"On"},'
-    statuses+='{"key":"off", "value":"Off"}'
-    statuses="[${statuses}]"
-
-    pick_one 'Set TLP status to:' "${statuses}" horizontal || return $?
-    status="${REPLY}"
-  fi
-
-  if [[ ! "${status}" =~ ^(on|off)$ ]]; then
-    echo 'Invalid TLP status'
+    echo 'Missing the power saving status'
+    return 2
+  elif [[ ! "${status}" =~ ^(on|off)$ ]]; then
+    echo 'Invalid power saving status'
     return 2
   fi
 
   if [[ "${status}" == "on" ]]; then
-    echo 'Enabling TLP service...'
+    echo 'Enabling power saving mode...'
     sudo systemctl stop acpid.service &> /dev/null &&
     sudo systemctl disable acpid.service &> /dev/null &&
     sudo systemctl enable tlp.service &> /dev/null &&
     sudo systemctl start tlp.service &> /dev/null &&
     sudo systemctl daemon-reload
   else
-    echo 'Disabling TLP service...'
+    echo 'Disabling power saving mode...'
     sudo systemctl stop tlp.service &> /dev/null &&
     sudo systemctl disable tlp.service &> /dev/null &&
     sudo systemctl enable acpid.service &> /dev/null &&
@@ -344,71 +310,68 @@ set_tlp () {
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set TLP to ${status}"
+    echo "Failed to set power saving mode to ${status}"
     return 2
   fi
 
-  echo "TLP has been set to ${status}"
+  echo "Power saving mode set to ${status}"
 }
 
-# Sets the battery charge start/stop threshold to the given
-# percentage limit.
+# Sets the battery charging start/stop thresholds to the given
+# percentage limits.
 # Arguments:
-#  action:    start or stop
-#  threshold: a percentage value between [0,100]
-set_charge () {
-  local action="${1}"
-  local threshold="${2}"
+#  start: the percent of capacity to start charging
+#  stop:  the percent of capacity to stop charging
+set_charging () {
+  local start="${1}"
+  local stop="${2}"
 
-  if [[ -z "${action}" ]]; then
-    local actions=''
-    actions+='{"key":"start", "value":"Start"},'
-    actions+='{"key":"stop", "value":"Stop"}'
-    actions="[${actions}]"
-
-    pick_one 'Which charge action to set:' "${actions}" horizontal || return $?
-    action="${REPLY}"
-  fi
-
-  if [[ ! "${action}" =~ ^(start|stop)$ ]]; then
-    echo 'Invalid charge action'
+  if [[ -z "${start}" ]]; then
+    echo 'Missing the charging start threshold'
+    return 2
+  elif [[ ! "${start}" =~ ^[0-9]{1,3}$ ]]; then
+    echo 'Invalid charging start threshold'
+    return 2
+  elif [[ ${start} -lt 0 ]] || [[ ${start} -gt 100 ]]; then
+    echo 'Charging start threshold is out of range'
     return 2
   fi
 
-  if [[ -z "${threshold}" ]]; then
-    ask 'Enter the charge threshold [0-100]:' || return $?
-    threshold="${REPLY}"
-  fi
-  
-  if [[ ! "${threshold}" =~ ^[0-9]{1,3}$ ]]; then
-    echo 'Invalid charge threshold value'
+  if [[ -z "${stop}" ]]; then
+    echo 'Missing the charging stop threshold'
     return 2
-  elif [[ ${threshold} -lt 0 ]] || [[ ${threshold} -gt 100 ]]; then
-    echo 'Charge threshold is out of range'
+  elif [[ ! "${stop}" =~ ^[0-9]{1,3}$ ]]; then
+    echo 'Invalid charging stop threshold'
+    return 2
+  elif [[ ${stop} -lt 0 ]] || [[ ${stop} -gt 100 ]]; then
+    echo 'Charging stop threshold is out of range'
+    return 2
+  fi
+
+  if [[ ${start} -ge ${stop} ]]; then
+    echo 'Start threshold should be lower than stop'
     return 2
   fi
 
   local config_file='/etc/tlp.d/00-main.conf'
 
   if [[ ! -f "${config_file}" ]]; then
-    sudo rm -f /etc/tlp.d/00-template.conf
+    sudo -k rm -f /etc/tlp.d/00-template.conf
     sudo touch "${config_file}"
-  fi
-
-  local option=''
-
-  if [[ "${action}" == "start" ]]; then
-    option='START_CHARGE_THRESH_BAT'
-  else
-    option='STOP_CHARGE_THRESH_BAT'
   fi
 
   local index=0
   for index in 0 1; do
-    if grep -qE "^${option}${index}=" "${config_file}"; then
-      sudo sed -i "s/^\(${option}${index}=\).*/\1${threshold}/" "${config_file}"
+    if grep -qE "^START_CHARGE_THRESH_BAT${index}=" "${config_file}"; then
+      sudo sed -i "s/^\(START_CHARGE_THRESH_BAT${index}=\).*/\1${start}/" "${config_file}"
     else
-      echo "${option}${index}=${threshold}" | sudo tee -a "${config_file}" > /dev/null
+      echo "START_CHARGE_THRESH_BAT${index}=${start}" | sudo tee -a "${config_file}" > /dev/null
+    fi
+    
+    if grep -qE "^STOP_CHARGE_THRESH_BAT${index}=" "${config_file}"; then
+      sudo sed -i "s/^\(STOP_CHARGE_THRESH_BAT${index}=\).*/\1${stop}/" "${config_file}"
+    else
+      echo "STOP_CHARGE_THRESH_BAT${index}=${stop}" | sudo tee -a "${config_file}" > /dev/null
     fi
   done
 
@@ -422,53 +385,45 @@ set_charge () {
     sudo systemctl restart tlp.service &> /dev/null || return 1
   fi
 
-  echo "Charge ${action} threshold set to ${threshold}%"
+  echo "Charging set to start at ${start}% and stop at ${stop}%"
 }
 
 # Shuts the system power down.
-# Arguments:
-#  None
 shutdown_system () {
   systemctl poweroff
 
   if [[ $? -ne 0 ]]; then
-    echo 'Unable to shutdown the system'
+    echo 'Failed to shutdown the system'
     return 2
   fi
 }
 
 # Reboots the system.
-# Arguments:
-#  None
 reboot_system () {
   systemctl reboot
 
   if [[ $? -ne 0 ]]; then
-    echo 'Unable to reboot the system'
+    echo 'Failed to reboot the system'
     return 2
   fi
 }
 
 # Sets system in suspend mode.
-# Arguments:
-#  None
 suspend_system () {
   systemctl suspend
 
   if [[ $? -ne 0 ]]; then
-    echo 'Unable to suspend the system'
+    echo 'Failed to suspend the system'
     return 2
   fi
 }
 
 # Blanks the screen immediately.
-# Arguments:
-#  None
 blank_screen () {
   xset dpms force off
 
   if [[ $? -ne 0 ]]; then
-    echo 'Unable to blank the screen'
+    echo 'Failed to blank the screen'
     return 2
   fi
 }
