Refine the trash tool scripts
This commit fixes:
* texts and syntax in help and docummentations
* user friendly text in outputs
* validation checks
* return codes when no files are proccessed to indicate failure
* various bugs

diff --git a/tools/trash/commands b/tools/trash/commands
--- a/tools/trash/commands
+++ b/tools/trash/commands
@@ -57,10 +57,10 @@ list_files () {
   echo "${files}" | jq -cer "${query}" || return 1
 }
 
-# Restores trashed files from the current dur or
-# the given path.
+# Restores trashed files starting from the root
+# directory or the given path.
 # Arguments:
-#  path: the path to restore files from
+#  path: the absolute path to restore files from
 restore_files () {
   local path="${1:-"/"}"
 
@@ -96,13 +96,18 @@ restore_files () {
   len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo 'No files have found to restore'
-    return 0
+    echo 'No trashed files found'
+    return 2
   fi
 
   local selected=''
-  pick_many 'Select the files to restore:' "${files}" '1,' vertical || return $?
-  [[ -n "${REPLY}" ]] && selected="${REPLY}" || return 0
+  pick_many 'Select which trashed files to restore:' "${files}" '1,' vertical || return $?
+  selected="${REPLY}"
+
+  if [[ -z "${selected}" ]]; then
+    echo 'No trashed files selected'
+    return 2
+  fi
 
   selected="$(echo "${selected}" | jq -rec 'join(",")')" || return 1
 
@@ -118,6 +123,11 @@ restore_files () {
   local post_len=0
   post_len="$(find_files | jq -cer 'length')" || return 1
   len=$((len - post_len))
+
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No trashed files restored'
+    return 2
+  fi
 
   echo "${len} file(s) have been restored"
 }
@@ -140,39 +150,48 @@ remove_files () {
   len="$(count "${files}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo 'No trashed files have found'
-    return 0
+    echo 'No trashed files found'
+    return 2
   fi
 
   if [ "${#paths[@]}" -eq 0 ]; then
     local query='[.[]|{key: .path, value: "\(.date) \(.path)"}]'
     files="$(echo "${files}" | jq -cer "${query}")" || return 1
 
-    pick_many 'Select which files to remove:' "${files}" '1,' vertical || return $?
-    [[ -z "${REPLY}" ]] && return 0
+    pick_many 'Select which trashed files to remove:' "${files}" '1,' vertical || return $?
+
+    if [[ -z "${REPLY}" ]]; then
+      echo 'No trashed files selected'
+      return 2
+    fi
 
     readarray -t paths < <(echo "${REPLY}" | jq -cr '.[]')
   fi
 
   confirm 'File(s) will be gone forever, proceed?' || return $?
-  [[ "${REPLY}" != "yes" ]] && return 0
+  
+  if [[ "${REPLY}" != "yes" ]]; then
+    echo 'No trashed files removed'
+    return 2
+  fi
 
   local index=0
   for ((index = 0; index < ${#paths[@]}; index++)); do
     local path="${paths[index]}"
 
-    trash-rm "${path}" || echo "Failed to remove file ${path}"
+    trash-rm "${path}"
   done
 
   local post_len=0
   post_len="$(find_files | jq -cer 'length')" || return 1
   len=$((len - post_len))
 
-  if [[ ${len} -gt 0 ]]; then
-    echo "${len} trashed file(s) removed"
-  else
-    echo 'No trashed files have been removed'
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No trashed files removed'
+    return 2
   fi
+  
+  echo "${len} trashed file(s) removed"
 }
 
 # Empties the trash from files trashed more than
@@ -182,31 +201,35 @@ remove_files () {
 empty_files () {
   local days="${1}"
   
+  if [[ -n "${days}" ]] && [[ ! "${days}" =~ ^[0-9]+$ ]]; then
+    echo 'Invalid days filter'
+    return 2
+  fi
+
   local len=0
   len="$(find_files | jq -cer 'length')" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo 'No trashed files have been found'
-    return 0
+    echo 'No trashed files found'
+    return 2
   fi
   
   local prompt=''
+
   if [[ -z "${days}" ]]; then
     prompt='ALL trashed files will be gone, proceed?'
-  elif [[ "${days}" =~ ^[0-9]+$ ]]; then
-    prompt="Files trashed more than ${days} days ago will be gone, proceed?"
   else
-    echo 'Invalid days value'
+    prompt="Files trashed more than ${days} days ago will be gone, proceed?"
+  fi
+  
+  confirm "${prompt}" || return $?
+
+  if [[ "${REPLY}" != "yes" ]]; then
+    echo 'No trashed files removed'
     return 2
   fi
 
-  confirm "${prompt}" || return $?
-
-  if [[ "${REPLY}" == "yes" ]]; then
-    trash-empty -f "${days:-0}"
-  else
-    return 0
-  fi
+  trash-empty -f "${days:-0}"
 
   if [[ $? -ne 0 ]]; then
     echo 'Failed to remove trashed files'
@@ -217,10 +240,11 @@ empty_files () {
   post_len="$(find_files | jq -cer 'length')" || return 1
   len=$((len - post_len))
 
-  if [[ ${len} -gt 0 ]]; then
-    echo "${len} trashed file(s) removed"
-  else
-    echo 'No trashed files have been removed'
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No trashed files removed'
+    return 2
   fi
+
+  echo "${len} trashed file(s) removed"
 }
 
