Have an alias to trash files via trash-cli

diff --git a/tools/trash/main b/tools/trash/main
--- a/tools/trash/main
+++ b/tools/trash/main
@@ -7,73 +7,45 @@ source /opt/stack/trash/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: trash [OPTIONS] FILE(S)...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: trash [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-8s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-    return 0
+    echo -e '\nCOMMANDS'
+    printf ' %-25s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [ARGUMENTS]...'
-  
-  echo -e '\nCOMMANDS'
-  printf ' %-20s %s\n' \
-    'help' 'Show this help message.' \
+  printf ' %-25s %s\n' \
+    'list files' 'List all trashed files.' \
+    'list files <days>' 'List files trashed within the given days.' \
+    'list files +<days>' 'List files trashed more than the given days ago.' \
+    'list files <date>' 'List files trashed at a certain date.' \
     '' '' \
-    'list' 'List all trashed files.' \
-    'list <days>' 'List files trashed within the given days.' \
-    'list +<days>' 'List files trashed more than the given days ago.' \
-    'list <date>' 'List files trashed at a certain date.' \
+    'restore files [<path>]' 'Restore files starting from / or the given path.' \
+    'remove files [<paths>]' 'Remove the given trashed files.' \
     '' '' \
-    'restore [<path>]' 'Restore files starting from / or the given path.' \
-    'remove [<paths>]' 'Remove the given trashed files.' \
-    '' '' \
-    'empty' 'Remove all trashed files.' \
-    'empty <days>' 'Remove files trashed more than the given days ago.'
+    'empty files' 'Remove all trashed files.' \
+    'empty files <days>' 'Remove files trashed more than the given days ago.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
 
-  while true; do
-    prompt trash && history -s "${REPLY}"
-
-    set -f
-    set_separator line
-    local args=($(xargs -n1 <<< "${REPLY}"))
-    restore_separator && set +f
-
-    local cmd="${args[0]}"
-
-    case "${cmd}" in
-      'help') show_help;;
-      'list') list_files "${args[1]}";;
-      'restore') restore_files "${args[1]}";;
-      'remove') remove_files "${args[@]:1}";;
-      'empty') empty_files "${args[1]}";;  
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
-      *)
-        echo 'Ooops, invalid or unknown command!'
-        $(return 2);;
-    esac && success || fail
-
-    REPLY=''
-  done
-
-  clear
-}
-
-once () {
   while getopts 'hq' opt; do
     case "${opt}" in
      'h')
@@ -81,27 +53,62 @@ once () {
         return 0;;
      'q') QUIET='true';;
      *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
     esac
   done
 
   shift $((OPTIND-1))
 
-  # Collect the given list of files
-  local files=()
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
-  while [[ $# -gt 0 ]]; do
-    files+=("${1}")
-    shift
+  while true; do
+    if [[ "${mode}" == "loop" ]]; then
+      prompt trash && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
+
+    set -f
+    set_separator line
+    local args=($(xargs -n1 <<< "${REPLY}"))
+    restore_separator && set +f
+    REPLY=''
+
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
+
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
+    case "${cmd}${obj:+ ${obj}}" in
+      'list files') list_files "${args[2]}";;
+      'restore files') restore_files "${args[2]}";;
+      'remove files') remove_files "${args[@]:2}";;
+      'empty files') empty_files "${args[2]}";;  
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
+
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
-  trash_files "${files[@]}"
+  clear
 }
 
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
