Refine scripts of the displays tools
This commit fixes:
* text in comments and documentation
* text in output messages
* missing arguments on script mode
* handing of optional and required arguments
* DRY code into helpers

diff --git a/tools/displays/helpers b/tools/displays/helpers
--- a/tools/displays/helpers
+++ b/tools/displays/helpers
@@ -4,6 +4,8 @@ set -o pipefail
 
 source /opt/stack/utils
 
+SETTINGS_FILE="${CONFIG_HOME}/displays.json"
+
 # Returns a list of outputs having the given status.
 # Arguments:
 #  status: all, connected, disconnected,
@@ -204,15 +206,13 @@ pick_output () {
 #  prompt:  a prompt text line
 #  status:  all, connected, disconnected, active,
 #           inactive, primary
-#  size:    the number of items must be selected
 #  skip:    the name of output to except from selection
 # Outputs:
 #  A menu of output names.
 pick_outputs () {
   local prompt="${1}"
   local status="${2}"
-  local size="${3}"
-  local skip="${4}"
+  local skip="${3}"
 
   local except='select(true)'
   [[ -n "${skip}" ]] && except="select(.device_name != \"${skip}\")"
@@ -235,7 +235,7 @@ pick_outputs () {
     return 2
   fi
 
-  pick_many "${prompt}" "${options}" "${size}" vertical || return $?
+  pick_many "${prompt}" "${options}" vertical || return $?
 }
 
 # Shows a menu of resolutions of the given output and waits
@@ -267,7 +267,7 @@ pick_resolution () {
     return 2
   fi
 
-  pick_one 'Select a resolution:' "${options}" vertical || return $?
+  pick_one 'Select resolution:' "${options}" vertical || return $?
 }
 
 # Shows a menu of resolution rates of the given output and
@@ -303,5 +303,543 @@ pick_rate () {
     return 2
   fi
 
-  pick_one 'Select a refresh rate:' "${options}" vertical || return $?
+  pick_one 'Select refresh rate:' "${options}" vertical || return $?
 }
+
+# Shows a menu asking the user to select a reflection mode.
+# Outputs:
+#  A menu of reflection modes.
+pick_reflection_mode () {
+  local modes=''
+  modes+='{"key": "normal", "value": "Normal"},'
+  modes+='{"key": "x", "value": "X Axis"},'
+  modes+='{"key": "y", "value": "Y Axis"},'
+  modes+='{"key": "xy", "value": "XY Axis"}'
+  modes="[${modes}]"
+
+  pick_one 'Select reflection mode:' "${modes}" horizontal || return $?
+}
+
+# Shows a menu asking the user to select a rotation mode.
+# Outputs:
+#  A menu of rotation modes.
+pick_rotation_mode () {
+  local modes=''
+  modes+='{"key": "normal", "value": "Normal"},'
+  modes+='{"key": "right", "value": "Right"},'
+  modes+='{"key": "left", "value": "Left"},'
+  modes+='{"key": "inverted", "value": "Inverted"}'
+  modes="[${modes}]"
+
+  pick_one 'Select rotation mode:' "${modes}" horizontal || return $?
+}
+
+# Returns the common resolution if any among the
+# outputs with the given names.
+# Arguments:
+#  names: a list of comma separated output names
+# Outputs:
+#  A json array of resolutions.
+find_common_resolutions () {
+  local names=("${@}")
+
+  local outputs=''
+  outputs="$(find_outputs all)" || return 1
+
+  local len=0
+  len="$(count "${outputs}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo '[]'
+    return 0
+  fi
+
+  # Turn names array into a disjuctive regular expression
+  names="$(echo "${names[@]}" | tr ' ' '|')"
+
+  local query=''
+  query+="select(.device_name | match(\"(${names})\"))"
+  query+=' |.associated_modes[]'
+  query+=' |"\(.resolution_width)x\(.resolution_height)\(if .is_high_resolution then "i" else "" end)"'
+  query="[.[]|${query}]|[group_by(.)|map(select(length>1))|.[]|.[0]]"
+
+  echo "${outputs}" | jq -cer "${query}" || return 1
+}
+
+# Show a menu of asking the user to select one of the
+# available layout modes, where the answer is kept in
+# the global var REPLY.
+# Arguments
+#  size: the number of active outputs
+# Outputs:
+#  A menu of layout modes.
+pick_layout_mode () {
+  local size="${1}"
+
+  local modes=''
+
+  if [[ ${size} -eq 2 ]]; then
+    modes+='{"key": "row-2", "value": "Row"},'
+    modes+='{"key": "col-2", "value": "Column"}'
+  elif [[ ${size} -eq 3 ]]; then
+    modes+='{"key": "row-3", "value": "Row"},'
+    modes+='{"key": "col-3", "value": "Column"},'
+    modes+='{"key": "gamma-3", "value": "Gamma"},'
+    modes+='{"key": "gamma-rev-3", "value": "Gamma Reverse"},'
+    modes+='{"key": "lambda-3", "value": "Lambda"},'
+    modes+='{"key": "lambda-rev-3", "value": "Lambda Reverse"}'
+  elif [[ ${size} -eq 4 ]]; then
+    modes+='{"key": "grid-4", "value": "Grid"},'
+    modes+='{"key": "taph-4", "value": "Taph"},'
+    modes+='{"key": "taph-rev-4", "value": "Taph Reverse"},'
+    modes+='{"key": "taph-right-4", "value": "Taph Right"},'
+    modes+='{"key": "taph-left-4", "value": "Taph Left"}'
+  else
+    echo "No layout mode found for ${size} outputs"
+    return 2
+  fi
+
+  pick_one 'Select layout mode:' "[${modes}]" vertical || return $?
+}
+
+# Validates the given layout mode for the given active
+# outputs.
+# Arguments:
+#  mode: row-2, col-2, row-3, col-3, gamma-3, gamma-rev-3,
+#        lambda-3, lambda-rev-3, grid-4, taph-4, taph-rev-4,
+#        taph-right-4, taph-left-4
+#  size: the number of active outputs
+# Returns:
+#  0 if layout mode corresponds to active outputs otherwise 1.
+validate_layout_mode () {
+  local mode="${1}"
+  local size="${2}"
+
+  local modes=''
+  
+  if [[ ${size} -eq 2 ]]; then
+    modes='row-2|col-2'
+  elif [[ ${size} -eq 3 ]]; then
+    modes='row-3|col-3|gamma-3|gamma-rev-3|lambda-3|lambda-rev-3'
+  elif [[ ${size} -eq 4 ]]; then
+    modes='grid-4|taph-4|taph-rev-4|taph-right-4|taph-left-4'
+  else
+    echo "No layout mode found for ${size} outputs"
+    return 2
+  fi
+  
+  if [[ ! "${mode}" =~ ^(${modes})$ ]]; then
+    return 1
+  fi
+
+  return 0
+}
+
+# Shows the layout topology map that corresponds to the
+# given layout mode.
+# Arguments:
+#  mode:    row-2, col-2, row-3, col-3, gamma-3, gamma-rev-3,
+#           lambda-3, lambda-rev-3, grid-4, taph-4, taph-rev-4,
+#           taph-right-4, taph-left-4
+# Outputs:
+#  The topology of the layout mode.
+show_layout_map () {
+  local mode="${1}"
+  
+  local c=$'\e[30m\e[47m'
+  local r=$'\e[0m'
+
+  echo
+  case "${mode}" in
+    row-2)
+      echo -e "${c}       ${r}  ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}  ${c}  |2|  ${r}"
+      echo -e "${c}       ${r}  ${c}       ${r}"
+      ;;
+    col-2)
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |1|  ${r}"
+      echo -e "${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |2|  ${r}"
+      echo -e "${c}       ${r}"
+      ;;
+    row-3)
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}   ${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      ;;
+    col-3)
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |1|  ${r}"
+      echo -e "${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |2|  ${r}"
+      echo -e "${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |3|  ${r}"
+      echo -e "${c}       ${r}"
+      ;;
+    gamma-3)
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}   ${c}  |2|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |3|  ${r}"
+      echo -e "${c}       ${r}"
+      ;;
+    gamma-rev-3)
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}   ${c}  |2|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |3|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      ;;
+    lambda-3)
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |1|  ${r}"
+      echo -e "${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      ;;
+    lambda-rev-3)
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |1|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      ;;
+    grid-4)
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}   ${c}  |2|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |3|  ${r}   ${c}  |4|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      ;;
+    taph-4)
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |1|  ${r}   ${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |4|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      ;;
+    taph-rev-4)
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |1|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |2|  ${r}   ${c}  |3|  ${r}   ${c}  |4|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}   ${c}       ${r}"
+      ;;
+    taph-right-4)
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |1|  ${r}"
+      echo -e "${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}"
+      echo -e "${c}  |4|  ${r}"
+      echo -e "${c}       ${r}"
+      ;;
+    taph-left-4)
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |1|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo -e "${c}  |2|  ${r}   ${c}  |3|  ${r}"
+      echo -e "${c}       ${r}   ${c}       ${r}"
+      echo
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      echo -e "${r}       ${r}   ${c}  |4|  ${r}"
+      echo -e "${r}       ${r}   ${c}       ${r}"
+      ;;
+    *)
+      echo 'Invalid or unknown layout mode'
+      return 2;;
+  esac
+  echo
+}
+
+# Returns the corresponding xrandr command as a jq
+# template query for the given layout mode.
+# Arguments:
+#  mode:    row-2, col-2, row-3, col-3, gamma-3, gamma-rev-3,
+#           lambda-3, lambda-rev-3, grid-4, taph-4, taph-rev-4,
+#           taph-right-4, taph-left-4
+# Outputs:
+#  An xrandr jq template query.
+layout_to_xrandr_template () {
+  local mode="${1}"
+
+  local query=''
+
+  case "${mode}" in
+    row-2)
+      query='--output \(.[1]) --right-of \(.[0])'
+      ;;
+    col-2)
+      query='--output \(.[1]) --below \(.[0])'
+      ;;
+    row-3)
+      query='--output \(.[1]) --right-of \(.[0]) '
+      query+='--output \(.[2]) --right-of \(.[1])'
+      ;;
+    col-3)
+      query='--output \(.[1]) --below \(.[0]) '
+      query+='--output \(.[2]) --below \(.[1])'
+      ;;
+    gamma-3)
+      query='--output \(.[1]) --right-of \(.[0]) '
+      query+='--output \(.[2]) --below \(.[0])'
+      ;;
+    gamma-rev-3)
+      query='--output \(.[1]) --right-of \(.[0]) '
+      query+='--output \(.[2]) --below \(.[1])'
+      ;;
+    lambda-3)
+      query='--output \(.[1]) --below \(.[0]) '
+      query+='--output \(.[2]) --right-of \(.[1])'
+      ;;
+    lambda-rev-3)
+      query='--output \(.[2]) --right-of \(.[1]) '
+      query+='--output \(.[0]) --above \(.[2])'
+      ;;
+    grid-4)
+      query='--output \(.[1]) --right-of \(.[0]) '
+      query+='--output \(.[2]) --below \(.[0]) '
+      query+='--output \(.[3]) --right-of \(.[2])'
+      ;;
+    taph-4)
+      query='--output \(.[1]) --right-of \(.[0]) '
+      query+='--output \(.[2]) --right-of \(.[1]) '
+      query+='--output \(.[3]) --below \(.[1])'
+      ;;
+    taph-rev-4)
+      query='--output \(.[2]) --below \(.[0]) '
+      query+='--output \(.[1]) --left-of \(.[2]) '
+      query+='--output \(.[3]) --right-of \(.[2])'
+      ;;
+    taph-right-4)
+      query='--output \(.[1]) --below \(.[0]) '
+      query+='--output \(.[2]) --right-of \(.[1]) '
+      query+='--output \(.[3]) --below \(.[1])'
+      ;;
+    taph-left-4)
+      query='--output \(.[0]) --above \(.[2]) '
+      query+='--output \(.[1]) --left-of \(.[2]) '
+      query+='--output \(.[3]) --below \(.[2])'
+      ;;
+    *)
+      echo 'Invalid or unknown layout mode'
+      return 2;;
+  esac
+
+  echo "${query}"
+}
+
+# Saves the layout with the given signature and map
+# into the settings file.
+#  map: the map of outputs
+#  sig: the unique signature of the mapping
+save_layout_to_settings () {
+  local map="${1}"
+  local sig="${2}"
+
+  local layout="{\"sig\": \"${sig}\", \"map\": ${map}}"
+
+  local settings='{}'
+
+  if [[ -f "${SETTINGS_FILE}" ]]; then
+    local layouts=''
+    layouts="$(jq 'if .layouts then .layouts else empty end' "${SETTINGS_FILE}")"
+
+    if [[ -n "${layouts}" ]]; then
+      local query=''
+      query=".layouts[]|select(.sig == \"${sig}\")"
+
+      local exists=''
+      exists="$(jq "${query}" "${SETTINGS_FILE}")"
+
+      if [[ -n "${exists}" ]]; then
+        query="(${query}|.map)|= ${map}"
+      else
+        query=".layouts += [${layout}]"
+      fi
+
+      settings="$(jq -e "${query}" "${SETTINGS_FILE}")" || return 1
+    else
+      settings="$(jq -e ".layouts = [${layout}] " "${SETTINGS_FILE}")" || return 1
+    fi
+  else
+    settings="$(echo "{\"layouts\": [${layout}]}" | jq -e '.')" || return 1
+  fi
+
+  mkdir -p "${CONFIG_HOME}"
+  echo "${settings}" > "${SETTINGS_FILE}"
+}
+
+# Show a menu asking the user to select a saved layout.
+# Outputs:
+#  A menu of layouts.
+pick_layout () {
+  local devices=''
+  devices+='\(if .value.model_name then "\(.key):\(.value.model_name)" else empty end)'
+  devices="[.value.map|to_entries[]|\"${devices}\"]|join(\", \")"
+
+  local query=''
+  query+="{key: .key, value: \"\(.key):[\(${devices})]\"}"
+  query="if .layouts|length > 0 then [.layouts|to_entries[]|${query}] else [] end"
+
+  local layouts=''
+  layouts="$(jq -cer "${query}" "${SETTINGS_FILE}")" || return 1
+  
+  local len=0
+  len="$(count "${layouts}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No layouts have found'
+    return 2
+  fi
+
+  pick_one 'Select layout:' "${layouts}" vertical || return $?
+}
+
+# Show a menu asking the user to select a color profile
+# from those saved under the local user directory.
+# Outputs:
+#  A menu of profile files.
+pick_color_profile () {
+  # List all color calibration files under $COLORS_HOME
+  local query='{key: .filename, value: .filename}'
+  query="[.[]|select(.filename|test(\".ic(c|m)$\"))|${query}]"
+
+  local profiles=''
+  profiles="$(ls "${COLORS_HOME}" 2> /dev/null | jc --ls | jq -cr "${query}")"
+  
+  local len=0
+  len="$(count "${profiles}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No color profiles have found'
+    return 2
+  fi
+
+  pick_one 'Select color profile:' "${profiles}" vertical || return $?
+}
+
+# Show a menu asking the user to select a stored color
+# setting from the settings file.
+# Outputs:
+#  A menu of color settings.
+pick_color_setting () {
+  local query=''
+  query+='{key: .key, value: "\(.key):\(.value.model_name) [\(.value.profile)]"}'
+  query="if .colors|length > 0 then [.colors|to_entries[]|${query}] else [] end"
+
+  local colors=''
+  colors="$(jq -cer "${query}" "${SETTINGS_FILE}")" || return 1
+  
+  local len=0
+  len="$(count "${colors}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo 'No color settings have found'
+    return 2
+  fi
+
+  pick_one 'Select a color setting:' "${colors}" vertical || return $?
+}
+
+# Saves the color profile for the given output into settings.
+# Arguments:
+#  output:  a json object of output
+#  profile: a color profile file
+save_color_to_settings () {
+  local output="${1}"
+  local profile="${2}"
+
+  local query=''
+  query+='model_name: .model_name,'
+  query+='product_id: .product_id,'
+  query+='serial_number: .serial_number,'
+  query+="profile: \"${profile}\""
+  query="{${query}}"
+
+  local color=''
+  color="$(echo "${output}" | jq -cr "${query}")"
+
+  local settings='{}'
+
+  if [[ -f "${SETTINGS_FILE}" ]]; then
+    local colors=''
+    colors="$(jq 'if .colors then .colors else empty end' "${SETTINGS_FILE}")"
+
+    if [[ -n "${colors}" ]]; then
+      local query=''
+      query+='.model_name == $c.model_name and '
+      query+='.product_id == $c.product_id and '
+      query+='.serial_number == $c.serial_number'
+      query=".colors[]|select(${query})"
+
+      local exists=''
+      exists="$(jq --argjson c "${color}" "${query}" "${SETTINGS_FILE}")"
+
+      if [[ -n "${exists}" ]]; then
+        query="(${query}|.profile)|=\"${profile}\""
+      else
+        query=".colors += [${color}]"
+      fi
+
+      settings="$(jq -e --argjson c "${color}" "${query}" "${SETTINGS_FILE}")" || return 1
+    else
+      settings="$(jq -e ".colors = [${color}]" "${SETTINGS_FILE}")" || return 1
+    fi
+  else
+    settings="$(echo "{\"colors\": [${color}]}" | jq -e '.')" || return 1
+  fi
+
+  mkdir -p "${CONFIG_HOME}"
+  echo "${settings}" > "${SETTINGS_FILE}"
+}
+
+# Deletes the matching color setting for the given output.
+# Arguments:
+#  output: a json object of output
+remove_color_from_settings () {
+  local output="${1}"
+
+  if [[ ! -f "${SETTINGS_FILE}" ]]; then
+    return 0
+  fi
+
+  local query=''
+  query+='.model_name == $o.model_name and '
+  query+='.product_id == $o.product_id and '
+  query+='.serial_number == $o.serial_number'
+  query="if .colors then .colors[]|select(${query}) else empty end"
+
+  local settings=''
+  settings="$(jq -e --argjson o "${output}" "del(${query})" "${SETTINGS_FILE}")" || return 1
+
+  echo "${settings}" > "${SETTINGS_FILE}"
+}
+
