Show how many resources have failed to init

diff --git a/tools/cloud/commands b/tools/cloud/commands
--- a/tools/cloud/commands
+++ b/tools/cloud/commands
@@ -305,7 +305,7 @@ mount_all () {
   # Iterate over remote names and mount remotes one by one
   remotes="$(echo "${remotes}" | jq -cr '.[]|.name')" || return 1
 
-  local failed='false'
+  local failed=0
   local remote=''
 
   while read -r remote; do
@@ -313,15 +313,15 @@ mount_all () {
 
     if has_failed; then
       echo "Failed to mount remote ${remote}"
-      failed='true'
+      failed="$(calc "${failed} + 1")" || return 1
       continue
     fi
   
     echo "Remote ${remote} has been mounted"
   done <<< "${remotes}"
 
-  if is_true "${failed}"; then
-    echo 'Some remotes failed to be mounted'
+  if is_true "${failed} > 0"; then
+    echo "${failed} remotes failed to be mounted"
     return 2
   fi
 
diff --git a/tools/displays/commands b/tools/displays/commands
--- a/tools/displays/commands
+++ b/tools/displays/commands
@@ -1284,19 +1284,19 @@ restore_colors () {
   xcalib_cmds="$(echo "${outputs}" | jq -cr --argjson c "${colors}" "${query}")" || return 1
 
   # Iterate over xcalib commands and execute one by one
-  local failed='false'
+  local failed=0
   local xcalib_cmd=''
 
   while read -r xcalib_cmd; do
     local result="$(${xcalib_cmd} 2>&1)"
 
     if has_failed || is_not_empty "${result}"; then
-      failed='true'
+      failed="$(calc "${failed} + 1")" || return 1
     fi
   done <<< "${xcalib_cmds}"
 
-  if is_true "${failed}"; then
-    echo 'Failed to restore color settings'
+  if is_true "${failed} > 0"; then
+    echo "${failed} color settings failed to be restored"
     return 2
   fi
 
