Refine scripts of the cloud tool
This commit fixes:
* text in comments and docs
* text in output messages
* optional and required args on script mode
* reject delete for mounted remote resources
* confirmation when droping remotes
* logging for any mounted remote

diff --git a/tools/cloud/commands b/tools/cloud/commands
--- a/tools/cloud/commands
+++ b/tools/cloud/commands
@@ -17,18 +17,13 @@ list_remotes () {
   query="[.[]|select(.service|test(\"${service}\"; \"i\"))]"
 
   local remotes=''
-  remotes="$(find_remotes | jq -cer "${query}")"
-
-  if [[ $? -ne 0 ]]; then
-    echo 'Unable to read remotes'
-    return 2
-  fi
+  remotes="$(find_remotes | jq -cer "${query}")" || return $?
 
   local len=0
   len="$(count "${remotes}")" || return 1
     
   if [[ ${len} -eq 0 ]]; then
-    echo -e "No ${service:-\b} remotes have been found"
+    echo -e "No ${service:-\b} remotes found"
     return 0
   fi
 
@@ -44,31 +39,57 @@ list_remotes () {
 
 # Creates a new google drive remote with the given name.
 # Arguments:
-#  name: the name of the remote
+#  name:   the name of the remote
+#  client: the google client id
+#  secret: the client secret
+#  folder: the root folder id
 sync_drive () {
   local name="${1}"
+  local client="${2}"
+  local secret="${3}"
+  local folder="${4}"
 
   if [[ -z "${name}" ]]; then
-    echo 'Missing the remote name'
-    return 2
-  elif exists "${name}"; then
+    on_script_mode &&
+      echo 'Missing the remote name' && return 2
+
+    ask 'Enter a remote name:' || return $?
+    require 'Remote name is required' || return 2
+    name="${REPLY}"
+  fi
+  
+  if exists_remote "${name}"; then
     echo "Remote ${name} already exists"
     return 2
   fi
+  
+  if [[ -z "${client}" ]]; then
+    on_script_mode &&
+      echo 'Missing the client id' && return 2
 
-  ask 'Enter the client ID:' '.+' || return $?
-  local client_id="${REPLY}"
+    ask 'Enter the client id:' || return $?
+    require 'Client id is required' || return 2
+    client="${REPLY}"
+  fi
+  
+  if [[ -z "${secret}" ]]; then
+    on_script_mode &&
+      echo 'Missing the client secret' && return 2
 
-  ask 'Enter the client secret:' '.+' || return $?
-  local client_secret="${REPLY}"
-
-  ask 'Enter the root folder ID (blank to skip):' || return $?
-  local root_folder="${REPLY}"
+    ask 'Enter the client secret:' || return $?
+    require 'Client secret is required' || return 2
+    secret="${REPLY}"
+  fi
+  
+  if [[ -z "${folder}" ]] && ! on_script_mode; then
+    ask 'Enter the root folder id [none]:' || return $?
+    folder="${REPLY}"
+  fi
 
   echo 'Go to browser and accept access permssions...'
 
-  rclone config create "${name}" drive scope=drive client_id="${client_id}" \
-    client_secret="${client_secret}" root_folder_id="${root_folder}" &> /dev/null
+  rclone config create "${name}" drive scope=drive client_id="${client}" \
+    client_secret="${secret}" root_folder_id="${folder}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
     echo 'Failed to sync drive remote'
@@ -76,33 +97,55 @@ sync_drive () {
     return 2
   fi
 
-  echo "Drive remote ${name} has been synced"
+  echo "Drive remote ${name} synced"
 }
 
 # Creates a new dropbox remote with the given name.
 # Arguments:
-#  name: the name of the remote
+#  name:   the name of the remote
+#  app:    the dropbox application key
+#  secret: the application secret
 sync_dropbox () {
   local name="${1}"
+  local app="${2}"
+  local secret="${3}"
 
   if [[ -z "${name}" ]]; then
-    echo 'Missing the remote name'
-    return 2
-  elif exists "${name}"; then
+    on_script_mode &&
+      echo 'Missing the remote name' && return 2
+
+    ask 'Enter the remote name:' || return $?
+    require 'Remote name is required' || return 2
+    name="${REPLY}"
+  fi
+  
+  if exists_remote "${name}"; then
     echo "Remote ${name} already exists"
     return 2
   fi
 
-  ask 'Enter the app key:' '.+' || return $?
-  local app_key="${REPLY}"
+  if [[ -z "${app}" ]]; then
+    on_script_mode &&
+      echo 'Missing the application key' && return 2
 
-  ask 'Enter the app secret:' '.+' || return $?
-  local app_secret="${REPLY}"
+    ask 'Enter the application key:' || return $?
+    require 'Application key is required' || return 2
+    app="${REPLY}"
+  fi
+
+  if [[ -z "${secret}" ]]; then
+    on_script_mode &&
+      echo 'Missing the application secret' && return 2
+
+    ask 'Enter the application secret:' || return $?
+    require 'Application secret is required' || return 2
+    secret="${REPLY}"
+  fi
 
   echo 'Go to browser and accept access permssions...'
 
   rclone config create "${name}" dropbox \
-    client_id="${app_key}" client_secret="${app_secret}" &> /dev/null
+    client_id="${app}" client_secret="${secret}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
     echo 'Failed to sync dropbox remote'
@@ -110,7 +153,7 @@ sync_dropbox () {
     return 2
   fi
 
-  echo "Dropbox remote ${name} has been synced"
+  echo "Dropbox remote ${name} synced"
 }
 
 # Deletes the remote with the given name.
@@ -120,17 +163,29 @@ delete_remote () {
   local name="${1}"
   
   if [[ -z "${name}" ]]; then
-    pick_remote || return $?
+    on_script_mode &&
+      echo 'Missing the remote name' && return 2
+
+    pick_remote unmounted || return $?
+    require 'Remote name is required' || return 2
     name="${REPLY}"
   fi
   
-  if ! exists "${name}"; then
-    echo "No remote ${name} has been found"
+  if ! exists_remote "${name}"; then
+    echo "Remote ${name} not found"
+    return 2
+  elif is_remote_mounted "${name}"; then
+    echo 'Cannot delete a mounted remote'
     return 2
   fi
 
-  if is_mounted "${name}"; then
-    unmount_remote "${name}"
+  if ! on_script_mode; then
+    echo "Remote ${name} will be deleted!"
+    confirm 'Do you realy want to proceed?' || return $?
+    require 'Confirmation is required' || return 2
+    
+    [[ "${REPLY}" != "yes" ]] &&
+      echo 'Deletion operation is canceled' && return 2
   fi
 
   rclone config delete "${name}"
@@ -150,14 +205,18 @@ mount_remote () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
+    on_script_mode &&
+      echo 'Missing the remote name' && return 2
+
     pick_remote unmounted || return $?
+    require 'Remote name is required' || return 2
     name="${REPLY}"
   fi
   
-  if ! exists "${name}"; then
-    echo "No remote ${name} has been found"
+  if ! exists_remote "${name}"; then
+    echo "Remote ${name} not found"
     return 2
-  elif is_mounted "${name}"; then
+  elif is_remote_mounted "${name}"; then
     echo "Remote ${name} is already mounted"
     return 2
   fi
@@ -166,15 +225,18 @@ mount_remote () {
 
   local mount_folder="${HOME}/mounts/cloud/${name}"
 
-  mkdir -p "${mount_folder}" &&
+  mkdir -p "${mount_folder}" '/tmp/rclone' &&
   rclone mount "${name}:" "${mount_folder}" \
     --umask=002 --gid=$(id -g) --uid=$(id -u) --timeout=1h \
     --poll-interval=15s --dir-cache-time=1000h --vfs-cache-mode=full \
-    --vfs-cache-max-size=150G --vfs-cache-max-age=12h --daemon
-  
+    --vfs-cache-max-size=150G --vfs-cache-max-age=12h \
+    --log-level=INFO --log-file="/tmp/rclone/${name}.log" --daemon
+
   if [[ $? -ne 0 ]]; then
-    echo 'Failed to mount remote'
+    # Remove the dangling root mount folder if it is empty
     find "${mount_folder}" -maxdepth 0 -empty -exec rm -rf {} \;
+
+    echo 'Failed to mount remote'
     return 2
   fi
 
@@ -188,14 +250,18 @@ unmount_remote () {
   local name="${1}"
 
   if [[ -z "${name}" ]]; then
+    on_script_mode &&
+      echo 'Missing the remote name' && return 2
+    
     pick_remote mounted || return $?
+    require 'Remote name is required' || return 2
     name="${REPLY}"
   fi
   
-  if ! exists "${name}"; then
-    echo "No remote ${name} has been found"
+  if ! exists_remote "${name}"; then
+    echo "Remote ${name} not found"
     return 2
-  elif ! is_mounted "${name}"; then
+  elif ! is_remote_mounted "${name}"; then
     echo "Remote ${name} is not mounted"
     return 2
   fi
@@ -215,22 +281,16 @@ unmount_remote () {
     return 2
   fi
 
+  # Remove root folder of the mount only if it is empty
   find "${mount_point}" -maxdepth 0 -empty -exec rm -rf {} \;
 
   echo "Remote ${name} has been unmounted"
 }
 
 # Mounts all the synced remotes.
-# Arguments:
-#  None
 mount_all () {
   local remotes=''
-  remotes="$(find_remotes)"
-
-  if [[ $? -ne 0 ]]; then
-    echo 'Unable to read remotes'
-    return 2
-  fi
+  remotes="$(find_remotes)" || return $?
 
   local len=0
   len="$(count "${remotes}")" || return 1
@@ -252,13 +312,14 @@ mount_all () {
     if [[ $? -ne 0 ]]; then
       echo "Failed to mount remote ${remote}"
       failed='true'
-    else
-      echo "Remote ${remote} has been mounted"
+      continue
     fi
+  
+    echo "Remote ${remote} has been mounted"
   done <<< "${remotes}"
 
   if [[ "${failed}" == "true" ]]; then
-    echo 'Failed to mount all remotes'
+    echo 'Some remotes failed to be mounted'
     return 2
   fi
 
