Make set option command script friendly

diff --git a/tools/printers/commands b/tools/printers/commands
--- a/tools/printers/commands
+++ b/tools/printers/commands
@@ -301,9 +301,13 @@ unshare_printer () {
 
 # Sets an option of the printer with the given name.
 # Arguments:
-#  name: the name of a print destination
+#  name:  the name of a print destination
+#  key:   quality, page, paper, toner or onerror
+#  value: the value of the option
 set_option () {
   local name="${1}"
+  local key="${2}"
+  local value="${3}"
 
   if [[ -z "${name}" ]]; then
     pick_printer || return $?
@@ -320,40 +324,65 @@ set_option () {
     return 2
   fi
 
-  pick_print_option || return $?
-  local option="${REPLY}"
+  if [[ -z "${key}" ]]; then
+    pick_print_option || return $?
+    key="${REPLY}"
 
-  if [[ -z "${option}" ]]; then
-    echo 'No print option selected'
+    if [[ -z "${key}" ]]; then
+      echo 'No print option selected'
+      return 2
+    fi
+  fi
+
+  if [[ ! "${key}" =~ ^(Quality|PageSize|MediaType|TonerSaveMode|printer-error-policy)$ ]]; then
+    echo 'Invalid print option'
     return 2
   fi
 
-  case "${option}" in
-    Quality) pick_print_quality;;
-    PageSize) pick_page_size;;
-    MediaType) pick_paper_type;;
-    TonerSaveMode) pick_toner_mode;;
-    printer-error-policy) pick_error_policy;;
+  if [[ -z "${value}" ]]; then
+    case "${key}" in
+      Quality) pick_print_quality;;
+      PageSize) pick_page_size;;
+      MediaType) pick_media_type;;
+      TonerSaveMode) pick_toner_mode;;
+      printer-error-policy) pick_error_policy;;
+      *)
+        echo 'Unknown or invalid print option'
+        return 2;;
+    esac || return $?
+
+    value="${REPLY}"
+
+    if [[ -z "${value}" ]]; then
+      echo 'No option value selected'
+      return 2
+    fi
+  fi
+   
+  case "${key}" in
+    Quality) [[ "${value}" =~ ^(600dpi|1200dpi)$ ]];;
+    PageSize) [[ "${value}" =~ ^(Letter|Legal|A4|A5|Executive|Folio|JB5|B5-ISO|COM10|Monarch|DL|C5|Oficio_S|PCard4x6)$ ]];;
+    MediaType) [[ "${value}" =~ ^(None|Plain|Thick|Thin|Bond|Color|Card|Labels|Preprinted|Cotton|Archive|Recycled|Envelope)$ ]];;
+    TonerSaveMode) [[ "${value}" =~ ^(Save|Standard)$ ]];;
+    printer-error-policy) [[ "${value}" =~ ^(abort-job|retry-current-job|retry-job|stop-printer)$ ]];;
     *)
       echo 'Unknown or invalid print option'
       return 2;;
-  esac || return $?
+  esac
 
-  local value="${REPLY}"
-
-  if [[ -z "${value}" ]]; then
-    echo "No option value selected"
+  if [[ $? -ne 0 ]]; then
+    echo 'Invalid option value'
     return 2
   fi
 
-  lpadmin -p "${name}" -o "${option}"="${value}"
+  lpadmin -p "${name}" -o "${key}"="${value}"
 
   if [[ $? -ne 0 ]]; then
     echo 'Failed to set printer option'
     return 2
   fi
 
-  echo "Option ${option} of printer ${name} set to ${value}"
+  echo "Option ${key} of printer ${name} set to ${value}"
 }
 
 # Sets the printer with the given name as default
@@ -381,7 +410,7 @@ set_default () {
   lpoptions -d "${name}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set printer ${name} as default destination"
+    echo 'Failed to set default print destination'
     return 2
   fi
 
diff --git a/tools/printers/helpers b/tools/printers/helpers
--- a/tools/printers/helpers
+++ b/tools/printers/helpers
@@ -325,11 +325,11 @@ pick_job () {
 #  A menu of print options.
 pick_print_option () {
   local options=''
-  options+='{"key": "Quality", "value": "print quality"},'
-  options+='{"key": "PageSize", "value": "page size"},'
-  options+='{"key": "MediaType", "value": "paper size"},'
-  options+='{"key": "TonerSaveMode", "value": "toner mode"},'
-  options+='{"key": "printer-error-policy", "value": "error policy"}'
+  options+='{"key": "Quality", "value": "Quality"},'
+  options+='{"key": "PageSize", "value": "Page Size"},'
+  options+='{"key": "MediaType", "value": "Paper Size"},'
+  options+='{"key": "TonerSaveMode", "value": "Toner Mode"},'
+  options+='{"key": "printer-error-policy", "value": "Error Policy"}'
   options="[${options}]"
 
   pick_one 'Select a print option:' "${options}" vertical || return $?
@@ -373,11 +373,11 @@ pick_page_size () {
   pick_one 'Select a page size:' "${values}" vertical || return $?
 }
 
-# Shows a menu asking the user to select a paper type option,
+# Shows a menu asking the user to select a media type option,
 # where the answer is kept in the global var REPLY.
 # Outputs:
-#  A menu of paper type options.
-pick_paper_type () {
+#  A menu of media type options.
+pick_media_type () {
   local values=''
   values+='{"key": "None", "value": "Printer Default [None]"},'
   values+='{"key": "Plain", "value": "Plain [Plain]"},'
@@ -394,7 +394,7 @@ pick_paper_type () {
   values+='{"key": "Envelope", "value": "Envelope [Envelope]"}'
   values="[${values}]"
 
-  pick_one 'Select a paper type:' "${values}" vertical || return $?
+  pick_one 'Select a media type:' "${values}" vertical || return $?
 }
 
 # Shows a menu asking the user to select a toner mode option,
