Add cmd to set the default audio in/ouputs

diff --git a/resources/stack/audio b/resources/stack/audio
--- a/resources/stack/audio
+++ b/resources/stack/audio
@@ -264,65 +264,77 @@ set_profile () {
 }
 
 set_output () {
-  local INDEX=$1
+  local SINK=$1
   local VOLUME=$2
 
-  if [ -z "$INDEX" ]; then
+  if [ -z "$SINK" ]; then
     echo "Missing the output name or id argument"
     return 1
   fi
 
+  if [ -n "$VOLUME" ]; then
+    if [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
+      echo "Invalid volume argument: '$VOLUME'"
+      return 1
+    elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
+      echo "Volume is out of the valid range: '$VOLUME'"
+      return 1
+    fi
+  fi
+
   if [ -z "$VOLUME" ]; then
-    echo "Missing the volume argument"
-    return 1
-  elif [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
-    echo "Invalid volume argument: '$VOLUME'"
-    return 1
-  elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
-    echo "Volume is out of the valid range: '$VOLUME'"
+    pactl set-default-sink "$SINK" && sleep 0.1 &&
+      echo "Default output set to $SINK" ||
+      echo "Unable to set the default output"
     return 1
   fi
 
   if [ $VOLUME -gt 0 ]; then
-    pactl set-sink-mute "$INDEX" 0 &&
-    pactl set-sink-volume "$INDEX" "$VOLUME%" && sleep 0.1 &&
-      echo "Volume set to $VOLUME for the output $INDEX" ||
-      echo "Unable to set the volume"
+    pactl set-sink-mute "$SINK" 0 &&
+    pactl set-sink-volume "$SINK" "$VOLUME%" && sleep 0.1 &&
+      echo "Output $SINK volume set to $VOLUME" ||
+      echo "Unable to set the output volume"
   else
-    pactl set-sink-mute "$INDEX" 1 && sleep 0.1 &&
-      echo "Output $INDEX set to mute" ||
-      echo "Unable to set output to mute"
+    pactl set-sink-mute "$SINK" 1 && sleep 0.1 &&
+      echo "Output $SINK set to mute" ||
+      echo "Unable to set the output to mute"
   fi
 }
 
 set_input () {
-  local INDEX=$1
+  local SOURCE=$1
   local VOLUME=$2
 
-  if [ -z "$INDEX" ]; then
+  if [ -z "$SOURCE" ]; then
     echo "Missing the input name or id argument"
     return 1
   fi
 
+  if [ -n "$VOLUME" ]; then
+    if [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
+      echo "Invalid volume argument: '$VOLUME'"
+      return 1
+    elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
+      echo "Volume is out of the valid range: '$VOLUME'"
+      return 1
+    fi
+  fi
+
   if [ -z "$VOLUME" ]; then
-    echo "Missing the volume argument"
-    return 1
-  elif [[ ! "$VOLUME" =~ ^[0-9]{1,3}$ ]]; then
-    echo "Invalid volume argument: '$VOLUME'"
-    return 1
-  elif ! (($VOLUME >= 0 && $VOLUME <= 150)); then
-    echo "Volume is out of the valid range: '$VOLUME'"
+    pactl set-default-source "$SOURCE" && sleep 0.1 &&
+      echo "Default input set to $SOURCE" ||
+      echo "Unable to set the default input"
     return 1
   fi
   
   if [ $VOLUME -gt 0 ]; then
-    pactl set-source-mute "$INDEX" 0 &&
-    pactl set-source-volume "$INDEX" "$VOLUME%" && sleep 0.1 &&
-      echo "Volume set to $VOLUME for the input $INDEX" ||
-      echo "Unable to set the volume"
+    pactl set-source-mute "$SOURCE" 0 &&
+    pactl set-source-volume "$SOURCE" "$VOLUME%" && sleep 0.1 &&
+      echo "Input $SOURCE volume set to $VOLUME" ||
+      echo "Unable to set the input volume"
   else
-    pactl set-source-mute "$INDEX" 1 && sleep 0.1 &&
-      echo "Input $INDEX set to mute" ||
+    pactl set-source-mute "$SOURCE" 1 && sleep 0.1 &&
+      echo "Input $SOURCE set to mute" ||
       echo "Unable to set input to mute"
   fi
 }
@@ -386,10 +398,12 @@ help () {
     "list playbacks [<filter>]" "List any active audio playbacks." \
     "" "" \
     "set profile <name|id> <profile>" "Set the audio profile of the given card." \
+    "set output <name|id>" "Set the default output." \
     "set output <name|id> <volume>" "Set the volume of the given output, 0 to mute." \
+    "set input <name|id>" "Set the default input." \
     "set input <name|id> <volume>" "Set the volume of the given input, 0 to mute." \
     "mute all|outputs|inputs" "Mute all, output or input audio streams." \
-    "unmute all|outputs|inputs" "Unmute all, outputs or inputs audio streams."
+    "unmute all|outputs|inputs" "Unmute all, output or input audio streams."
 
   echo -e "\nOBJECTS"
   printf "$FRM" \
