Add cmd to list controllers and devices

diff --git a/resources/stack/bluetooth b/resources/stack/bluetooth
--- a/resources/stack/bluetooth
+++ b/resources/stack/bluetooth
@@ -12,6 +12,25 @@ find_controllers () {
   bluetoothctl list | jc --bluetoothctl || return 1
 }
 
+# Returns all the available devices filtered by the
+# optionally given status.
+# Arguments:
+#  status: paired, connected or trusted
+# Outputs:
+#  A json array of device objects.
+find_devices () {
+  local status="${1}"
+
+  local devices=''
+  if [[ -n "${status}" ]]; then
+    devices="$(bluetoothctl devices "${status}")" || return 1
+  else
+    devices="$(bluetoothctl devices)" || return 1
+  fi
+
+  echo "${devices}" | jc --bluetoothctl || return 1
+}
+
 # Shows a prompt status and asks user to enter the
 # next command, which is kept in the global var REPLY.
 # Globals:
@@ -58,6 +77,75 @@ show_logs () {
   systemctl status --no-pager bluetooth.service | tail -n +13 || return 1
 }
 
+# Shows the list of available controllers.
+# Arguments:
+#  None
+# Outputs:
+#  A list of bluetooth controllers.
+list_controllers () {
+  local controllers=''
+  controllers="$(find_controllers)"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Unable to read controllers"
+    return 2
+  fi
+
+  local len=0
+  len="$(count "${controllers}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo "No controllers have found"
+    return 0
+  fi
+
+  local query=''
+  query+='Name:     \(.name)\n'
+  query+='Address:  \(.address)'
+  query+='\(if .is_default then "\nDefault:  \(.is_default)" else "" end)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  echo "${controllers}" | jq -cer "${query}" || return 1
+}
+
+# Shows the list of available devices filtered by
+# the optionally given status.
+# Arguments:
+#  status: paired, connected or trusted
+# Outputs:
+#  A list of bluetooth devices.
+list_devices () {
+  local status="${1}"
+
+  if [[ -n "${status}" ]] && [[ ! "${status}" =~ ^(paired|connected|trusted|bonded)$ ]]; then
+    echo "Invalid status value"
+    return 2
+  fi
+
+  local devices=''
+  devices="$(find_devices "${status^}")"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Unable to read devices"
+    return 2
+  fi
+
+  local len=0
+  len="$(count "${devices}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo "No available devices have found"
+    return 0
+  fi
+
+  local query=''
+  query+='Name:     \(.name)\n'
+  query+='Address:  \(.address)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  echo "${devices}" | jq -cer "${query}" || return 1
+}
+
 # Restarts the bluetooth service.
 # Arguments:
 #  None
@@ -93,6 +181,10 @@ show_help () {
     "show status" "Show a report of the bluetooth service and devices." \
     "show logs" "Show the last logs of the bluetooth service." \
     "" "" \
+    "list controllers" "List the available controllers." \
+    "list devices [<status>]" "List the devices where status could be" \
+    "" "any of paired, connected, trusted or bonded." \
+    "" "" \
     "restart" "Restart the bluetooth service."
 }
 
@@ -124,6 +216,12 @@ loop () {
         case "${cmd[1]}" in
           "status") show_status;;
           "logs") show_logs;;
+          *) echo "Invalid or unknown command";;
+        esac;;
+      "list")
+        case "${cmd[1]}" in
+          "controllers") list_controllers;;
+          "devices") list_devices "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       "restart") restart_bluetooth;;
