Validate network objects before select them

diff --git a/resources/stack/connect b/resources/stack/connect
--- a/resources/stack/connect
+++ b/resources/stack/connect
@@ -10,6 +10,11 @@ sel () {
   local OBJECT=$1
   local NAME=$2
 
+  if ! nmcli --colors no device | grep -q "$NAME"; then
+    echo "Invalid network object $NAME"
+    return 1
+  fi
+
   if [ "$OBJECT" = "device" ]; then
     SEL_DEVICE=$NAME
     SEL_CONNECTION=""
