Add cmd to list the pointing devices

diff --git a/resources/stack/desktop b/resources/stack/desktop
--- a/resources/stack/desktop
+++ b/resources/stack/desktop
@@ -78,6 +78,42 @@ pick_wallpaper () {
   pick_one "Select a wallpaper:" "${wallpapers}" "vertical" || return $?
 }
 
+# Returns the list of pointing devices currently
+# connected to the system.
+# Arguments:
+#  None
+# Outputs:
+#  A json array of pointing device objects.
+find_pointers () {
+  local pointers=''
+  pointers="$(xinput --list | awk '{
+    if ($0 ~ "Virtual core pointer") {
+      next
+    } else if ($0 ~ "Virtual core keyboard") {
+      exit
+    }
+
+    match($0, ".*↳ (.*)id=([0-9]+).*", a)
+    gsub(/^[ \t]+/,"",a[1])
+    gsub(/[ \t]+$/,"",a[1])
+    gsub(/^[ \t]+/,"",a[2])
+    gsub(/[ \t]+$/,"",a[2])
+
+    schema="\"id\": \"%s\","
+    schema=schema"\"name\": \"%s\""
+    schema="{"schema"},"
+
+    printf schema, a[2], a[1]
+  }')" || return 1
+
+  # Remove the extra comma after the last element
+  if [[ -n "${pointers}" ]]; then
+    pointers="${pointers::-1}"
+  fi
+
+  echo "[${pointers}]"
+}
+
 # Returns the list of stylus-pen devices currently
 # connected to the system.
 # Arguments:
@@ -556,6 +592,37 @@ load_wallpaper () {
   echo "Wallpaper has been loaded"
 }
 
+# Shows the list of pointing devices currently
+# connected to the system.
+# Arguments:
+#  None
+# Outputs:
+#  A list of pointing devices.
+list_pointers () {
+  local pointers=''
+  pointers="$(find_pointers)"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Unable to find pointers"
+    return 2
+  fi
+
+  local len=0
+  len="$(count "${pointers}")" || return 1
+
+  if [[ ${len} -eq 0 ]]; then
+    echo "No pointers have found"
+    return 0
+  fi
+
+  local query=''
+  query+='ID:    \(.id)\n'
+  query+='Name:  \(.name)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  echo "${pointers}" | jq -cer "${query}" || return 1
+}
+
 # Sets the acceleration speed of every pointing device
 # to the given speed factor, where 0 means slow and 1
 # means fast.
@@ -912,6 +979,7 @@ show_help () {
     "show tablet [<name>]" "Show a tablet device." \
     "" "" \
     "list wallpapers" "List the available wallapers." \
+    "list pointers" "List the available pointing devices." \
     "list tablets" "List the connected tablets." \
     "" "" \
     "set wallpaper [<name> [<mode>]]" "Set the desktop wallpaper in center" \
@@ -977,6 +1045,7 @@ loop () {
       "list")
         case "${cmd[1]}" in
           "wallpapers") list_wallpapers;;
+          "pointers") list_pointers;;
           "tablets") list_tablets;;
           *) echo "Invalid or unknown command";;
         esac;;
