Distinguish tablets by vendor

diff --git a/resources/stack/desktop b/resources/stack/desktop
--- a/resources/stack/desktop
+++ b/resources/stack/desktop
@@ -97,7 +97,8 @@ find_tablets () {
 
     schema="\"id\": \"%s\","
     schema=schema"\"name\": \"%s\","
-    schema=schema"\"type\": \"%s\""
+    schema=schema"\"type\": \"%s\","
+    schema=schema"\"vendor\": \"wacom\""
     schema="{"schema"},"
 
     printf schema, a[2], a[1], a[3]
@@ -351,7 +352,12 @@ load_wallpaper () {
 #  A list of stylus-pen devices.
 list_tablets () {
   local tablets=''
-  tablets="$(find_tablets)" || return 1
+  tablets="$(find_tablets)"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Unable to find tablets"
+    return 2
+  fi
 
   local len=0
   len="$(count "${tablets}")" || return 1
@@ -362,9 +368,10 @@ list_tablets () {
   fi
 
   local query=''
-  query+='ID:    \(.id)\n'
-  query+='Name:  \(.name)\n'
-  query+='Type:  \(.type)'
+  query+='ID:      \(.id)\n'
+  query+='Name:    \(.name)\n'
+  query+='Type:    \(.type)\n'
+  query+='Vendor:  \(.vendor)'
   query="[.[]|\"${query}\"]|join(\"\n\n\")"
 
   echo "${tablets}" | jq -cer "${query}" || return 1
@@ -396,11 +403,11 @@ show_help () {
     "" "" \
     "show status" "Show the status of the desktop environment." \
     "" "" \
-    "list wallpapers" "List all the wallapers." \
-    "set wallpaper [<name> [<mode>]]" "Set the desktop wallpaper in center" \
-    "" "fill, scale, max or tile mode." \
+    "list wallpapers" "List the available wallapers." \
+    "list tablets" "List the connected tablets." \
     "" "" \
-    "list tablets" "List all the connected tablets."
+    "set wallpaper [<name> [<mode>]]" "Set the desktop wallpaper in center" \
+    "" "fill, scale, max or tile mode."
 }
 
 loop () {
