List all images file systems currently mounted

diff --git a/resources/stack/disks b/resources/stack/disks
--- a/resources/stack/disks
+++ b/resources/stack/disks
@@ -926,7 +926,7 @@ list_mounts () {
   local folders=''
   folders="$(ls "/run/user/${UID}/gvfs" | awk -v id="${UID}" '{
     match($0, /server=(.*),share=(.*),/, a);
-    print "\nDevice:  "a[1]"/"a[2]"\nPoints:  [/run/user/"id"/gvfs/"$0"]"
+    print "\nDevice:  "a[1]"/"a[2]"\nPoints:  [\"/run/user/"id"/gvfs/"$0"\"]"
   }')"
 
   if [[ $? -ne 0 ]]; then
@@ -934,10 +934,21 @@ list_mounts () {
     return 2
   fi
 
+  local images=''
+  images="$(cat /proc/mounts | awk '/^fuseiso/{
+    n=split($2, a, "/")
+    print "\nDevice:  " a[n] "\nPoints:  [\"" $2 "\"]"
+  }')"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Unable to read image mounts"
+    return 2
+  fi
+
   local len=0
   len="$(count "${devices}")" || return 1
 
-  if [[ ${len} -eq 0 ]] && [[ -z "${folders}" ]]; then
+  if [[ ${len} -eq 0 ]] && [[ -z "${folders}" ]] && [[ -z "${images}" ]]; then
     echo "No mounts have found"
     return 0
   fi
@@ -954,6 +965,10 @@ list_mounts () {
 
   if [[ -n "${folders}" ]]; then
     echo "${folders}"
+  fi
+
+  if [[ -n "${images}" ]]; then
+    echo "${images}"
   fi
 }
 
