Use URI as remote disk name to reveal purpose of use

diff --git a/resources/stack/disks b/resources/stack/disks
--- a/resources/stack/disks
+++ b/resources/stack/disks
@@ -69,16 +69,16 @@ unmount_local_disk () {
 }
 
 mount_remote_disk () {
-  local DEVICE=$1
+  local URI=$1
 
-  if gio mount -l | grep -q "$DEVICE"; then
-    echo "Device $DEVICE is already mounted"
+  if gio mount -l | grep -q "$URI"; then
+    echo "Device $URI is already mounted"
     return 1
   fi
 
-  gio mount "$DEVICE" &&
-    echo "Device $DEVICE mounted successfully" ||
-    echo "Failed to mount device from $DEVICE"
+  gio mount "$URI" &&
+    echo "Device $URI mounted successfully" ||
+    echo "Failed to mount device from $URI"
 
   if [ -d "/run/user/${UID}/gvfs" ] && [ ! -L "$HOME/mount/remote" ]; then
     mkdir -p "$HOME/mount/remote"
@@ -87,17 +87,17 @@ mount_remote_disk () {
 }
 
 unmount_remote_disk () {
-  local DEVICE=$1
+  local URI=$1
 
-  if ! gio mount -l | grep -q "$DEVICE"; then
-    echo "No remote disk $DEVICE is mounted"
+  if ! gio mount -l | grep -q "$URI"; then
+    echo "No remote disk $URI is mounted"
     return 1
   fi
 
   sync &&
-  gio mount -u "$DEVICE" &&
-    echo "Device $DEVICE unmounted successfully" ||
-    echo "Failed to umount device $DEVICE"
+  gio mount -u "$URI" &&
+    echo "Device $URI unmounted successfully" ||
+    echo "Failed to umount device $URI"
 }
 
 help () {
@@ -139,7 +139,7 @@ main () {
       "mount")
         case "${CMD[1]}" in
           "local") mount_local_disk "${CMD[2]}";;
-          "remote") mount_remote_disk "${CMD[2]}://${CMD[3]}/${CMD[4]}";;;;
+          "remote") mount_remote_disk "${CMD[2]}://${CMD[3]}/${CMD[4]}";;
           *) echo "Invalid disk type: '${CMD[1]}'";;
         esac;;
       "unmount")
