Make clear in disks which operation goes to which cmd object

diff --git a/resources/stack/disks b/resources/stack/disks
--- a/resources/stack/disks
+++ b/resources/stack/disks
@@ -9,7 +9,7 @@ source /opt/stack/utils
 #  type:   a comma-sep list of disk, part, rom or all
 #  status: mounted, unmounted or all
 # Outputs:
-#  A json array list of device objects.
+#  A json array list of block device objects.
 find_devices () {
   local type="${1}"
   local status="${2}"
@@ -41,11 +41,11 @@ find_devices () {
   lsblk -J -o "${fields}" | jq -cer "${query}" || return 1
 }
 
-# Returns the device with the given path.
+# Returns the block device with the given path.
 # Arguments:
-#  path: the device path
+#  path: the path of a block device
 # Outputs:
-#  A json object of a device.
+#  A json object of a block device.
 find_device () {
   local path="${1}"
 
@@ -57,18 +57,22 @@ find_device () {
 }
 
 # Checks if the block device with the given path
-# is a disk or not.
+# is of the given type or not.
 # Arguments:
 #  path: the path of a block device
+#  type: disk, part or rom
 # Returns:
-#  0 if it is a disk otherwise 1.
-is_disk () {
+#  0 if it is of type otherwise 1.
+is_type_of () {
   local path="${1}"
+  local type="${2}"
 
-  local type=''
-  type="$(find_device "${path}" | jq -cr '.type')" || return 1
+  local query="if .type == \"${type}\" then true else false end"
 
-  if [[ "${type}" == "disk" ]]; then
+  local result=''
+  result="$(find_device "${path}" | jq -cr "${query}")"
+
+  if [[ "${result}" == "true" ]]; then
     return 0
   else
     return 1
@@ -125,7 +129,8 @@ is_system_disk () {
   fi
 }
 
-# Unmounts the partition with the given path.
+# Unmounts the partition block device with
+# the given path.
 # Arguments:
 #  path: the path of a partition block device
 unmount_partition () {
@@ -139,7 +144,7 @@ unmount_partition () {
 # given path.
 # Arguments:
 #  path: the path of a disk block device
-unmount_disk_partitions () {
+unmount_partitions () {
   local path="${1}"
 
   # Collect any disk's partitions currently mounted
@@ -255,15 +260,15 @@ find_shared_folders () {
   echo "[${folders}]"
 }
 
-# Shows a menu asking the user to select one device, where the
-# answer is kept in the global var REPLY.
+# Shows a menu asking the user to select one block device,
+# where the answer is kept in the global var REPLY.
 # Globals:
 #  REPLY
 # Arguments:
 #  type:   a comma-sep list of disk, part, rom or all
 #  status: mounted, unmounted or all
 # Outputs:
-#  A menu of devices.
+#  A menu of block devices.
 pick_device () {
   local type="${1}"
   local status="${2}"
@@ -272,7 +277,7 @@ pick_device () {
   devices="$(find_devices "${type}" "${status}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to find devices"
+    echo "Unable to find block devices"
     return 2
   fi
 
@@ -280,7 +285,7 @@ pick_device () {
   len="$(count "${devices}")" || return 1
   
   if [[ ${len} -eq 0 ]]; then
-    echo "No devices have found"
+    echo "No block devices have found"
     return 2
   fi
 
@@ -295,7 +300,7 @@ pick_device () {
 
   devices="$(echo "${devices}" | jq -cer "${query}")" || return 1
 
-  pick_one "Select a device:" "${devices}" "vertical" || return $?
+  pick_one "Select a block device:" "${devices}" "vertical" || return $?
 }
 
 # Shows a menu asking the user to select one host, where the
@@ -422,19 +427,24 @@ show_status () {
 # Globals:
 #  REPLY
 # Arguments:
+#  type: disk, part or rom
 #  path: the path of a block device
 # Outputs:
-#  A long text of device data.
+#  A long text of block device data.
 show_device () {
-  local path="${1}"
+  local type="${1}"
+  local path="${2}"
 
   if [[ -z "${path}" ]]; then
-    pick_device "all" || return $?
+    pick_device "${type}" || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
   if [[ ! -b "${path}" ]]; then
-    echo "Invalid block device path"
+    echo "Invalid block device"
+    return 2
+  elif ! is_type_of "${path}" "${type}"; then
+    echo "Invalid ${type} block device"
     return 2
   fi
 
@@ -471,27 +481,30 @@ show_device () {
   find_device "${path}" | jq -cer "\"${query}\""
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to read device data"
+    echo "Failed to read block device data"
     return 2
   fi
 }
 
-# Scans the device with the given path for
-# possible SMART data.
+# Scans the disk block device with the given path
+# for possible SMART data.
 # Arguments:
-#  path: the path of a block device
+#  path: the path of a disk block device
 # Outputs:
 #  A long list of health and status data.
-scan_device () {
+scan_disk () {
   local path="${1}"
 
   if [[ -z "${path}" ]]; then
-    pick_device "all" || return $?
+    pick_device "disk" || return $?
     [[ -n "${REPLY}" ]] && path="${REPLY}" || return 0
   fi
 
   if [[ ! -b "${path}" ]]; then
-    echo "Invalid block device path"
+    echo "Invalid block device"
+    return 2
+  elif ! is_type_of "${path}" "disk"; then
+    echo "Invalid disk block device"
     return 2
   elif ! sudo smartctl -i "${path}" &> /dev/null; then
     echo "Unable to retrieve SMART data"
@@ -572,16 +585,16 @@ scan_device () {
   fi
 }
 
-# Shows the list of devices of the given type.
+# Shows the list of block devices of the given type.
 # Arguments:
-#  type: disk, part, rom or all
+#  type: disk, part or rom
 # Outputs:
-#  A list of devices.
+#  A list of block devices.
 list_devices () {
   local type="${1}"
 
-  if [[ -n "${type}" ]] && [[ ! "${type}" =~ ^(disk|part|rom)$ ]]; then
-    echo "Invalid device type value"
+  if [[ ! "${type}" =~ ^(disk|part|rom)$ ]]; then
+    echo "Invalid block device type"
     return 2
   fi
 
@@ -589,7 +602,7 @@ list_devices () {
   devices="$(find_devices "${type}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read ${type:-\b} devices"
+    echo "Unable to read ${type} block devices"
     return 2
   fi
 
@@ -597,7 +610,7 @@ list_devices () {
   len="$(count "${devices}")" || return 1
 
   if [[ ${len} -eq 0 ]]; then
-    echo "No ${type:-\b} devices have found"
+    echo "No ${type} block devices have found"
     return 0
   fi
 
@@ -674,7 +687,7 @@ list_mounts () {
   devices="$(find_devices "part,rom" "mounted")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read mounted devices"
+    echo "Unable to read mounted block devices"
     return 2
   fi
 
@@ -685,7 +698,7 @@ list_mounts () {
   }')"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read mounted folders"
+    echo "Unable to read mounted shared folders"
     return 2
   fi
 
@@ -712,7 +725,7 @@ list_mounts () {
   fi
 }
 
-# Mounts the device with the given path.
+# Mounts the block device with the given path.
 # Globals:
 #  REPLY, HOME, USER
 # Arguments:
@@ -728,19 +741,22 @@ mount_device () {
   if [[ ! -b "${path}" ]]; then
     echo "Invalid block device"
     return 2
+  elif is_type_of "${path}" "disk"; then
+    echo "Not mountable block device"
+    return 2
   elif grep -qs "${path} " /proc/mounts; then
-    echo "Device ${path} is already mounted"
+    echo "Block device ${path} is already mounted"
     return 2
   fi
   
   udisksctl mount -b "${path}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to mount device"
+    echo "Failed to mount block device"
     return 2
   fi
 
-  echo "Device ${path} has been mounted"
+  echo "Block device ${path} has been mounted"
 
   local local_home="${HOME}/mount/local"
 
@@ -750,7 +766,7 @@ mount_device () {
   fi
 }
 
-# Unmounts the device with the given path.
+# Unmounts the block device with the given path.
 # Globals:
 #  REPLY, HOME, USER
 # Arguments:
@@ -766,8 +782,11 @@ unmount_device () {
   if [[ ! -b "${path}" ]]; then
     echo "Invalid block device"
     return 2
+  elif is_type_of "${path}" "disk"; then
+    echo "Not mountable block device"
+    return 2
   elif ! grep -qs "${path} " /proc/mounts; then
-    echo "Device ${path} is not mounted"
+    echo "Block device ${path} is not mounted"
     return 2
   fi
 
@@ -782,19 +801,20 @@ unmount_device () {
   unmount_partition "${path}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to unmount device"
+    echo "Failed to unmount block device"
     return 2
   fi
 
-  echo "Device ${path} has been unmounted"
+  echo "Block device ${path} has been unmounted"
 }
 
-# Formats the disk device with the given path.
+# Formats the disk block device with the given path,
+# creating a new partition table of a single primary partition.
 # Globals:
 #  REPLY
 # Arguments:
 #  path: the path of a block disk device
-format_device () {
+format_disk () {
   local path="${1}"
 
   if [[ -z "${path}" ]]; then
@@ -805,7 +825,7 @@ format_device () {
   if [[ ! -b "${path}" ]]; then
     echo "Invalid block device"
     return 2
-  elif ! is_disk "${path}"; then
+  elif ! is_type_of "${path}" "disk"; then
     echo "Not a disk block device"
     return 2
   elif is_system_disk "${path}"; then
@@ -829,7 +849,7 @@ format_device () {
   [[ "${REPLY}" != "yes" ]] && return 0
 
   echo "Unmounting disk partitions..."
-  unmount_disk_partitions "${path}" || return 1
+  unmount_partitions "${path}" || return 1
 
   echo "Cleaning disk partitions..."
   clean_partitions "${path}" &&
@@ -843,11 +863,11 @@ format_device () {
   format_partition "${path}" "1" "${fs_type}" "${label}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to format device ${path}"
+    echo "Failed to format disk ${path}"
     return 2
   fi
 
-  echo "Device ${path} has been formated"
+  echo "disk ${path} has been formated"
 }
 
 # Ejects the disk block device with the given path.
@@ -855,7 +875,7 @@ format_device () {
 #  REPLY
 # Arguments:
 #  path: the path of a block device
-eject_device () {
+eject_disk () {
   local path="${1}"
 
   if [[ -z "${path}" ]]; then
@@ -866,17 +886,20 @@ eject_device () {
   if [[ ! -b "${path}" ]]; then
     echo "Invalid block device"
     return 2
-  elif ! is_removable_disk "${path}"; then
-    echo "Not a removable disk block device"
-    return 2
   elif is_system_disk "${path}"; then
     echo "Cannot eject a system disk"
+    return 2
+  elif ! is_type_of "${path}" "disk"; then
+    echo "Not a disk block device"
+    return 2
+  elif ! is_removable_disk "${path}"; then
+    echo "Not a removable disk block device"
     return 2
   fi
 
   echo "Unmounting disk partitions..."
 
-  unmount_disk_partitions "${path}"
+  unmount_partitions "${path}"
 
   if [[ $? -ne 0 ]]; then
     echo "Failed to unmount disk partitions"
@@ -886,10 +909,10 @@ eject_device () {
   udisksctl power-off -b "${path}" &> /dev/null
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to power off the device"
+    echo "Unable to power off disk ${path}"
   fi
 
-  echo "Device ${path} power set to off"  
+  echo "Disk ${path} power set to off"
 }
 
 # Creates a bootable archlinux installation drive.
@@ -908,11 +931,14 @@ create_bootable () {
   if [[ ! -b "${path}" ]]; then
     echo "Invalid block device"
     return 2
-  elif ! is_removable_disk "${path}"; then
-    echo "Not a removable disk block device"
-    return 2
   elif is_system_disk "${path}"; then
     echo "Cannot create bootable on a system disk"
+    return 2
+  elif ! is_type_of "${path}" "disk"; then
+    echo "Not a disk block device"
+    return 2
+  elif ! is_removable_disk "${path}"; then
+    echo "Not a removable disk block device"
     return 2
   fi
 
@@ -933,7 +959,7 @@ create_bootable () {
     hosts="[${hosts}]"
 
     local host=''
-    pick_one "Select the mirror host:" "${hosts}" "vertical" || return $?
+    pick_one "Select a mirror host close to you:" "${hosts}" "vertical" || return $?
     [[ -n "${REPLY}" ]] && host="${REPLY}" || return 0
 
     local file='archlinux-x86_64.iso'
@@ -1002,7 +1028,7 @@ create_bootable () {
   [[ "${REPLY}" != "yes" ]] && return 0
 
   echo "Unmounting disk partitions..."
-  unmount_disk_partitions "${path}" || return 1
+  unmount_partitions "${path}" || return 1
 
   echo "Cleaning disk partitions..."
   clean_partitions "${path}" &&
@@ -1134,23 +1160,26 @@ show_help () {
   printf " %-28s %s\n" \
     "help" "Show this help message." \
     "" "" \
-    "show status" "Show a report of disks and the file system." \
+    "show status" "Show a report of the file system." \
     "" "" \
-    "show device [<path>]" "Show the data of a block device." \
-    "scan device [<path>]" "Scan a block device for SMART data." \
+    "show disk [<path>]" "Show a disk block device." \
+    "show partition [<path>]" "Show a partition block device." \
+    "show rom [<path>]" "Show an optical drive block device." \
     "" "" \
-    "list devices [<type>]" "List all the block devices or by type," \
-    "" "where type could be disk, part or rom." \
-    "list shares [<host>]" "Fetch the shared folders of a host." \
-    "list mounts" "List all mounted block devices and shared folders." \
+    "list disks" "List all disk block devices." \
+    "list partitions" "List all partition block devices." \
+    "list roms" "List all optical drive block devices." \
+    "list shares [<host>]" "List the shared folders of a host." \
+    "list mounts" "List all mounting points." \
     "" "" \
-    "mount device [<path>]" "Mount a block device." \
-    "unmount device [<path>]" "Unmount a block device." \
-    "format device [<path>]" "Format a disk block device." \
-    "eject device [<path>]" "Eject a disk block device." \
-    "" "" \
+    "mount device [<path>]" "Mount a partition or rom block device." \
+    "unmount device [<path>]" "Unmount a partition or rom block device." \
     "mount share [<host>]" "Mount a shared folder." \
     "unmount share [<uri>]" "Unmount a shared folder." \
+    "" "" \
+    "format disk [<path>]" "Format a disk block device." \
+    "eject disk [<path>]" "Eject a removable disk block device." \
+    "scan disk [<path>]" "Scan a disk block device for SMART data." \
     "" "" \
     "create bootable [<path>]" "Create a bootable archlinux installation drive."
 }
@@ -1181,7 +1210,9 @@ loop () {
     case "${cmd[0]}" in
       "list")
         case "${cmd[1]}" in
-          "devices") list_devices "${cmd[2]}";;
+          "disks") list_devices "disk";;
+          "partitions") list_devices "part";;
+          "roms") list_devices "rom";;
           "shares") list_shares "${cmd[2]}";;
           "mounts") list_mounts;;
           *) echo "Invalid or unknown command";;
@@ -1189,12 +1220,9 @@ loop () {
       "show")
         case "${cmd[1]}" in
           "status") show_status;;
-          "device") show_device "${cmd[2]}";;
-          *) echo "Invalid or unknown command";;
-        esac;;
-      "scan")
-        case "${cmd[1]}" in
-          "device") scan_device "${cmd[2]}";;
+          "disk") show_device "disk" "${cmd[2]}";;
+          "partition") show_device "part" "${cmd[2]}";;
+          "rom") show_device "rom" "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       "mount")
@@ -1211,12 +1239,17 @@ loop () {
         esac;;
       "format")
         case "${cmd[1]}" in
-          "device") format_device "${cmd[2]}";;
+          "disk") format_disk "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       "eject")
         case "${cmd[1]}" in
-          "device") eject_device "${cmd[2]}";;
+          "disk") eject_disk "${cmd[2]}";;
+          *) echo "Invalid or unknown command";;
+        esac;;
+      "scan")
+        case "${cmd[1]}" in
+          "disk") scan_disk "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       "create")
