Move network disk impl from mount to disks util

diff --git a/resources/stack/disks b/resources/stack/disks
--- a/resources/stack/disks
+++ b/resources/stack/disks
@@ -3,6 +3,7 @@
 source /opt/stack/utils
 
 require "udisks2"
+require "glib2"
 
 prompt () {
   read -rep "[disks] " REPLY
@@ -68,11 +69,35 @@ unmount_local_disk () {
 }
 
 mount_remote_disk () {
-  echo "No implementation found."
+  local DEVICE=$1
+
+  if gio mount -l | grep -q "$DEVICE"; then
+    echo "Device $DEVICE is already mounted"
+    return 1
+  fi
+
+  gio mount "$DEVICE" &&
+    echo "Device $DEVICE mounted successfully" ||
+    echo "Failed to mount device from $DEVICE"
+
+  if [ -d "/run/user/${UID}/gvfs" ] && [ ! -L "$HOME/mount/remote" ]; then
+    mkdir -p "$HOME/mount/remote"
+    ln -s "/run/user/${UID}/gvfs" "$HOME/mount/remote"
+  fi
 }
 
 unmount_remote_disk () {
-  echo "No implementation found."
+  local DEVICE=$1
+
+  if ! gio mount -l | grep -q "$DEVICE"; then
+    echo "No remote disk $DEVICE is mounted"
+    return 1
+  fi
+
+  sync &&
+  gio mount -u "$DEVICE" &&
+    echo "Device $DEVICE unmounted successfully" ||
+    echo "Failed to umount device $DEVICE"
 }
 
 help () {
@@ -81,8 +106,10 @@ help () {
   echo -e "\nCOMMANDS"
   printf " %-20s\t%s\n" \
     "list local|remote" "List disks..." \
-    "mount local|remote <name>" "Mount..." \
-    "unmount local|remote <name>" "Unmount..." \
+    "mount local <name>" "Mount..." \
+    "mount remote <uri>" "Mount..." \
+    "unmount local <name>" "Unmount..." \
+    "unmount remote <uri>" "Unmount..." \
     "help" "Show this help message."
 }
 
@@ -112,13 +139,13 @@ main () {
       "mount")
         case "${CMD[1]}" in
           "local") mount_local_disk "${CMD[2]}";;
-          "remote") mount_remote_disk "${CMD[2]}";;
+          "remote") mount_remote_disk "${CMD[2]}://${CMD[3]}/${CMD[4]}";;;;
           *) echo "Invalid disk type: '${CMD[1]}'";;
         esac;;
       "unmount")
         case "${CMD[1]}" in
           "local") unmount_local_disk "${CMD[2]}";;
-          "remote") unmount_remote_disk "${CMD[2]}";;
+          "remote") unmount_remote_disk "${CMD[2]}://${CMD[3]}/${CMD[4]}";;
           *) echo "Invalid disk type: '${CMD[1]}'";;
         esac;;
       *) echo "Unknown or invalid command: '$REPLY'";; 
