Refine text in help and documentation of color operations

diff --git a/resources/stack/displays b/resources/stack/displays
--- a/resources/stack/displays
+++ b/resources/stack/displays
@@ -1224,7 +1224,7 @@ delete_layout () {
 }
 
 # Sets the color profile of the device connected to the output
-# with the given name and save it to the color settings. The
+# with the given name and saves it to the color settings. The
 # profile should be the filename of any .icc or .icm color
 # calibration files stored in $COLORS_HOME.
 # Globals:
@@ -1256,6 +1256,7 @@ set_color () {
   fi
 
   if [[ -z "${profile}" ]]; then
+    # List all color calibration files under $COLORS_HOME
     local query='{key: .filename, value: .filename}'
     query="[.[]|select(.filename|test(\".ic(c|m)$\"))|${query}]"
   
@@ -1278,7 +1279,7 @@ set_color () {
     echo "Invalid color profile file"
     return 2
   elif [[ ! -f "${COLORS_HOME}/${profile}" ]]; then
-    echo "Cannot find color profile file"
+    echo "Cannot find color profile file ${profile}"
     return 2
   fi
 
@@ -1428,7 +1429,7 @@ delete_color () {
       return 2
     fi
 
-    pick_one "Select a color setting:" "${colors}" "tabular" || return 1
+    pick_one "Select a color setting:" "${colors}" "vertical" || return 1
     [[ -n "${REPLY}" ]] && index="${REPLY}" || return
   fi
 
@@ -1458,7 +1459,8 @@ delete_color () {
   echo "Color setting has been deleted"
 }
 
-# List all the color settings per device have stored in settings.
+# List all the color settings per device being stored
+# in settings.
 # Globals:
 #  SETTINGS_FILE
 # Arguments:
@@ -1479,7 +1481,7 @@ list_colors () {
   local query=''
   query+='if .colors|length > 0'
   query+=" then .colors|to_entries[]|\"${color}\""
-  query+=' else "No color setting have found"'
+  query+=' else "No color settings have found"'
   query+='end'
 
   query="[${query}]|join(\"\n\n\")"
@@ -1492,9 +1494,8 @@ list_colors () {
   fi
 }
 
-# Restores the color profiles of any devices currently
-# connected to an output, only if such profile is stored
-# in the settings file.
+# Restores the color settings of any devices currently
+# connected to an output.
 # Globals:
 #  COLORS_HOME, SETTINGS_FILE, DISPLAY
 # Arguments:
@@ -1506,7 +1507,7 @@ restore_colors () {
   fi
 
   local colors=''
-  colors="$(jq -cr 'if .colors then .colors else [] end' "${SETTINGS_FILE}")"
+  colors="$(jq -cr 'if .colors then .colors else [] end' "${SETTINGS_FILE}")" || return 1
 
   local len=0
   len="$(count "${colors}")" || return 1
@@ -1519,25 +1520,29 @@ restore_colors () {
   local outputs=''
   outputs="$(find_outputs "active")" || return 1
 
+  local cmd=''
+  cmd+="\"xcalib -d ${DISPLAY} -s 0 -o \(.index) ${COLORS_HOME}/\(.profile)\""
+
   local query=''
   query+='. + $c'
   query+=' |group_by([.model_name, .product_id, .serial_number])'
   query+=" |map({index: (.[0].index), profile: (.[].profile|select(.))})[]"
-  query+=" |\"xcalib -d ${DISPLAY} -s 0 -o \(.index) ${COLORS_HOME}/\(.profile)\""
+  query+=" |${cmd}"
 
-  local xcalib_cmds=''
-  xcalib_cmds="$(echo "${outputs}" | jq -cr --argjson c "${colors}" "${query}")" || return 1
+  local cmds=''
+  cmds="$(echo "${outputs}" | jq -cr --argjson c "${colors}" "${query}")" || return 1
 
-  # Iterate over xcalib commands and execute
+  # Iterate over xcalib commands and execute one by one
   local failed='false'
-  local xcalib_cmd=''
-  while read -r xcalib_cmd; do
-    local result="$(${xcalib_cmd} 2>&1)"
+  local cmd=''
+
+  while read -r cmd; do
+    local result="$(${cmd} 2>&1)"
 
     if [[ $? -ne 0 ]] || [[ -n "${result}" ]]; then
       failed='true'
     fi
-  done <<< "${xcalib_cmds}"
+  done <<< "${cmds}"
 
   if [[ "${failed}" == "true" ]]; then
     echo "Failed to restore all color profiles"
@@ -1593,10 +1598,10 @@ help () {
     "" "where profile should be any calibration files" \
     "" "stored under ${COLORS_HOME}." \
     "reset color [<output>]" "Reset color profile of the device connected to output." \
-    "delete color [<index>]" "Delete the color setting with the given index." \
     "" "" \
-    "list colors" "List any colors have set per device." \
-    "restore colors" "Restore color profiles saved in settings." \
+    "list colors" "List all color settings per device being currently stored." \
+    "delete color [<index>]" "Delete the stored color setting with the given index." \
+    "restore colors" "Apply all stored color settings of active devices." \
     "" "" \
     "set layout" "Set the layout of active outputs." \
     "save layout" "Save the current layout." \
