Add cmd to set the keyboard console keymap

diff --git a/resources/stack/langs b/resources/stack/langs
--- a/resources/stack/langs
+++ b/resources/stack/langs
@@ -21,16 +21,31 @@ show_status () {
     printf "%-12s\t%s\n", l":", substr($0, i+1)}'
 }
 
+set_keymap () {
+  local KEYMAP=$1
+
+  if ! localectl list-keymaps | grep -qE "^${KEYMAP}$"; then
+    echo "Invalid keymap value: '$KEYMAP'"
+    return 1
+  fi
+
+  echo "KEYMAP=$KEYMAP" | sudo tee /etc/vconsole.conf > /dev/null &&
+    sudo loadkeys "$KEYMAP" &&
+    echo "Keyboard keymap set to $KEYMAP" ||
+    echo "Something went setting up the keymap"
+}
+
 help () {
   echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."
 
   echo -e "\nOBJECTS"
   printf " %-25s\t%s\n" \
-      "..." "An object to handle..."
+      "keymap" "An object to handle the keyboard keymap."
 
   echo -e "\nCOMMANDS"
   printf " %-25s\t%s\n" \
     "show status" "Show the locale and languages status of the system." \
+    "set keymap <keymap>" "Set the keyboard's console keymap." \
     "help" "Show this help message."
 }
 
@@ -61,6 +76,11 @@ loop () {
         case "${CMD[1]}" in
           "status") show_status;;
           *) echo "Unknown or invalid command: '$REPLY'";;
+        esac;;
+      "set")
+        case "${CMD[1]}" in
+          "keymap") set_keymap "${CMD[2]}";;
+          *) echo "Unknown or invalid command: '$REPLY'";; 
         esac;;
       *) echo "Unknown or invalid command: '$REPLY'";; 
     esac
