Let user decide which wifi device used to scan and connect

diff --git a/resources/stack/networks b/resources/stack/networks
--- a/resources/stack/networks
+++ b/resources/stack/networks
@@ -105,17 +105,19 @@ find_connection () {
 }
 
 # Returns any detected wifi networks broadcasting in
-# your local area having a singal strength equal to
-# the given value.
+# your local area having a singal strength equal or
+# greter to the given value.
 # Arguments:
+#  device: the name of a wifi device
 #  signal: a signal limitation value
 # Outputs:
 #  A json array list of wifi networks.
 find_wifis () {
-  local signal="${1:-"0"}"
+  local device="${1}"
+  local signal="${2:-"0"}"
 
   local networks=''
-  networks="$(nmcli -f SSID,SIGNAL,CHAN,SECURITY -t device wifi list |
+  networks="$(nmcli -f SSID,SIGNAL,CHAN,SECURITY -t device wifi list ifname "${device}" |
     awk -v limit="${signal}" -F: '{
       if ($2 >= limit) {
         schema="\"ssid\":\"%s\","
@@ -496,11 +498,23 @@ list_connections () {
 # Detects the available wifi networks in the local area
 # with signal strength at least the given limit.
 # Arguments:
-#  limit: a signal limitation value
+#  device: the name of a wifi device
+#  singal:  a signal limitation value
 # Outputs:
 #  The list of wifi networks.
 scan () {
-  local signal="${1:-"0"}"
+  local device="${1}"
+  local signal="${2:-"0"}"
+
+  if [[ -z "${device}" ]]; then
+    pick_device "wifi" || return $?
+    [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
+  fi
+
+  if ! validate "device" "${device}"; then
+    echo "Invalid or unknwon device"
+    return 2
+  fi
 
   if [[ ! "${signal}" =~ ^[0-9][0-9]{,2}$ ]]; then
     echo "Invalid signal limit value"
@@ -513,7 +527,7 @@ scan () {
   echo "Detecting available wifi networks..."
 
   local networks=''
-  networks="$(find_wifis "${signal}")"
+  networks="$(find_wifis "${device}" "${signal}")"
 
   if [[ $? -ne 0 ]]; then
     echo "Unable to detect wifi networks"
@@ -543,15 +557,27 @@ scan () {
 # Globals:
 #  REPLY
 # Arguments:
-#  ssid: the ssid of the wifi network
+#  device: the name of a wifi device
+#  ssid:   the ssid of the wifi network
 connect () {
-  local ssid="${1}"
+  local device="${1}"
+  local ssid="${2}"
+
+  if [[ -z "${device}" ]]; then
+    pick_device "wifi" || return $?
+    [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
+  fi
+
+  if ! validate "device" "${device}"; then
+    echo "Invalid or unknwon device"
+    return 2
+  fi
 
   if [[ -z "${ssid}" ]]; then
     echo "Detecting available wifi networks..."
 
     local networks=''
-    networks="$(find_wifis)" || return 1
+    networks="$(find_wifis "${device}")" || return 1
 
     local len=0
     len="$(count "${networks}")" || return 1
@@ -574,7 +600,7 @@ connect () {
 
   echo "Connecting to ${ssid}..."
 
-  nmcli device wifi connect "${ssid}" password "${key}" hidden yes
+  nmcli device wifi connect "${ssid}" password "${key}" ifname "${device}" hidden yes
   
   if [[ $? -ne 0 ]]; then
     echo "Failed to connect to ${ssid}"
@@ -1209,8 +1235,8 @@ show_help () {
     "list devices" "List the network devices." \
     "list connections" "List the network connections." \
     "" "" \
-    "scan [<signal>]" "Detect wifi networks with min signal." \
-    "connect [<ssid>]" "Connect to a wifi network." \
+    "scan [<device>] [<signal>]" "Detect wifi networks with min signal." \
+    "connect [<device>] [<ssid>]" "Connect to a wifi network." \
     "" "" \
     "up device [<name>]" "Enable a network device." \
     "down device [<name>]" "Disable a network device." \
@@ -1269,14 +1295,14 @@ loop () {
           "proxies") list_proxies;;
           *) echo "Invalid or unknown command";;
         esac;;
-      "scan") scan "${cmd[1]}";;
+      "scan") scan "${cmd[1]}" "${cmd[2]}";;
       "power")
         case "${cmd[1]}" in
           "network") power_network "${cmd[2]}";;
           "wifi") power_wifi "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
-      "connect") connect "${cmd[1]}";; 
+      "connect") connect "${cmd[1]}" "${cmd[2]}";; 
       "up") up "${cmd[1]}" "${cmd[2]}";;
       "down") down "${cmd[1]}" "${cmd[2]}";;
       "add")
