Add cmd to add new ethernet connections

diff --git a/resources/stack/networks b/resources/stack/networks
--- a/resources/stack/networks
+++ b/resources/stack/networks
@@ -16,13 +16,21 @@ find_status () {
   nmcli general | jc --nmcli | jq -cer '.[0]' || return 1
 }
 
-# Returns the list of network devices.
+# Returns the list of network devices of the
+# given type.
 # Arguments:
-#  None
+#  type: ethernet, wifi or bridge
 # Outputs:
 #  A json array of device objects.
 find_devices () {
-  nmcli device | jc --nmcli || return 1
+  local type="${1}"
+
+  local query='.'
+  if [[ -n "${type}" ]]; then
+    query="[.[]|select(.type == \"${type}\")]"
+  fi
+
+  nmcli device | jc --nmcli | jq -cer "${query}" || return 1
 }
 
 # Returns the device with the given name.
@@ -121,15 +129,17 @@ validate () {
 # Globals:
 #  REPLY
 # Arguments:
-#  None
+#  type: ethernet, wifi or bridge
 # Outputs:
 #  A menu of device names.
 pick_device () {
+  local type="${1}"
+
   local query='{key: .device, value: .device}'
   query="[.[]|${query}]"
 
   local devices=''
-  devices="$(find_devices | jq -cer "${query}")" || return 1
+  devices="$(find_devices "${type}" | jq -cer "${query}")" || return 1
 
   local len=0
   len="$(count "${devices}")" || return 1
@@ -279,6 +289,7 @@ show_device () {
   query+='\(.ip4_gateway|if . then "\nGateway:     \(.)" else "" end)'
   query+='\(.ip4_route_1|if . then "\nRoute:       \(.dst)" else "" end)'
   query+='\(.ip4_dns_1|if . then "\nDNS:         \(.)" else "" end)'
+  query+='\(.ip4_dns_2|if . then ", \(.)" else "" end)'
   query+='\(.ip6_address_1|if . then "\nIPv6:        \(.)" else "" end)'
   query+='\(.ip6_gateway|if . then "\nGateway:     \(.)" else "" end)'
   query+='\(.ip6_route_1|if . then "\nRoute:       \(.dst)" else "" end)'
@@ -326,6 +337,7 @@ show_connection () {
   query+='\(.ip4_gateway|if . then "\nGateway:     \(.)" else "" end)'
   query+='\(.ip4_route_1|if . then "\nRoute:       \(.dst)" else "" end)'
   query+='\(.ip4_dns_1|if . then "\nDNS:         \(.)" else "" end)'
+  query+='\(.ip4_dns_2|if . then ", \(.)" else "" end)'
   query+='\(.ip6_address_1|if . then "\nIPv6:        \(.)" else "" end)'
   query+='\(.ip6_gateway|if . then "\nGateway:     \(.)" else "" end)'
   query+='\(.ip6_route_1|if . then "\nRoute:       \(.dst)" else "" end)'
@@ -579,13 +591,13 @@ down () {
   echo "${object^} ${name} has been disabled"
 }
 
-# Deletes the device or connection with the given name.
+# Removes the device or connection with the given name.
 # Globals:
 #  REPLY
 # Arguments:
 #  object: device or connection
 #  name:   the name of a device or connection
-delete () {
+remove () {
   local object="${1}"
   local name="${2}"
 
@@ -607,7 +619,7 @@ delete () {
     return 2
   fi
 
-  echo "Deleting ${object} ${name}..."
+  echo "Removing ${object} ${name}..."
 
   if [[ "${object}" == "device" ]]; then
     nmcli device delete "${name}" &>/dev/null
@@ -616,12 +628,72 @@ delete () {
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to delete ${object}"
+    echo "Failed to remove ${object}"
     return 2
   fi
 
   sleep 3
-  echo "${object^} ${name} has been deleted"
+  echo "${object^} ${name} has been removed"
+}
+
+# Adds a new ethernet connection with the given name.
+# Globals:
+#  REPLY
+# Arguments:
+#  name: the name of the connection
+add () {
+  local name="${1}"
+
+  if [[ -z "${name}" ]]; then
+    echo "Connection name is missing"
+    return 2
+  fi
+
+  if find_connection "${name}" &>/dev/null; then
+    echo "Connection ${name} already exists"
+    return 2
+  fi
+
+  local device=''
+  pick_device "ethernet" || return $?
+  [[ -n "${REPLY}" ]] && device="${REPLY}" || return 0
+
+  local dhcp=''
+  confirm "Want to enable DHCP mode?" || return $?
+  [[ -n "${REPLY}" ]] && dhcp="${REPLY}" || return 0
+
+  echo "Creating connection ${name}..."
+
+  if [[ "${dhcp}" == "yes" ]]; then
+    nmcli connection add type "ethernet" \
+      con-name "${name}" ifname "${device}" ipv4.method "auto"
+  else
+    local re='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
+
+    ask "Enter the static ip:" "${re}" || return $?
+    local ip="${REPLY}"
+
+    ask "Enter the gateway:" "${re}" || return $?
+    local gateway="${REPLY}"
+
+    ask "Enter the primary DNS:" "${re}" || return $?
+    local dns="${REPLY}"
+
+    ask "Enter the secondary DNS:" "${re}" || return $?
+    dns="${dns} ${REPLY}"
+
+    nmcli connection add type "ethernet" \
+      con-name "${name}" ifname "${device}" ipv4.method "manual" \
+      ipv4.addresses "${ip}/24" ipv4.gateway "${gateway}" ipv4.dns "${dns}"
+  fi
+
+  if [[ $? -ne 0 ]]; then
+    echo "Failed to create connection"
+    return 2
+  fi
+
+  sleep 3
+  echo "Connection ${name} has been created"
 }
 
 # Sets the system networking to on or off.
@@ -697,12 +769,17 @@ show_help () {
     "list devices" "List the network devices." \
     "list connections" "List the network connections." \
     "" "" \
-    "scan [signal]" "Detect wifi networks in your area with minimum signal." \
+    "scan [<signal>]" "Detect wifi networks with min signal." \
     "connect [<ssid>]" "Connect to a wifi network." \
     "" "" \
-    "up device|connection [<name>]" "Enable a device or connection." \
-    "down device|connection [<name>]" "Disable a device or connection." \
-    "delete device|connection [<name>]" "Delete a device or connection." \
+    "up device [<name>]" "Enable a network device." \
+    "down device [<name>]" "Disable a network device." \
+    "remove device [<name>]" "Remove a software network device." \
+    "" "" \
+    "up connection [<name>]" "Enable a connection." \
+    "down connection [<name>]" "Disable a connection." \
+    "add connection <name>" "Add a new connection." \
+    "remove connection [<name>]" "Remove a connection." \
     "" "" \
     "power network on|off" "Set the system network to on or off." \
     "power wifi on|off" "Set the wifi device to on or off."
@@ -755,7 +832,12 @@ loop () {
       "connect") connect "${cmd[1]}";; 
       "up") up "${cmd[1]}" "${cmd[2]}";;
       "down") down "${cmd[1]}" "${cmd[2]}";;
-      "delete") delete "${cmd[1]}" "${cmd[2]}";;
+      "add")
+        case "${cmd[1]}" in
+          "connection") add "${cmd[2]}";;
+          *) echo "Invalid or unknown command";;
+        esac;;
+      "remove") remove "${cmd[1]}" "${cmd[2]}";;
       *) echo "Invalid or unknown command";; 
     esac
 
