Move connect function next to scan for maintainability

diff --git a/resources/stack/networks b/resources/stack/networks
--- a/resources/stack/networks
+++ b/resources/stack/networks
@@ -453,6 +453,49 @@ scan () {
   echo "${networks}" | jq -cer "${query}" || return 1
 }
 
+# Connect to the wifi network with the given id
+# and secret key.
+# Globals:
+#  REPLY
+# Arguments:
+#  ssid: the ssid of the wifi network
+connect () {
+  local ssid="${1}"
+
+  if [[ -z "${ssid}" ]]; then
+    echo "Detecting available wifi networks..."
+
+    local networks=''
+    networks="$(find_wifis)" || return 1
+
+    local len=0
+    len="$(count "${networks}")" || return 1
+
+    if [[ ${len} -eq 0 ]]; then
+      echo "No wifi networks have been detected"
+      return 0
+    fi
+
+    local query='{key: .ssid, value: "\(.ssid) [\(.signal)]"}'
+    query="[.[]|${query}]"
+
+    networks="$(echo "${networks}" | jq -cer "${query}")" || return 1
+    pick_one "Select a wifi network:" "${networks}" "vertical" || return $?
+    [[ -n "${REPLY}" ]] && ssid="${REPLY}" || return 0
+  fi
+
+  ask_password "Enter the private key:"
+  local key="${REPLY}"
+
+  nmcli device wifi connect "${ssid}" password "${key}" hidden yes &&
+   wait_progress
+  
+  if [[ $? -ne 0 ]]; then
+    echo "Failed to establish connection with ${ssid}"
+    return 2
+  fi
+}
+
 # Enables the device or connection with the given name.
 # Globals:
 #  REPLY
@@ -640,49 +683,6 @@ power_wifi () {
   fi
 
   echo "Wifi power set to ${mode}"
-}
-
-# Connect to the wifi network with the given id
-# and secret key.
-# Globals:
-#  REPLY
-# Arguments:
-#  ssid: the ssid of the wifi network
-connect () {
-  local ssid="${1}"
-
-  if [[ -z "${ssid}" ]]; then
-    echo "Detecting available wifi networks..."
-
-    local networks=''
-    networks="$(find_wifis)" || return 1
-
-    local len=0
-    len="$(count "${networks}")" || return 1
-
-    if [[ ${len} -eq 0 ]]; then
-      echo "No wifi networks have been detected"
-      return 0
-    fi
-
-    local query='{key: .ssid, value: "\(.ssid) [\(.signal)]"}'
-    query="[.[]|${query}]"
-
-    networks="$(echo "${networks}" | jq -cer "${query}")" || return 1
-    pick_one "Select a wifi network:" "${networks}" "vertical" || return $?
-    [[ -n "${REPLY}" ]] && ssid="${REPLY}" || return 0
-  fi
-
-  ask_password "Enter the private key:"
-  local key="${REPLY}"
-
-  nmcli device wifi connect "${ssid}" password "${key}" hidden yes &&
-   wait_progress
-  
-  if [[ $? -ne 0 ]]; then
-    echo "Failed to establish connection with ${ssid}"
-    return 2
-  fi
 }
 
 # Shows the help message.
