Add cmd to set the volume of the notifications sound

diff --git a/resources/stack/notifications b/resources/stack/notifications
--- a/resources/stack/notifications
+++ b/resources/stack/notifications
@@ -3,6 +3,8 @@
 set -o pipefail
 source /opt/stack/utils
 
+SETTINGS_FILE="${CONFIG_HOME}/notifications.json"
+
 # Returns the list of all archived notifications 
 # sorted by the given field in the given order.
 # Arguments:
@@ -217,6 +219,42 @@ set_popup () {
   echo "Pop-up notifications set to ${mode}"
 }
 
+# Sets the volume of the notifications sound.
+# Globals:
+#  SETTINGS_FILE, CONFIG_HOME
+# Arguments:
+#  percent: a value between 0 and 100
+set_volume () {
+  local percent="${1}"
+
+  if [[ -z "${percent}" ]]; then
+    ask "Enter the volume [0, 100]:" "^[0-9]{1,3}$" || return $?
+    percent="${REPLY}"
+  elif [[ ! "${percent}" =~ ^[0-9]{1,3}$ ]]; then
+    echo 'Invalid volume value'
+    return 2
+  fi
+
+  if [[ ${percent} -lt 0 ]] || [[ ${percent} -gt 100 ]]; then
+    echo 'Volume is out of range'
+    return 2
+  fi
+
+  # Scale down volume to [0,1] range
+  percent=$(echo "${percent}" | awk '{print $0/100}')
+
+  local settings='{}'
+
+  if [[ -f "${SETTINGS_FILE}" ]]; then
+    settings="$(jq -e ".volume = ${percent}" "${SETTINGS_FILE}")" || return 1
+  else
+    settings="$(echo "{\"volume\": ${percent}}" | jq -e '.')" || return 1
+  fi
+
+  mkdir -p "${CONFIG_HOME}"
+  echo "${settings}" > "${SETTINGS_FILE}"
+}
+
 # Shows the help message.
 # Arguments:
 #  mode: once or none
@@ -248,6 +286,7 @@ show_help () {
     "" "id or appname in asc or desc order." \
     "" "" \
     "set popup on|off" "Show or hide pop-up notifications." \
+    "set volume <percent>" "Set the volume of the notifications sound." \
     "" "" \
     "mute all" "Pause the notifications stream." \
     "unmute all" "Restore the notifications stream." \
@@ -306,6 +345,7 @@ loop () {
       "set")
         case "${cmd[1]}" in
           "popup") set_popup "${cmd[2]}";;
+          "volume") set_volume "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       *) echo "Invalid or unknown command";; 
