List archived notifications by id and appname

diff --git a/resources/stack/notifications b/resources/stack/notifications
--- a/resources/stack/notifications
+++ b/resources/stack/notifications
@@ -3,6 +3,28 @@
 set -o pipefail
 source /opt/stack/utils
 
+# Returns the list of archived notifications 
+# sorted by the given field in the given order.
+# Arguments:
+#  sort_by:  id or appname
+#  order:    asc or desc, default is asc
+# Outputs:
+#  A json array of notification objects.
+find_archived () {
+  local sort_by="${1}"
+  local order="${2}"
+
+  local query='.data[0]'
+
+  if [[ "${sort_by}" =~ ^(id|appname)$ ]]; then
+    query+="|sort_by(.${sort_by})"
+
+    [[ "${order}" == "desc" ]] && query+='|reverse'
+  fi
+
+  dunstctl history | jq -cr "${query}" || return 1
+}
+
 # Shows a prompt status and asks user to enter the
 # next command, which is kept in the global var REPLY.
 # Globals:
@@ -63,6 +85,37 @@ show_status () {
   echo "${status}" | jq -cer "\"${query}\"" || return 1
 }
 
+# Shows the list of archived notifications sorted by the
+# optionally given field and order.
+# Arguments:
+#  sort_by: id or appname, default is id
+#  order:   asc or desc, default is asc
+# Outputs:
+#  A long list of notificaions data.
+list_archived () {
+  local sort_by="${1:-"id"}"
+  local order="${2:-"asc"}"
+
+  if [[ ! "${sort_by}" =~ ^(id|appname)$ ]]; then
+    echo 'Invalid sorting field'
+    return 2
+  fi
+
+  if [[ -n "${order}" ]] && [[ ! "${order}" =~ ^(asc|desc)$ ]]; then
+    echo 'Invalid ordering value'
+    return 2
+  fi
+
+  local query=''
+  query+='ID:       \(.id.data)\n'
+  query+='App:      \(.appname.data)'
+  query+='\(.summary.data|if . and . != "" then "\nSummary:  \(.)" else "" end)'
+  query+='\(.body.data|if . and . != "" then "\nBody:     \(.)" else "" end)'
+  query="[.[]|\"${query}\"]|join(\"\n\n\")"
+
+  find_archived "${sort_by}" "${order}" | jq -cer "${query}" || return 1
+}
+
 # Pauses the notification stream.
 # Arguments:
 #  None
@@ -113,10 +166,13 @@ show_help () {
   echo "Usage: COMMAND [OBJECT] [ARGUMENTS]..."
 
   echo -e "\nCOMMANDS"
-  printf " %-36s %s\n" \
+  printf " %-30s %s\n" \
     "help" "Show this help message." \
     "" "" \
     "show status" "Show the status of notifications." \
+    "" "" \
+    "list [<sort_by> [<order>]]" "List archived notifications sorted by either the" \
+    "" "id or appname in asc or desc order." \
     "" "" \
     "mute" "Pause the notifications stream." \
     "unmute" "Restore the notifications stream."
@@ -151,6 +207,7 @@ loop () {
           "status") show_status;;
           *) echo "Invalid or unknown command";;
         esac;;
+      "list") list_archived "${cmd[1]}" "${cmd[2]}";;
       "mute") mute_stream;;
       "unmute") unmute_stream;;
       *) echo "Invalid or unknown command";; 
