Add cmd to set screen saver via dpms

diff --git a/resources/stack/power b/resources/stack/power
--- a/resources/stack/power
+++ b/resources/stack/power
@@ -55,7 +55,7 @@ prompt () {
 #  A verbose list of text data.
 show_status () {
   local query=''
-  query+='"Adapter:   \(."on-line"|if . then "on" else "off" end)"'
+  query+='"Adapter:      \(."on-line"|if . then "on" else "off" end)"'
 
   find_adapter | jq -cer "${query}" || return 1
 
@@ -64,28 +64,28 @@ show_status () {
 
   if [[ -n "${battery}" ]]; then
     local query=''
-    query+='Battery:   yes\n'
-    query+='State:     \(.state|ascii_downcase)\n'
-    query+='Charge:    \(.charge_percent)%'
-    query+="\(.design_capacity_mah|if . then \"\nCapacity:  \(.)mAh\" else \"\" end)"
+    query+='Battery:      yes\n'
+    query+='State:        \(.state|ascii_downcase)\n'
+    query+='Charge:       \(.charge_percent)%'
+    query+="\(.design_capacity_mah|if . then \"\nCapacity:     \(.)mAh\" else \"\" end)"
     query="\"${query}\""
 
     echo "${battery}" | jq -cer "${query}" || return 1
   else
-    echo "Battery:   no"
+    echo "Battery:      no"
   fi
 
   if [[ -f '/sys/class/power_supply/BAT0/current_now' ]]; then
     local current_now="$(< /sys/class/power_supply/BAT0/current_now)"
-    echo "Current:   ${current_now}mAh"
+    echo "Current:      ${current_now}mAh"
   fi
 
   if [[ -f '/sys/class/power_supply/BAT0/charge_now' ]]; then
     local charge_now="$(< /sys/class/power_supply/BAT0/charge_now)"
-    echo "Load:      ${charge_now}mAh"
+    echo "Load:         ${charge_now}mAh"
   fi
 
-  local query='.[]|select(.unit == "acpid.service")|"ACPID:     \(.active)"'
+  local query='.[]|select(.unit == "acpid.service")|"ACPID:        \(.active)"'
 
   local acpid_status=''
   acpid_status="$(systemctl -a | jc --systemctl | jq -cr "${query}")" || return 1
@@ -94,7 +94,7 @@ show_status () {
     echo "${acpid_status}"
   fi
 
-  local query='.[]|select(.unit == "tlp.service")|"TLP:       \(.active)"'
+  local query='.[]|select(.unit == "tlp.service")|"TLP:          \(.active)"'
 
   local tlp_status=''
   tlp_status="$(systemctl -a | jc --systemctl | jq -cr "${query}")" || return 1
@@ -110,10 +110,21 @@ show_status () {
   if [[ -n "${locker_process}" ]]; then
     echo "${locker_process}" | awk '{
       match($0,/.* -time(.*) -corners.*/,a)
-      print "Locker:   "a[1]" mins"
+      print "Locker:      "a[1]" mins"
     }'
   else
-    echo "Locker:    off"
+    echo "Locker:      off"
+  fi
+
+  local query='.screensaver.interval|if . then . else "" end'
+
+  local screensaver=''
+  screensaver="$(jq -cr "${query}" "${SETTINGS_FILE}")" || return 1
+  
+  if [[ -n "${screensaver}" ]] && [[ ${screensaver} -gt 0 ]]; then
+    echo "Screensaver:  ${screensaver} mins"
+  else
+    echo "Screensaver:  off"
   fi
 
   loginctl show-session | awk '{
@@ -127,7 +138,7 @@ show_status () {
       next
     }
 
-    printf  "%-9s  %s\n", a[1]":", a[2]
+    printf  "%-12s  %s\n", a[1]":", a[2]
   }' || return 1
 
   echo ""
@@ -349,6 +360,96 @@ init_locker () {
   echo "Locker has been set"
 }
 
+# Sets the interval time of the screen saver, where
+# 0 means deactivate the screensaver.
+# Arguments:
+#  mins:    an integer interval in mins or 0
+#  persist: save or nosave, default is save
+set_screensaver () {
+  local mins="${1}"
+  local persist="${2:-"save"}"
+
+  if [[ -z "${mins}" ]]; then
+    echo "Missing the interval time"
+    return 2
+  elif [[ ! "${mins}" =~ ^[0-9]{,2}$ ]]; then
+    echo "Invalid interval time"
+    return 2
+  elif [[ ${mins} -lt 0 ]] || [[ ${mins} -gt 60 ]]; then
+    echo "Interval time out of range [0,60]"
+    return 2
+  fi
+
+  if [[ ${mins} -gt 0 ]]; then
+    local secs=$((mins*60))
+    xset s "${secs}" "${secs}" &> /dev/null
+
+    if [[ $? -ne 0 ]]; then
+      echo "Failed to set the screen saver"
+      return 2
+    fi
+
+    echo "Screen saver set to ${mins} mins"
+  else
+    xset s off &> /dev/null
+
+    if [[ $? -ne 0 ]]; then
+      echo "Failed to disable screen saver"
+      return 2
+    fi
+
+    echo "Screen saver has been disabled"
+  fi
+
+  # Save screen saver interval into settings file
+  if [[ "${persist}" == "save" ]]; then
+    local settings='{}'
+    local screensaver="{\"interval\": \"${mins}\"}"
+
+    if [[ -f "${SETTINGS_FILE}" ]]; then
+      settings="$(jq -e ".screensaver = ${screensaver} " "${SETTINGS_FILE}")" || return 1
+    else
+      settings="$(echo "{\"screensaver\": ${screensaver}}" | jq -e '.')" || return 1
+    fi
+
+    mkdir -p "${CONFIG_HOME}"
+    echo "${settings}" > "${SETTINGS_FILE}"
+  fi
+}
+
+# Initializes the screen saver to settings being set
+# in the settings file.
+# Globals:
+#  SETTINGS_FILE
+# Arguments:
+#  None
+init_screensaver () {
+  if [[ ! -f "${SETTINGS_FILE}" ]]; then
+    echo "No screensaver settings found"
+    return 0
+  fi
+
+  local screensaver=''
+  screensaver="$(jq '.screensaver|if . then . else empty end' "${SETTINGS_FILE}")"
+
+  if [[ -z "${screensaver}" ]]; then
+    echo "No screensaver settings found"
+    return 0
+  fi
+
+  local interval=''
+  interval="$(get "${screensaver}" '.interval')" || return 1
+
+  set_screensaver "${interval}" "nosave"
+
+  if [[ $? -ne 0 ]]; then
+    echo "Failed to set screensaver"
+    return 2
+  fi
+
+  echo "Screensaver has been set"
+}
+
 # Enables power saving mode via the tlp service.
 # Arguments:
 #  None
@@ -525,6 +626,7 @@ show_help () {
       "help" "Show this help message." \
       "" "" \
       "init locker" "Initialize the screen locker." \
+      "init screensaver" "Initialize the screen saver." \
       "" "" \
       "shutdown" "Shut the system down." \
       "reboot" "Reboot the system." \
@@ -549,6 +651,8 @@ show_help () {
     "" "" \
     "set locker <mins>" "Set the interval of the screen locker," \
     "" "where 0 means deactivate the locker." \
+    "set screensaver <mins>" "Set the interval of the screen saver," \
+    "" "where 0 means deactivate the screensaver." \
     "" "" \
     "enable tlp" "Enable the power saving mode." \
     "disable tlp" "Disable the power saving mode." \
@@ -588,6 +692,7 @@ loop () {
         case "${cmd[1]}" in
           "action") set_action "${cmd[2]}" "${cmd[3]}";;
           "locker") set_locker "${cmd[2]}";;
+          "screensaver") set_screensaver "${cmd[2]}";;
           "charge") set_charge "${cmd[2]}" "${cmd[3]}";;
           *) echo "Invalid or unknown command";;
         esac;;
@@ -623,6 +728,7 @@ once () {
     "init")
       case "${2}" in
         "locker") init_locker || abort;;
+        "screensaver") init_screensaver || abort;;
         *) abort "Invalid or unknown command";;
       esac;;
     "shutdown") shutdown_system;;
