Check if output exists and active before any set operation

diff --git a/resources/stack/screens b/resources/stack/screens
--- a/resources/stack/screens
+++ b/resources/stack/screens
@@ -63,6 +63,42 @@ get_outputs () {
   echo "$OUTPUTS"
 }
 
+exists () {
+  local OUTPUT=$1
+
+  local SCREEN=$(get_screen 0 || echo "err:$?")
+
+  if [[ "$SCREEN" =~ ^err: ]]; then
+    return 1
+  fi
+
+  local HEAD=$(echo "$SCREEN" | awk "/^${OUTPUT} /")
+
+  [ -n "$HEAD" ] && return 0 || return 1
+}
+
+is_active () {
+  local OUTPUT=$1
+
+  local SCREEN=$(get_screen 0 || echo "err:$?")
+
+  if [[ "$SCREEN" =~ ^err: ]]; then
+    return 1
+  fi
+
+  local HEAD=$(echo "$SCREEN" | awk "/^${OUTPUT} /")
+
+  if [ -z "$HEAD" ]; then
+    return 1
+  fi
+
+  local STATUS="$(echo "$HEAD" | awk 'match($0, /.* ((dis)?connected) .*/, a) {print a[1]}')"
+  local RESOLUTION="$(echo "$HEAD" | awk 'match($0, /.* ([0-9]+x[0-9]+)\+.*/, a) {print a[1]}')"
+
+  [ "$STATUS" = "connected" ] && [ -n "$RESOLUTION" ] &&
+    return 0 || return 1
+}
+
 pick_output () {
   local OUTPUTS=$(get_outputs | awk '{print NR-1"|"$0"|"$0}' || echo "err:$?")
   
@@ -286,6 +322,14 @@ set_mode () {
     return 1
   fi
 
+  if ! exists "$OUTPUT"; then
+    echo "Unable to find output: '$OUTPUT'"
+    return 1
+  elif ! is_active "$OUTPUT"; then
+    echo "Unable to set mode of an inactive output"
+    return 1
+  fi
+
   xrandr --output "$OUTPUT" --mode "$RESOLUTION" --rate "$RATE" ||
     echo "Unable to set resolution"
 }
@@ -298,6 +342,14 @@ restore () {
     return 1
   fi
 
+  if ! exists "$OUTPUT"; then
+    echo "Unable to find output: '$OUTPUT'"
+    return 1
+  elif ! is_active "$OUTPUT"; then
+    echo "Unable to restore an inactive output"
+    return 1
+  fi
+
   xrandr --output "$OUTPUT" --auto ||
     echo "Unable to restore the output resolution"
 }
@@ -307,6 +359,14 @@ set_primary () {
 
   if [ -z "$OUTPUT" ]; then
     echo "Missing the output argument"
+    return 1
+  fi
+
+  if ! exists "$OUTPUT"; then
+    echo "Unable to find output: '$OUTPUT'"
+    return 1
+  elif ! is_active "$OUTPUT"; then
+    echo "Unable to set primary an inactive output"
     return 1
   fi
 
