Add cmd to set an output active or inactive

diff --git a/resources/stack/screens b/resources/stack/screens
--- a/resources/stack/screens
+++ b/resources/stack/screens
@@ -374,6 +374,44 @@ set_primary () {
     echo "Unable to set the primary output"
 }
 
+set_active () {
+  local OUTPUT=$1
+  local ACTIVE=$2
+
+  if [ -z "$OUTPUT" ]; then
+    echo "Missing the output argument"
+    return 1
+  fi
+
+  if [[ ! "$ACTIVE" =~ ^(on|off)$ ]]; then
+    echo "Invalid active argument: '$ACTIVE'"
+    return 1
+  fi
+
+  if [ "$ACTIVE" = "on" ] && is_active "$OUTPUT"; then
+    echo "Output is already activate"
+    return 1
+  fi
+
+  if [ "$ACTIVE" = "off" ] && ! is_active "$OUTPUT"; then
+    echo "Output is already inactive"
+    return 1
+  fi
+
+  if ! exists "$OUTPUT"; then
+    echo "Unable to find output: '$OUTPUT'"
+    return 1
+  fi
+
+  if [ "$ACTIVE" = "on" ]; then
+    xrandr --output "$OUTPUT" --auto ||
+      echo "Unable to activate the output"
+  else
+    xrandr --output "$OUTPUT" --off ||
+      echo "Unable to deactivate the output"
+  fi
+}
+
 help () {
   local FRM=" %-28s\t%s\n"
 
@@ -388,6 +426,7 @@ help () {
     "list outputs [[dis]connected]" "List all outputs or by status." \
     "set mode <output> <res> <rate>" "Set the mode of the given output." \
     "set primary <output>" "Set the primary output." \
+    "set active <output> on|off" "Set active or inactive the given output." \
     "restore <output>" "Restore the given output to auto mode."
 
   echo -e "\nOBJECTS"
@@ -395,7 +434,8 @@ help () {
     "status" "The status of xorg server and screen layouts." \
     "output" "An output display device." \
     "mode" "The resolution and rate of an output." \
-    "primary" "The main output in a multihead layout."
+    "primary" "The main output in a multihead layout." \
+    "active" "The status of an output if is active or not."
 }
 
 loop () {
@@ -437,6 +477,7 @@ loop () {
         case "${CMD[1]}" in
           "mode") set_mode "${CMD[2]}" "${CMD[3]}" "${CMD[4]}";;
           "primary") set_primary "${CMD[2]}";;
+          "active") set_active "${CMD[2]}" "${CMD[3]}";;
           *) echo "Unknown or invalid command: '$REPLY'";;
         esac;;
       "restore") restore "${CMD[1]}";;
