Add cmd to show the data of a screen output display

diff --git a/resources/stack/screens b/resources/stack/screens
--- a/resources/stack/screens
+++ b/resources/stack/screens
@@ -31,6 +31,34 @@ show_status () {
   }'
 }
 
+show_output () {
+  local OUTPUT=$1
+
+  if [ -z "$OUTPUT" ]; then
+    echo "Missing the output argument"
+    return 1
+  fi
+
+  local SCREEN=$(xrandr --current | sed '/^Screen 0:/,/^Screen/!d;//d' || echo "err:$?")
+
+  if [[ "$SCREEN" =~ ^err: ]]; then
+    echo "Unable to find the default screen"
+    return 1
+  fi
+
+  local OUTPUTS=($(echo "$SCREEN" | awk '/^[A-Z]/{print $1}'))
+
+  if ! contains "$OUTPUT" "${OUTPUTS[@]}"; then
+    echo "Unable to find output: '$OUTPUT'"
+    return 1
+  fi
+
+  echo "$SCREEN" | awk /^$OUTPUT/
+  echo "$SCREEN" |
+    awk /^$OUTPUT/,!// | tail -n +2 |
+    awk '{if ($0 ~ /^\s+[0-9]+x[0-9]+/) {print} else {exit}}' 
+}
+
 help () {
   local FRM=" %-28s\t%s\n"
 
@@ -39,11 +67,13 @@ help () {
   echo -e "\nCOMMANDS"
   printf "$FRM" \
     "help" "Show this help message." \
-    "show status" "Show a report of all screen layouts."
+    "show status" "Show a report of all screen layouts." \
+    "show output <output>" "Show the data of the given output."
 
   echo -e "\nOBJECTS"
   printf "$FRM" \
-    "status" "The status of all screen layouts."
+    "status" "The status of all screen layouts." \
+    "output" "An output display device."
 }
 
 loop () {
@@ -73,6 +103,7 @@ loop () {
       "show")
         case "${CMD[1]}" in
           "status") show_status;;
+          "output") show_output "${CMD[2]}";;
           *) echo "Unknown or invalid command: '$REPLY'";;
         esac;;
       *) echo "Unknown or invalid command: '$REPLY'";; 
