Before any sudo cmd authenticate user password

diff --git a/resources/stack/security b/resources/stack/security
--- a/resources/stack/security
+++ b/resources/stack/security
@@ -241,7 +241,16 @@ set_faillock_attempts () {
     return 2
   fi
 
-  sudo sed -ri "s;deny =.*;deny = ${attempts};" /etc/security/faillock.conf
+  ask_secret "Enter current password:"
+  local password="${REPLY}"
+
+  if ! authenticate_user "${password}"; then
+    echo 'Incorrect or invalid password'
+    return 2
+  fi
+
+  echo "${password}" |
+    sudo --stdin sed -ri "s;deny =.*;deny = ${attempts};" /etc/security/faillock.conf
 
   if [[ $? -ne 0 ]]; then
     echo 'Unable to set faillock attempts'
@@ -269,7 +278,16 @@ set_faillock_unblock () {
     return 2
   fi
 
-  sudo sed -ri "s;unlock_time =.*;unlock_time = ${time};" /etc/security/faillock.conf
+  ask_secret "Enter current password:"
+  local password="${REPLY}"
+
+  if ! authenticate_user "${password}"; then
+    echo 'Incorrect or invalid password'
+    return 2
+  fi
+
+  echo "${password}" |
+    sudo --stdin sed -ri "s;unlock_time =.*;unlock_time = ${time};" /etc/security/faillock.conf
 
   if [[ $? -ne 0 ]]; then
     echo 'Unable to set faillock unblock time'
@@ -298,7 +316,16 @@ set_faillock_interval () {
     return 2
   fi
 
-  sudo sed -ri "s;fail_interval =.*;fail_interval = ${time};" /etc/security/faillock.conf
+  ask_secret "Enter current password:"
+  local password="${REPLY}"
+
+  if ! authenticate_user "${password}"; then
+    echo 'Incorrect or invalid password'
+    return 2
+  fi
+
+  echo "${password}" |
+    sudo --stdin sed -ri "s;fail_interval =.*;fail_interval = ${time};" /etc/security/faillock.conf
 
   if [[ $? -ne 0 ]]; then
     echo 'Unable to set faillock interval'
