Add cmd to set the password unlock time via faillock

diff --git a/resources/stack/security b/resources/stack/security
--- a/resources/stack/security
+++ b/resources/stack/security
@@ -215,8 +215,8 @@ logout_user () {
   fi
 }
 
-# Sets the number of password attempts a user allowed
-# to submit before he is locked out.
+# Sets the number of failed password attempts a user
+# allowed to submit before he is password is locked.
 # Arguments:
 #  attempts: a positive integer number
 set_password_attempts () {
@@ -241,6 +241,33 @@ set_password_attempts () {
   fi
 
   echo "Password attempts set to ${attempts}"
+}
+
+# Sets the time to wait before unlock the password.
+# Arguments:
+#  time: the number of secs to keep password locked
+set_password_unlock () {
+  local time="${1}"
+
+  if [[ -z "${time}" ]]; then
+    echo "Missing the unlock time value"
+    return 2
+  elif [[ ! "${time}" =~ ^[1-9][0-9]*$ ]]; then
+    echo "Invalid unlock time value"
+    return 2
+  elif [[ ! ${time} -gt 0 ]]; then
+    echo "Unlock time should be greater than 0"
+    return 2
+  fi
+
+  sudo sed -ri "s;unlock_time =.*;unlock_time = ${time};" /etc/security/faillock.conf
+
+  if [[ $? -ne 0 ]]; then
+    echo 'Unable to set password unlock time'
+    return 2
+  fi
+
+  echo "Password unlock time set to ${time}"
 }
 
 # Shows the help message.
@@ -274,8 +301,10 @@ show_help () {
     "" "" \
     "set locker <mins>" "Set the interval of the screen locker," \
     "" "where 0 means deactivate the locker." \
+    "" "" \
     "set password" "Change the user password." \
-    "set password_attempts <attempts>" "Set the failed password attempts."
+    "set password_attempts <attempts>" "Set the failed password attempts." \
+    "set password_unlock <secs>" "Set the time to wait before password unlock."
 }
 
 loop () {
@@ -312,6 +341,7 @@ loop () {
           "locker") set_locker "${cmd[2]}";;
           "password") set_password;;
           "password_attemps") set_password_attempts "${cmd[2]}";;
+          "password_unlock") set_password_unlock "${cmd[2]}";;
           *) echo "Invalid or unknown command";;
         esac;;
       *) echo "Invalid or unknown command";; 
