Catch extraction failures during theme installation

diff --git a/resources/stack/theme b/resources/stack/theme
--- a/resources/stack/theme
+++ b/resources/stack/theme
@@ -174,6 +174,11 @@ install_theme () {
     sudo tar -xf "$ARCHIVE" --directory "$THEMES_HOME"
   fi
 
+  if [ ! $? = 0 ]; then
+    echo "Failed to install theme"
+    return 1
+  fi
+
   if [ ! "$ROOT" = "$NAME" ]; then
     sudo mv "$THEMES_HOME/$ROOT" "$THEMES_HOME/$NAME"
   fi
