Use single quotes for text without interpolation

diff --git a/tools/audio/commands b/tools/audio/commands
--- a/tools/audio/commands
+++ b/tools/audio/commands
@@ -38,7 +38,7 @@ show_status () {
   query+=' else ."device.alias" end'
   query="[${query}]|join(\"\n           \")"
 
-  echo -n "Cards:     "
+  echo -n 'Cards:     '
   find_cards | jq -cer "${query}" || return 1
 
   local sink=''
@@ -85,7 +85,7 @@ show_card () {
   local index="${1}"
 
   if [[ -z "${index}" ]]; then
-    pick_card "Select an audio card:" || return $?
+    pick_card 'Select an audio card:' || return $?
     [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
   fi
 
@@ -113,14 +113,14 @@ show_card () {
   query='.profiles|[keys[]]|join("\n           ")'
 
   echo
-  echo -n "Profiles:  "
+  echo -n 'Profiles:  '
   echo "${card}" | jq -cer "${query}" || return 1
 
   local query=''
   query='[.ports|to_entries[]|"\(.key) [\(.value.type)]"]|join("\n           ")'
 
   echo
-  echo -n "Ports:     "
+  echo -n 'Ports:     '
   echo "${card}" | jq -cr "${query}" || return 1
 }
 
@@ -128,21 +128,21 @@ show_card () {
 # Arguments:
 #  none
 restart () {
-  echo "Restarting the audio server..."
+  echo 'Restarting the audio server...'
 
   systemctl --user restart pipewire.socket && sleep 0.5 &&
-    echo "Pipewire socket restarted" &&
+    echo 'Pipewire socket restarted' &&
   systemctl --user restart pipewire.service && sleep 0.5 &&
-    echo "Pipewire service restarted" &&
+    echo 'Pipewire service restarted' &&
   systemctl --user restart pipewire-session-manager.service && sleep 0.5 &&
   systemctl --user restart pipewire-media-session.service && sleep 0.5 &&
   systemctl --user restart pipewire-pulse.socket && sleep 0.5 &&
-    echo "Pulse socket restarted" &&
+    echo 'Pulse socket restarted' &&
   systemctl --user restart pipewire-pulse.service && sleep 0.5 &&
-    echo "Pulse service restarted" &&
-  echo "Audio server has been restarted" &&
+    echo 'Pulse service restarted' &&
+  echo 'Audio server has been restarted' &&
   (~/.config/polybar/launch &> /dev/null &) ||
-    echo "An error occurred restarting the audio server"
+    echo 'An error occurred restarting the audio server'
 }
 
 # Shows the list of all audio cards of the system.
@@ -155,7 +155,7 @@ list_cards () {
   cards="$(find_cards)"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read audio cards"
+    echo 'Unable to read audio cards'
     return 2
   fi
 
@@ -163,7 +163,7 @@ list_cards () {
   len="$(count "${cards}")" || return 1
 
   if [[ ${len} == 0 ]]; then
-    echo "No audio cards have found"
+    echo 'No audio cards have found'
     return 0
   fi
 
@@ -186,7 +186,7 @@ list_ports () {
   local type="${1}"
 
   if [[ ! "${type}" =~ ^(sink|source)$ ]]; then
-    echo "Invalid module type value"
+    echo 'Invalid module type value'
     return 2
   fi
 
@@ -196,7 +196,7 @@ list_ports () {
   modules="$(pactl --format=json list "${type}"s | jq -cer "${query}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read $(label "type" "${type}") modules"
+    echo "Unable to read $(label type "${type}") modules"
     return 2
   fi
 
@@ -204,7 +204,7 @@ list_ports () {
   len="$(count "${modules}")" || return 1
 
   if [[ ${len} == 0 ]]; then
-    echo "No $(label "type" "${type}") modules have found"
+    echo "No $(label type "${type}") modules have found"
     return 0
   fi
 
@@ -246,7 +246,7 @@ list_playbacks () {
   sink_inputs="$(pactl --format=json list sink-inputs | jq -cer "${query}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read playback streams"
+    echo 'Unable to read playback streams'
     return 2
   fi
 
@@ -254,7 +254,7 @@ list_playbacks () {
   len="$(count "${sink_inputs}")" || return 1
 
   if [[ ${len} == 0 ]]; then
-    echo "No playbacks have found"
+    echo 'No playbacks have found'
     return 0
   fi
 
@@ -282,7 +282,7 @@ set_profile () {
   local name="${2}"
 
   if [[ -z "${index}" ]]; then
-    pick_card "Select an audio card:" || return $?
+    pick_card 'Select an audio card:' || return $?
     [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
   fi
 
@@ -295,7 +295,7 @@ set_profile () {
   fi
 
   if [[ -z "${name}" ]]; then
-    pick_profile "Select a profile:" "${card}" || return $?
+    pick_profile 'Select a profile:' "${card}" || return $?
     [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
   fi
 
@@ -303,14 +303,14 @@ set_profile () {
   exists="$(echo "${card}" | jq -cer ".profiles|has(\"${name}\")")"
 
   if [[ "${exists}" == "false" ]]; then
-    echo "Invalid profile name value"
+    echo 'Invalid profile name value'
     return 2
   fi
 
   pactl set-card-profile "${index}" "${name}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set profile"
+    echo 'Failed to set profile'
     return 2
   fi
   
@@ -326,12 +326,12 @@ set_default () {
   local index="${2}"
 
   if [[ ! "${type}" =~ ^(sink|source)$ ]]; then
-    echo "Invalid module type value"
+    echo 'Invalid module type value'
     return 2
   fi
 
   if [[ -z "${index}" ]]; then
-    pick_module "Select an audio module:" "${type}" || return $?
+    pick_module 'Select an audio module:' "${type}" || return $?
     [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
   fi
 
@@ -341,18 +341,18 @@ set_default () {
   exists="$(pactl --format=json list "${type}"s | jq -cer "${query}")"
 
   if [[ -z "${exists}" ]]; then
-    echo "Invalid module index value"
+    echo 'Invalid module index value'
     return 2
   fi
 
   pactl set-default-${type} "${index}"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set active $(label "type" "${type}")"
+    echo "Failed to set active $(label type "${type}")"
     return 2
   fi
 
-  echo "Active $(label "type" "${type}") set to module ${index}"
+  echo "Active $(label type "${type}") set to module ${index}"
 }
 
 # Sets the volume of the active sink or source
@@ -366,15 +366,15 @@ turn_default () {
   local to="${2}"
 
   if [[ ! "${type}" =~ ^(sink|source)$ ]]; then
-    echo "Invalid module type value"
+    echo 'Invalid module type value'
     return 2
   fi
 
   if [[ ! "${to}" =~ ^(up|down|mute|unmute|[0-9]+)$ ]]; then
-    echo "Invalid volume value"
+    echo 'Invalid volume value'
     return 2
   elif [[ "${to}" =~ ^[0-9]+$ ]] && ! ((${to} >= 0 && ${to} <= 150)); then
-    echo "Volume value is out of range"
+    echo 'Volume value is out of range'
     return 2
   fi
 
@@ -382,7 +382,7 @@ turn_default () {
   module="$(pactl get-default-${type})"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read the active $(label "type" "${type}")"
+    echo "Unable to read the active $(label type "${type}")"
     return 2
   fi
   
@@ -390,39 +390,39 @@ turn_default () {
     pactl set-${type}-mute "${module}" 1
 
     if [[ $? -ne 0 ]]; then
-      echo "Failed to set active $(label "type" "${type}") to mute"
+      echo "Failed to set active $(label type "${type}") to mute"
       return 2
     fi
 
-    echo "Active $(label "type" "${type}") volume set to mute" && return 0
+    echo "Active $(label type "${type}") volume set to mute" && return 0
   elif [[ "${to}" == "unmute" ]]; then
     pactl set-${type}-mute "${module}" 0
 
     if [[ $? -ne 0 ]]; then
-      echo "Failed to set active $(label "type" "${type}") to unmute"
+      echo "Failed to set active $(label type "${type}") to unmute"
       return 2
     fi
 
-    echo "Active $(label "type" "${type}") volume set to unmute" && return 0
+    echo "Active $(label type "${type}") volume set to unmute" && return 0
   fi
 
   local volume="${to}"
 
   if [[ "${to}" == "up" ]]; then
-    volume="+5"
+    volume='+5'
   elif [[ "${to}" == "down" ]]; then
-    volume="-5"
+    volume='-5'
   fi
 
   pactl set-${type}-mute "${module}" 0 &&
   pactl set-${type}-volume "${module}" "${volume}%"
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set volume of active $(label "type" "${type}")"
+    echo "Failed to set volume of active $(label type "${type}")"
     return 2
   fi
 
-  echo "Active $(label "type" "${type}") volume set to ${volume}%"
+  echo "Active $(label type "${type}") volume set to ${volume}%"
 }
 
 # Sets all sink or source modules to mute or unmute mode.
@@ -434,12 +434,12 @@ set_mute () {
   local mode="${2}"
 
   if [[ ! "${type}" =~ ^(sink|source)$ ]]; then
-    echo "Invalid module type value"
+    echo 'Invalid module type value'
     return 2
   fi
 
   if [[ ! "${mode}" =~ ^(1|0)$ ]]; then
-    echo "Invalid mute mode value"
+    echo 'Invalid mute mode value'
     return 2
   fi
 
@@ -452,12 +452,12 @@ set_mute () {
   pactl_cmds="$(pactl --format=json list "${type}"s | jq -cer "${query}")"
 
   if [[ $? -ne 0 ]]; then
-    echo "Unable to read $(label "type" "${type}") modules"
+    echo "Unable to read $(label type "${type}") modules"
     return 2
   fi
 
   if [[ -z "${pactl_cmds}" ]]; then
-    echo "No $(label "type" "${type}") modules have found"
+    echo "No $(label type "${type}") modules have found"
     return 0
   fi
 
@@ -474,10 +474,10 @@ set_mute () {
   done <<< "${pactl_cmds}"
 
   if [[ "${failed}" == "true" ]]; then
-    echo "Failed to set mute mode for all $(label "type" "${type}") modules"
+    echo "Failed to set mute mode for all $(label type "${type}") modules"
     return 2
   fi
 
-  echo "All $(label "type" "${type}") modules set to $(label "mute" "${mode}")"
+  echo "All $(label type "${type}") modules set to $(label mute "${mode}")"
 }
 
