Beep success only to certain update actions
Reduce beep sounds that could overwhelm user attention and reactions.
The beep success sound should only be triggered to certain update actions.

diff --git a/tools/audio/commands b/tools/audio/commands
--- a/tools/audio/commands
+++ b/tools/audio/commands
@@ -86,7 +86,7 @@ show_card () {
 
   if [[ -z "${index}" ]]; then
     pick_card 'Select an audio card:' || return $?
-    [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
+    index="${REPLY}"
   fi
 
   local card=''
@@ -128,21 +128,32 @@ show_card () {
 # Arguments:
 #  none
 restart () {
-  echo 'Restarting the audio server...'
+  echo 'Restarting audio services...'
 
-  systemctl --user restart pipewire.socket && sleep 0.5 &&
+  systemctl --user restart pipewire.socket &&
+    sleep 0.5 &&
     echo 'Pipewire socket restarted' &&
-  systemctl --user restart pipewire.service && sleep 0.5 &&
+  systemctl --user restart pipewire.service &&
+    sleep 0.5 &&
     echo 'Pipewire service restarted' &&
-  systemctl --user restart pipewire-session-manager.service && sleep 0.5 &&
-  systemctl --user restart pipewire-media-session.service && sleep 0.5 &&
-  systemctl --user restart pipewire-pulse.socket && sleep 0.5 &&
+  systemctl --user restart pipewire-session-manager.service &&
+    sleep 0.5 &&
+  systemctl --user restart pipewire-media-session.service &&
+    sleep 0.5 &&
+  systemctl --user restart pipewire-pulse.socket &&
+    sleep 0.5 &&
     echo 'Pulse socket restarted' &&
-  systemctl --user restart pipewire-pulse.service && sleep 0.5 &&
+  systemctl --user restart pipewire-pulse.service &&
+    sleep 0.5 &&
     echo 'Pulse service restarted' &&
-  echo 'Audio server has been restarted' &&
-  (~/.config/polybar/launch &> /dev/null &) ||
-    echo 'An error occurred restarting the audio server'
+  (~/.config/polybar/launch &> /dev/null &)
+
+  if [[ $? -ne 0 ]]; then
+    echo 'Failed to restart audio services'
+    return 2
+  fi
+
+  echo 'Audio services has been restarted'
 }
 
 # Shows the list of all audio cards of the system.
@@ -283,7 +294,7 @@ set_profile () {
 
   if [[ -z "${index}" ]]; then
     pick_card 'Select an audio card:' || return $?
-    [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
+    index="${REPLY}"
   fi
 
   local card=''
@@ -296,7 +307,7 @@ set_profile () {
 
   if [[ -z "${name}" ]]; then
     pick_profile 'Select a profile:' "${card}" || return $?
-    [[ -n "${REPLY}" ]] && name="${REPLY}" || return 0
+    name="${REPLY}"
   fi
 
   local exists=''
@@ -332,7 +343,7 @@ set_default () {
 
   if [[ -z "${index}" ]]; then
     pick_module 'Select an audio module:' "${type}" || return $?
-    [[ -n "${REPLY}" ]] && index="${REPLY}" || return 0
+    index="${REPLY}"
   fi
 
   local query=".[]|select(.index|tostring == \"${index}\")"
@@ -394,7 +405,8 @@ turn_default () {
       return 2
     fi
 
-    echo "Active $(label type "${type}") volume set to mute" && return 0
+    echo "Active $(label type "${type}") volume set to mute"
+    return 0
   elif [[ "${to}" == "unmute" ]]; then
     pactl set-${type}-mute "${module}" 0
 
@@ -403,7 +415,8 @@ turn_default () {
       return 2
     fi
 
-    echo "Active $(label type "${type}") volume set to unmute" && return 0
+    echo "Active $(label type "${type}") volume set to unmute"
+    return 0
   fi
 
   local volume="${to}"
diff --git a/tools/audio/main b/tools/audio/main
--- a/tools/audio/main
+++ b/tools/audio/main
@@ -49,7 +49,7 @@ show_help () {
     'mute outputs|inputs' 'Mute all outputs or inputs.' \
     'unmute outputs|inputs' 'Unmute all outputs or inputs.' \
     '' '' \
-    'restart' 'Restart the audio server.'
+    'restart' 'Restart the audio services.'
 }
 
 run () {
@@ -62,7 +62,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -109,19 +110,19 @@ run () {
       'list outputs') list_ports sink;;
       'list inputs') list_ports source;;
       'list playbacks') list_playbacks "${args[2]}";;
-      'set profile') set_profile "${args[2]}" "${args[3]}";;
-      'set ouptut') set_default sink "${args[2]}";;
-      'set input') set_default source "${args[2]}";;
-      'turn output') turn_default sink "${args[2]}";;
-      'turn input') turn_default source "${args[2]}";;
-      'mute outputs') set_mute sink 1;;
-      'mute inputs') set_mute source 1;;
-      'unmute outputs') set_mute sink 0;;
-      'unmute inputs') set_mute source 0;;
+      'set profile') set_profile "${args[2]}" "${args[3]}" && beep;;
+      'set output') set_default sink "${args[2]}" && beep;;
+      'set input') set_default source "${args[2]}" && beep;;
+      'turn output') turn_default sink "${args[2]}" && beep;;
+      'turn input') turn_default source "${args[2]}" && beep;;
+      'mute outputs') set_mute sink 1 && beep;;
+      'mute inputs') set_mute source 1 && beep;;
+      'unmute outputs') set_mute sink 0 && beep;;
+      'unmute inputs') set_mute source 0 && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/bluetooth/main b/tools/bluetooth/main
--- a/tools/bluetooth/main
+++ b/tools/bluetooth/main
@@ -64,7 +64,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -109,19 +110,19 @@ run () {
       'show device') show_device "${args[2]}";;
       'list controllers') list_controllers;;
       'list devices') list_devices "${args[2]}";;
-      'set controller') set_controller "${args[2]}";;
-      'set power') set_power "${args[2]}";;
-      'set scan') set_scan "${args[2]}";;
-      'set discoverable') set_discoverable "${args[2]}";;
-      'set pairable') set_pairable "${args[2]}";;
-      'connect device') connect_device "${args[2]}";;
-      'disconnect device') disconnect_device "${args[2]}";;
-      'remove device') remove_device "${args[2]}";;
+      'set controller') set_controller "${args[2]}" && beep;;
+      'set power') set_power "${args[2]}" && beep;;
+      'set scan') set_scan "${args[2]}" && beep;;
+      'set discoverable') set_discoverable "${args[2]}" && beep;;
+      'set pairable') set_pairable "${args[2]}" && beep;;
+      'connect device') connect_device "${args[2]}" && beep;;
+      'disconnect device') disconnect_device "${args[2]}" && beep;;
+      'remove device') remove_device "${args[2]}" && beep;;
       'restart') restart_bluetooth;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/clock/main b/tools/clock/main
--- a/tools/clock/main
+++ b/tools/clock/main
@@ -53,7 +53,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -93,16 +94,16 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'show status') show_status;;
-      'set ntp') set_ntp "${args[2]}";;
-      'set timezone') set_timezone "${args[2]}";;
-      'set time') set_time "${args[2]}";;
-      'set date') set_date "${args[2]}";;
-      'set rtc') set_rtc "${args[2]}";;
-      'sync rtc') sync_rtc;;
+      'set ntp') set_ntp "${args[2]}" && beep;;
+      'set timezone') set_timezone "${args[2]}" && beep;;;
+      'set time') set_time "${args[2]}" && beep;;;
+      'set date') set_date "${args[2]}" && beep;;;
+      'set rtc') set_rtc "${args[2]}" && beep;;;
+      'sync rtc') sync_rtc && beep;;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/cloud/main b/tools/cloud/main
--- a/tools/cloud/main
+++ b/tools/cloud/main
@@ -51,7 +51,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -91,16 +92,16 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'list remotes') list_remotes "${args[2]}";;
-      'sync remote drive') sync_drive "${args[3]}";;
-      'sync remote dropbox') sync_dropbox "${args[3]}";;
-      'delete remote') delete_remote "${args[2]}";;
-      'mount  remote') mount_remote "${args[2]}";;
-      'unmount remote') unmount_remote "${args[2]}";;
-      'mount remotes') mount_all;;
+      'sync remote drive') sync_drive "${args[3]}" && beep;;
+      'sync remote dropbox') sync_dropbox "${args[3]}" && beep;;
+      'delete remote') delete_remote "${args[2]}" && beep;;
+      'mount remote') mount_remote "${args[2]}" && beep;;
+      'unmount remote') unmount_remote "${args[2]}" && beep;;
+      'mount remotes') mount_all && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/desktop/main b/tools/desktop/main
--- a/tools/desktop/main
+++ b/tools/desktop/main
@@ -64,7 +64,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -106,20 +107,20 @@ run () {
       'show status') show_status;;
       'show pointer') show_pointer "${args[2]}";;
       'show tablet') show_tablet "${args[2]}";;
-      'set wallpaper') set_wallpaper "${args[2]}" "${args[3]}";;
-      'speed pointer') set_pointer_speed "${args[2]}";;
-      'scale tablet') scale_tablet "${args[2]}" "${args[3]}";;
-      'map tablet') map_tablet "${args[2]}" "${args[3]}";;
+      'set wallpaper') set_wallpaper "${args[2]}" "${args[3]}" && beep;;
+      'speed pointer') set_pointer_speed "${args[2]}" && beep;;
+      'scale tablet') scale_tablet "${args[2]}" "${args[3]}" && beep;;
+      'map tablet') map_tablet "${args[2]}" "${args[3]}" && beep;;
       'list wallpapers') list_wallpapers;;
       'list pointers') list_pointers;;
       'list tablets') list_tablets;;
-      'init pointer') init_pointer;;
-      'init tablets') init_tablets;;
-      'init wallpaper') init_wallpaper;;
+      'init pointer') init_pointer && beep;;
+      'init tablets') init_tablets && beep;;
+      'init wallpaper') init_wallpaper && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/disks/main b/tools/disks/main
--- a/tools/disks/main
+++ b/tools/disks/main
@@ -70,7 +70,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -118,23 +119,23 @@ run () {
       'show disk') show_disk "${args[2]}";;
       'show partition') show_partition "${args[2]}";;
       'show rom') show_rom "${args[2]}";;
-      'mount partition') mount_partition "${args[2]}";;
-      'mount rom') mount_rom "${args[2]}";;
-      'mount image') mount_image "${args[2]}";;
-      'mount folder') mount_shared_folder "${args[2]}";;
-      'unmount partition') unmount_partition "${args[2]}";;
-      'unmount rom') unmount_rom "${args[2]}";;
-      'unmount image') unmount_image "${args[2]}";;
-      'unmount folder') unmount_shared_folder "${args[2]}";;
-      'format disk') format_disk "${args[2]}";;
-      'eject disk') eject_disk "${args[2]}";;
-      'scan disk') scan_disk "${args[2]}";;
-      'create encrypted') create_encrypted "${args[2]}";;
-      'create bootable') create_bootable "${args[2]}";;
+      'mount partition') mount_partition "${args[2]}" && beep;;
+      'mount rom') mount_rom "${args[2]}" && beep;;
+      'mount image') mount_image "${args[2]}" && beep;;
+      'mount folder') mount_shared_folder "${args[2]}" && beep;;
+      'unmount partition') unmount_partition "${args[2]}" && beep;;
+      'unmount rom') unmount_rom "${args[2]}" && beep;;
+      'unmount image') unmount_image "${args[2]}" && beep;;
+      'unmount folder') unmount_shared_folder "${args[2]}" && beep;;
+      'format disk') format_disk "${args[2]}" && beep;;
+      'eject disk') eject_disk "${args[2]}" && beep;;
+      'scan disk') scan_disk "${args[2]}" && beep;;
+      'create encrypted') create_encrypted "${args[2]}" && beep;;
+      'create bootable') create_bootable "${args[2]}" && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/displays/main b/tools/displays/main
--- a/tools/displays/main
+++ b/tools/displays/main
@@ -70,7 +70,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -115,26 +116,26 @@ run () {
       'list outputs') list_outputs "${args[2]}";;
       'list colors') list_colors;;
       'list layouts') list_layouts;;
-      'set layout') set_layout;;
-      'set mode') set_mode "${args[2]}" "${args[3]}" "${args[4]}";;
-      'set primary') set_primary "${args[2]}";;
-      'set on') set_on "${args[2]}";;
-      'set off') set_off "${args[2]}";;
-      'set color') set_color "${args[2]}" "${args[3]}";;
-      'reset color') reset_color "${args[2]}";;
-      'save layout') save_layout;;
-      'delete layout') delete_layout "${args[2]}";;
-      'delete color') delete_color "${args[2]}";;
-      'restore layout') restore_layout;;
-      'restore colors') restore_colors;;
-      'rotate output') rotate_output "${args[2]}" "${args[3]}";;
-      'reflect output') reflect_output "${args[2]}" "${args[3]}";;
-      'mirror_output') mirror_output "${args[2]}";;
-      'fix layout') fix_layout;;
+      'set layout') set_layout && beep;;
+      'set mode') set_mode "${args[2]}" "${args[3]}" "${args[4]}" && beep;;
+      'set primary') set_primary "${args[2]}" && beep;;
+      'set on') set_on "${args[2]}" && beep;;
+      'set off') set_off "${args[2]}" && beep;;
+      'set color') set_color "${args[2]}" "${args[3]}" && beep;;
+      'reset color') reset_color "${args[2]}" && beep;;
+      'save layout') save_layout && beep;;
+      'delete layout') delete_layout "${args[2]}" && beep;;
+      'delete color') delete_color "${args[2]}" && beep;;
+      'restore layout') restore_layout && beep;;
+      'restore colors') restore_colors && beep;;
+      'rotate output') rotate_output "${args[2]}" "${args[3]}" && beep;;
+      'reflect output') reflect_output "${args[2]}" "${args[3]}" && beep;;
+      'mirror_output') mirror_output "${args[2]}" && beep;;
+      'fix layout') fix_layout && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/langs/main b/tools/langs/main
--- a/tools/langs/main
+++ b/tools/langs/main
@@ -60,7 +60,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -100,20 +101,20 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'show status') show_status;;
-      'set keymap') set_keymap "${args[2]}";;
-      'set language') set_language "${args[2]}";;
-      'set locale') set_locale "${args[2]}" "${args[3]}";;
-      'set options') set_options "${args[2]}";;
-      'set model') set_model "${args[2]}";;
-      'add locale') add_locale "${args[2]}";;
-      'add layout') add_layout "${args[2]}";;
-      'remove locale') remove_locale "${args[2]}";;
-      'remove layout') remove_layout "${args[2]}";;
-      'order layouts') order_layouts;;
+      'set keymap') set_keymap "${args[2]}" && beep;;
+      'set language') set_language "${args[2]}" && beep;;
+      'set locale') set_locale "${args[2]}" "${args[3]}" && beep;;
+      'set options') set_options "${args[2]}" && beep;;
+      'set model') set_model "${args[2]}" && beep;;
+      'add locale') add_locale "${args[2]}" && beep;;
+      'add layout') add_layout "${args[2]}" && beep;;
+      'remove locale') remove_locale "${args[2]}" && beep;;
+      'remove layout') remove_layout "${args[2]}" && beep;;
+      'order layouts') order_layouts && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/networks/main b/tools/networks/main
--- a/tools/networks/main
+++ b/tools/networks/main
@@ -68,7 +68,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -114,25 +115,25 @@ run () {
       'list connections') list_connections;;
       'list wifis') list_wifis "${args[2]}" "${args[3]}";;
       'list proxies') list_proxies;;
-      'power network') power_network "${args[2]}";;
-      'power wifi') power_wifi "${args[2]}";;
-      'up device') up device "${args[2]}";;
-      'down device') down device "${args[2]}";;
-      'up connection') up connection "${args[2]}";;
-      'down connection') down connection "${args[2]}";;
-      'add connection eth') add_ethernet_connection;;
-      'add connection wifi') add_wifi_connection;;
-      'add connection vpn') add_vpn_connection;;
-      'add proxy') add_proxy "${args[2]}";;
-      'remove device') remove_device "${args[2]}";;
-      'remove connection') remove_connection "${args[2]}";;
-      'remove proxy') remove_proxy "${args[2]}";;
-      'set proxy') set_proxy "${args[2]}";;
-      'unset proxy') unset_proxy;;
+      'power network') power_network "${args[2]}" && beep;;
+      'power wifi') power_wifi "${args[2]}" && beep;;
+      'up device') up device "${args[2]}" && beep;;
+      'down device') down device "${args[2]}" && beep;;
+      'up connection') up connection "${args[2]}" && beep;;
+      'down connection') down connection "${args[2]}" && beep;;
+      'add connection eth') add_ethernet_connection && beep;;
+      'add connection wifi') add_wifi_connection && beep;;
+      'add connection vpn') add_vpn_connection && beep;;
+      'add proxy') add_proxy "${args[2]}" && beep;;
+      'remove device') remove_device "${args[2]}" && beep;;
+      'remove connection') remove_connection "${args[2]}" && beep;;
+      'remove proxy') remove_proxy "${args[2]}" && beep;;
+      'set proxy') set_proxy "${args[2]}" && beep;;
+      'unset proxy') unset_proxy && beep;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/notifications/main b/tools/notifications/main
--- a/tools/notifications/main
+++ b/tools/notifications/main
@@ -58,7 +58,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -99,18 +100,18 @@ run () {
     case "${cmd}${obj:+ ${obj}}" in
       'show status') show_status;;
       'list all') list_all "${args[2]}" "${args[3]}";;
-      'mute all') mute_all;;
-      'unmute all') unmute_all;;
-      'clean all') clean_all;;
-      'set popup') set_popup "${args[2]}";;
-      'set volume') set_volume "${args[2]}";;
+      'mute all') mute_all && beep;;
+      'unmute all') unmute_all && beep;;
+      'clean all') clean_all && beep;;
+      'set popup') set_popup "${args[2]}" && beep;;
+      'set volume') set_volume "${args[2]}" && beep;;
       'start') start;;
       'restart') restart;;
       'get state') get_state;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/power/commands b/tools/power/commands
--- a/tools/power/commands
+++ b/tools/power/commands
@@ -136,7 +136,7 @@ set_action () {
     handlers="[${handlers}]"
 
     pick_one 'Select a power handler:' "${handlers}" vertical || return $?
-    [[ -n "${REPLY}" ]] && handler="${REPLY}" || return 0
+    handler="${REPLY}"
   fi
 
   if [[ ! "${handler}" =~ ^(power|reboot|suspend|lid|docked)$ ]]; then
@@ -153,7 +153,7 @@ set_action () {
     actions="[${actions}]"
 
     pick_one 'Select an action:' "${actions}" vertical || return $?
-    [[ -n "${REPLY}" ]] && action="${REPLY}" || return 0
+    action="${REPLY}"
   fi
 
   if [[ ! "${action}" =~ ^(poweroff|reboot|suspend|ignore)$ ]]; then
@@ -208,7 +208,7 @@ reset_actions () {
   local config_file='/etc/systemd/logind.conf.d/00-main.conf'
 
   if [[ ! -f "${config_file}" ]]; then
-    echo 'Power actions are already set to defaults'
+    echo 'Actions already set to defaults'
     return 0
   fi
 
@@ -231,89 +231,79 @@ reset_actions () {
 # Sets the interval time of the screen saver, where
 # 0 means deactivate the screensaver.
 # Arguments:
-#  mins:    an integer interval in mins or 0
-#  persist: save or nosave, default is save
+#  interval: the number of minutes or 0
 set_screensaver () {
-  local mins="${1}"
-  local persist="${2:-"save"}"
+  local interval="${1}"
 
-  if [[ -z "${mins}" ]]; then
-    echo 'Missing the interval time'
-    return 2
-  elif [[ ! "${mins}" =~ ^[0-9]{,2}$ ]]; then
-    echo 'Invalid interval time'
-    return 2
-  elif [[ ${mins} -lt 0 ]] || [[ ${mins} -gt 60 ]]; then
-    echo 'Interval time out of range [0,60]'
-    return 2
+  if [[ -z "${interval}" ]]; then
+    ask 'Enter the interval in mins [0-60]:' || return $?
+    interval="${REPLY}"
   fi
-
-  if [[ ${mins} -gt 0 ]]; then
-    local secs=$((mins*60))
-    xset s "${secs}" "${secs}" &> /dev/null
-
-    if [[ $? -ne 0 ]]; then
-      echo 'Failed to set the screen saver'
-      return 2
-    fi
-
-    echo "Screen saver set to ${mins} mins"
-  else
-    xset s off &> /dev/null
-
-    if [[ $? -ne 0 ]]; then
-      echo 'Failed to disable screen saver'
-      return 2
-    fi
-
-    echo 'Screen saver has been disabled'
+  
+  if [[ ! "${interval}" =~ ^[0-9]{,2}$ ]]; then
+    echo 'Invalid or malformed interval'
+    return 2
+  elif [[ ${interval} -lt 0 ]] || [[ ${interval} -gt 60 ]]; then
+    echo 'Interval is out of range'
+    return 2
   fi
 
   # Save screen saver interval into settings file
-  if [[ "${persist}" == "save" ]]; then
-    local settings='{}'
-    local screensaver="{\"interval\": ${mins}}"
+  local settings='{}'
+  local screensaver="{\"interval\": ${interval}}"
 
-    if [[ -f "${SETTINGS_FILE}" ]]; then
-      settings="$(jq -e ".screensaver = ${screensaver} " "${SETTINGS_FILE}")" || return 1
-    else
-      settings="$(echo "{\"screensaver\": ${screensaver}}" | jq -e '.')" || return 1
-    fi
-
-    mkdir -p "${CONFIG_HOME}"
-    echo "${settings}" > "${SETTINGS_FILE}"
+  if [[ -f "${SETTINGS_FILE}" ]]; then
+    settings="$(jq -e ".screensaver = ${screensaver} " "${SETTINGS_FILE}")" || return 1
+  else
+    settings="$(echo "{\"screensaver\": ${screensaver}}" | jq -e '.')" || return 1
   fi
+
+  mkdir -p "${CONFIG_HOME}"
+  echo "${settings}" > "${SETTINGS_FILE}"
+
+  if [[ ${interval} -gt 0 ]]; then
+    local secs=$((interval*60))
+
+    xset s "${secs}" "${secs}" &> /dev/null
+  else
+    xset s off &> /dev/null
+  fi
+  
+  if [[ $? -ne 0 ]]; then
+    echo 'Failed to set the screen saver'
+    return 2
+  fi
+
+  echo "Screen saver set to ${interval} mins"
 }
 
-# Initializes the screen saver to settings being set
+# Initializes the screen saver to the interval saved
 # in the settings file.
 # Arguments:
 #  None
 init_screensaver () {
   if [[ ! -f "${SETTINGS_FILE}" ]]; then
     echo 'No screen saver settings found'
-    return 0
-  fi
-
-  local screensaver=''
-  screensaver="$(jq '.screensaver|if . then . else empty end' "${SETTINGS_FILE}")"
-
-  if [[ -z "${screensaver}" ]]; then
-    echo 'No screen saver settings found'
-    return 0
+    return 2
   fi
 
   local interval=''
-  interval="$(get "${screensaver}" '.interval')" || return 1
+  interval="$(jq '.screensaver.interval|if . then . else 5 end' "${SETTINGS_FILE}")"
 
-  set_screensaver "${interval}" nosave
+  if [[ ${interval} -gt 0 ]]; then
+    local secs=$((interval*60))
 
+    xset s "${secs}" "${secs}" &> /dev/null
+  else
+    xset s off &> /dev/null
+  fi
+  
   if [[ $? -ne 0 ]]; then
     echo 'Failed to initialize the screen saver'
     return 2
   fi
 
-  echo 'Screen saver has been initialized'
+  echo "Screen saver initialized to ${interval} mins"
 }
 
 # Enables or disables power saving mode via the tlp service.
@@ -323,20 +313,29 @@ set_tlp () {
   local status="${1}"
 
   if [[ -z "${status}" ]]; then
-    echo 'Missing the tlp status'
-    return 2
-  elif [[ ! "${status}" =~ ^(on|off)$ ]]; then
-    echo 'Invalid tlp status'
+    local statuses=''
+    statuses+='{"key":"on", "value":"On"},'
+    statuses+='{"key":"off", "value":"Off"}'
+    statuses="[${statuses}]"
+
+    pick_one 'Set TLP status to:' "${statuses}" horizontal || return $?
+    status="${REPLY}"
+  fi
+
+  if [[ ! "${status}" =~ ^(on|off)$ ]]; then
+    echo 'Invalid TLP status'
     return 2
   fi
 
   if [[ "${status}" == "on" ]]; then
+    echo 'Enabling TLP service...'
     sudo systemctl stop acpid.service &> /dev/null &&
     sudo systemctl disable acpid.service &> /dev/null &&
     sudo systemctl enable tlp.service &> /dev/null &&
     sudo systemctl start tlp.service &> /dev/null &&
     sudo systemctl daemon-reload
   else
+    echo 'Disabling TLP service...'
     sudo systemctl stop tlp.service &> /dev/null &&
     sudo systemctl disable tlp.service &> /dev/null &&
     sudo systemctl enable acpid.service &> /dev/null &&
@@ -345,7 +344,7 @@ set_tlp () {
   fi
 
   if [[ $? -ne 0 ]]; then
-    echo "Failed to set tlp to ${status}"
+    echo "Failed to set TLP to ${status}"
     return 2
   fi
 
@@ -362,21 +361,30 @@ set_charge () {
   local threshold="${2}"
 
   if [[ -z "${action}" ]]; then
-    echo 'Missing the charge action'
-    return 2
-  elif [[ ! "${action}" =~ ^(start|stop)$ ]]; then
+    local actions=''
+    actions+='{"key":"start", "value":"Start"},'
+    actions+='{"key":"stop", "value":"Stop"}'
+    actions="[${actions}]"
+
+    pick_one 'Which charge action to set:' "${actions}" horizontal || return $?
+    action="${REPLY}"
+  fi
+
+  if [[ ! "${action}" =~ ^(start|stop)$ ]]; then
     echo 'Invalid charge action'
     return 2
   fi
 
   if [[ -z "${threshold}" ]]; then
-    echo 'Missing the threshold value'
-    return 2
-  elif [[ ! "${threshold}" =~ ^[0-9]{1,3}$ ]]; then
-    echo 'Invalid threshold value'
+    ask 'Enter the charge threshold [0-100]:' || return $?
+    threshold="${REPLY}"
+  fi
+  
+  if [[ ! "${threshold}" =~ ^[0-9]{1,3}$ ]]; then
+    echo 'Invalid charge threshold value'
     return 2
   elif [[ ${threshold} -lt 0 ]] || [[ ${threshold} -gt 100 ]]; then
-    echo 'Threshold value out of range'
+    echo 'Charge threshold is out of range'
     return 2
   fi
 
@@ -463,7 +471,5 @@ blank_screen () {
     echo 'Unable to blank the screen'
     return 2
   fi
-
-  echo 'Screen has been blanked'
 }
 
diff --git a/tools/power/main b/tools/power/main
--- a/tools/power/main
+++ b/tools/power/main
@@ -60,7 +60,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -100,12 +101,12 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'show status') show_status;;
-      'set action') set_action "${args[2]}" "${args[3]}";;
-      'set screensaver') set_screensaver "${args[2]}";;
-      'set tlp') set_tlp "${args[2]}";;
-      'set charge') set_charge "${args[2]}" "${args[3]}";;
-      'reset actions') reset_actions;;
-      'init screensaver') init_screensaver;;
+      'set action') set_action "${args[2]}" "${args[3]}" && beep;;
+      'set screensaver') set_screensaver "${args[2]}" && beep;;
+      'set tlp') set_tlp "${args[2]}" && beep;;
+      'set charge') set_charge "${args[2]}" "${args[3]}" && beep;;
+      'reset actions') reset_actions && beep;;
+      'init screensaver') init_screensaver && beep;;
       'shutdown') shutdown_system;;
       'reboot') reboot_system;;
       'suspend') suspend_system;;
@@ -113,7 +114,7 @@ run () {
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/printers/main b/tools/printers/main
--- a/tools/printers/main
+++ b/tools/printers/main
@@ -64,7 +64,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -107,22 +108,22 @@ run () {
       'show printer') show_printer "${args[2]}";;
       'list printers') list_printers;;
       'list jobs') list_jobs;;
-      'add printer') add_printer "${args[2]}" "${args[3]}";;
-      'remove printer') remove_printer "${args[2]}";;
-      'share printer') share_printer "${args[2]}";;
-      'unshare printer') unshare_printer "${args[2]}";;
-      'set quality') set_option "${args[2]}" 'Quality' "${args[3]}";;
-      'set size') set_option "${args[2]}" 'PageSize' "${args[3]}";;
-      'set paper') set_option "${args[2]}" 'MediaType' "${args[3]}";;
-      'set toner') set_option "${args[2]}" 'TonerSaveMode' "${args[3]}";;
-      'set onerror') set_option "${args[2]}" 'printer-error-policy' "${args[3]}";;
-      'set default') set_default "${args[2]}";;
-      'cancel job') cancel_job "${args[2]}";;
+      'add printer') add_printer "${args[2]}" "${args[3]}" && beep;;
+      'remove printer') remove_printer "${args[2]}" && beep;;
+      'share printer') share_printer "${args[2]}" && beep;;
+      'unshare printer') unshare_printer "${args[2]}" && beep;;
+      'set quality') set_option "${args[2]}" 'Quality' "${args[3]}" && beep;;
+      'set size') set_option "${args[2]}" 'PageSize' "${args[3]}" && beep;;
+      'set paper') set_option "${args[2]}" 'MediaType' "${args[3]}" && beep;;
+      'set toner') set_option "${args[2]}" 'TonerSaveMode' "${args[3]}" && beep;;
+      'set onerror') set_option "${args[2]}" 'printer-error-policy' "${args[3]}" && beep;;
+      'set default') set_default "${args[2]}" && beep;;
+      'cancel job') cancel_job "${args[2]}" && beep;;
       'restart') restart;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/security/main b/tools/security/main
--- a/tools/security/main
+++ b/tools/security/main
@@ -56,7 +56,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -96,18 +97,18 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'show status') show_status;;
-      'set locker') set_screen_locker "${args[2]}";;
-      'set password') set_user_password;;
-      'set attempts') set_faillock_attempts "${args[2]}";;
-      'set unblock') set_faillock_unblock "${args[2]}";;
-      'set interval') set_faillock_interval "${args[2]}";;
-      'init locker') init_screen_locker;;
+      'set locker') set_screen_locker "${args[2]}" && beep;;
+      'set password') set_user_password && beep;;
+      'set attempts') set_faillock_attempts "${args[2]}" && beep;;
+      'set unblock') set_faillock_unblock "${args[2]}" && beep;;
+      'set interval') set_faillock_interval "${args[2]}" && beep;;
+      'init locker') init_screen_locker && beep;;
       'lock screen') lock_screen;;
       'logout user') logout_user;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
diff --git a/tools/trash/main b/tools/trash/main
--- a/tools/trash/main
+++ b/tools/trash/main
@@ -53,7 +53,8 @@ run () {
         return 0;;
      'q') QUIET='true';;
      *)
-      fail 'Ooops, invalid or unknown option'
+      echo 'Ooops, invalid or unknown option'
+      $(exit 2) || beep
       return $?;;
     esac
   done
@@ -93,13 +94,13 @@ run () {
 
     case "${cmd}${obj:+ ${obj}}" in
       'list files') list_files "${args[2]}";;
-      'restore files') restore_files "${args[2]}";;
-      'remove files') remove_files "${args[@]:2}";;
-      'empty files') empty_files "${args[2]}";;  
+      'restore files') restore_files "${args[2]}" && beep;;
+      'remove files') remove_files "${args[@]:2}" && beep;;
+      'empty files') empty_files "${args[2]}" && beep;;  
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
-    esac && success || fail
+    esac || beep
 
     local exit_code=$?
     if [[ "${mode}" == "once" ]]; then
