Enhance user experience with success and fail beep sounds

diff --git a/tools/audio/main b/tools/audio/main
--- a/tools/audio/main
+++ b/tools/audio/main
@@ -66,69 +66,38 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          logs) show_logs;;
-          card) show_card "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      restart) restart;;
-      list)
-        case "${cmd[1]}" in
-          cards) list_cards;;
-          outputs) list_ports sink;;
-          inputs) list_ports source;;
-          playbacks) list_playbacks "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          profile) set_profile "${cmd[2]}" "${cmd[3]}";;
-          output) set_default sink "${cmd[2]}";;
-          input) set_default source "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      turn)
-        case "${cmd[1]}" in
-          output) turn_default sink "${cmd[2]}";;
-          input) turn_default source "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      mute)
-        case "${cmd[1]}" in
-          outputs) set_mute sink 1;;
-          inputs) set_mute source 1;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unmute)
-        case "${cmd[1]}" in
-          outputs) set_mute sink 0;;
-          inputs) set_mute source 0;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show logs') show_logs;;
+      'show card') show_card "${args[2]}";;
+      'restart') restart;;
+      'list cards') list_cards;;
+      'list outputs') list_ports sink;;
+      'list inputs') list_ports source;;
+      'list playbacks') list_playbacks "${args[2]}";;
+      'set profile') set_profile "${args[2]}" "${args[3]}";;
+      'set ouptut') set_default sink "${args[2]}";;
+      'set input') set_default source "${args[2]}";;
+      'turn output') turn_default sink "${args[2]}";;
+      'turn input') turn_default source "${args[2]}";;
+      'mute outputs') set_mute sink 1;;
+      'mute inputs') set_mute source 1;;
+      'unmute outputs') set_mute sink 0;;
+      'unmute inputs') set_mute source 0;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -137,30 +106,27 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    restart) restart;;
-    set)
-      case "${2}" in
-        profile) set_profile;;
-        output) set_default sink;;
-        *) abort 'Invalid or unknown command';; 
-      esac;;
-    mute) turn_default sink mute;;
-    unmute) turn_default sink unmute;;
-    up) turn_default sink up;;
-    down) turn_default sink down;;
-    *) abort 'Invalid or unknown command';; 
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'restart') restart;;
+    'set profile') set_profile;;
+    'set output') set_default sink;;
+    'mute') turn_default sink mute;;
+    'unmute') turn_default sink unmute;;
+    'up') turn_default sink up;;
+    'down') turn_default sink down;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/bluetooth/main b/tools/bluetooth/main
--- a/tools/bluetooth/main
+++ b/tools/bluetooth/main
@@ -48,67 +48,36 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          logs) show_logs;;
-          controller) show_controller "${cmd[2]}";;
-          device) show_device "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          controllers) list_controllers;;
-          devices) list_devices "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          controller) set_controller "${cmd[2]}";;
-          power) set_power "${cmd[2]}";;
-          scan) set_scan "${cmd[2]}";;
-          discoverable) set_discoverable "${cmd[2]}";;
-          pairable) set_pairable "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      connect)
-        case "${cmd[1]}" in
-          device) connect_device "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      disconnect)
-        case "${cmd[1]}" in
-          device) disconnect_device "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      remove)
-        case "${cmd[1]}" in
-          device) remove_device "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      restart) restart_bluetooth;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show logs') show_logs;;
+      'show controller') show_controller "${args[2]}";;
+      'show device') show_device "${args[2]}";;
+      'list controllers') list_controllers;;
+      'list devices') list_devices "${args[2]}";;
+      'set controller') set_controller "${args[2]}";;
+      'set power') set_power "${args[2]}";;
+      'set scan') set_scan "${args[2]}";;
+      'set discoverable') set_discoverable "${args[2]}";;
+      'set pairable') set_pairable "${args[2]}";;
+      'connect device') connect_device "${args[2]}";;
+      'disconnect device') disconnect_device "${args[2]}";;
+      'remove device') remove_device "${args[2]}";;
+      'restart') restart_bluetooth;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/clock/main b/tools/clock/main
--- a/tools/clock/main
+++ b/tools/clock/main
@@ -37,47 +37,28 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          ntp) set_ntp "${cmd[2]}";;
-          timezone) set_timezone "${cmd[2]}";;
-          time) set_time "${cmd[2]}";;
-          date) set_date "${cmd[2]}";;
-          rtc) set_rtc "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';; 
-        esac;;
-      sync)
-        case "${cmd[1]}" in
-          rtc) sync_rtc;;
-          *) echo 'Invalid or unknown command';; 
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'set ntp') set_ntp "${args[2]}";;
+      'set timezone') set_timezone "${args[2]}";;
+      'set time') set_time "${args[2]}";;
+      'set date') set_date "${args[2]}";;
+      'set rtc') set_rtc "${args[2]}";;
+      'sync rtc') sync_rtc;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/cloud/main b/tools/cloud/main
--- a/tools/cloud/main
+++ b/tools/cloud/main
@@ -46,58 +46,27 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      list)
-        case "${cmd[1]}" in
-          remotes) list_remotes "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      sync)
-        case "${cmd[1]}" in
-          remote)
-            case "${cmd[2]}" in
-              drive) sync_drive "${cmd[3]}";;
-              dropbox) sync_dropbox "${cmd[3]}";;
-              *) echo 'Invalid or unknown service';;
-            esac;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      delete)
-        case "${cmd[1]}" in
-          remote) delete_remote "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      mount)
-        case "${cmd[1]}" in
-          remote) mount_remote "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unmount)
-        case "${cmd[1]}" in
-          remote) unmount_remote "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Unknown or invalid command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'list remotes') list_remotes "${args[2]}";;
+      'sync remote drive') sync_drive "${args[3]}";;
+      'sync remote dropbox') sync_dropbox "${args[3]}";;
+      'delete remote') delete_remote "${args[2]}";;
+      'mount  remote') mount_remote "${args[2]}";;
+      'unmount remote') unmount_remote "${args[2]}";;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -106,24 +75,21 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    mount)
-      case "${2}" in
-        remotes) mount_all || abort;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'mount remotes') mount_all;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/desktop/main b/tools/desktop/main
--- a/tools/desktop/main
+++ b/tools/desktop/main
@@ -57,62 +57,31 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+  
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
-
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          pointer) show_pointer "${cmd[2]}";;
-          tablet) show_tablet "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          wallpaper) set_wallpaper "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      speed)
-        case "${cmd[1]}" in
-          pointer) set_pointer_speed "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      scale)
-        case "${cmd[1]}" in
-          tablet) scale_tablet "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      map)
-        case "${cmd[1]}" in
-          tablet) map_tablet "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          wallpapers) list_wallpapers;;
-          pointers) list_pointers;;
-          tablets) list_tablets;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show pointer') show_pointer "${args[2]}";;
+      'show tablet') show_tablet "${args[2]}";;
+      'set wallpaper') set_wallpaper "${args[2]}" "${args[3]}";;
+      'speed pointer') set_pointer_speed "${args[2]}";;
+      'scale tablet') scale_tablet "${args[2]}" "${args[3]}";;
+      'map tablet') map_tablet "${args[2]}" "${args[3]}";;
+      'list wallpapers') list_wallpapers;;
+      'list pointers') list_pointers;;
+      'list tablets') list_tablets;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -121,26 +90,23 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    init)
-      case "${2}" in
-        pointer) init_pointer || abort;;
-        tablets) init_tablets || abort;;
-        wallpaper) init_wallpaper || abort;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'init pointer') init_pointer;;
+    'init tablets') init_tablets;;
+    'init wallpaper') init_wallpaper;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/disks/main b/tools/disks/main
--- a/tools/disks/main
+++ b/tools/disks/main
@@ -54,82 +54,43 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      list)
-        case "${cmd[1]}" in
-          disks) list_disks;;
-          partitions) list_partitions "${cmd[2]}";;
-          roms) list_roms;;
-          folders) list_shared_folders "${cmd[2]}";;
-          mounts) list_mounts;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          disk) show_disk "${cmd[2]}";;
-          partition) show_partition "${cmd[2]}";;
-          rom) show_rom "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      mount)
-        case "${cmd[1]}" in
-          partition) mount_partition "${cmd[2]}";;
-          rom) mount_rom "${cmd[2]}";;
-          image) mount_image "${cmd[2]}";;
-          folder) mount_shared_folder "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unmount)
-        case "${cmd[1]}" in
-          partition) unmount_partition "${cmd[2]}";;
-          rom) unmount_rom "${cmd[2]}";;
-          image) unmount_image "${cmd[2]}";;
-          folder) unmount_shared_folder "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      format)
-        case "${cmd[1]}" in
-          disk) format_disk "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      eject)
-        case "${cmd[1]}" in
-          disk) eject_disk "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      scan)
-        case "${cmd[1]}" in
-          disk) scan_disk "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      create)
-        case "${cmd[1]}" in
-          encrypted) create_encrypted "${cmd[2]}";;
-          bootable) create_bootable "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'list disks') list_disks;;
+      'list partitions') list_partitions "${args[2]}";;
+      'list roms') list_roms;;
+      'list folders') list_shared_folders "${args[2]}";;
+      'list mounts') list_mounts;;
+      'show status') show_status;;
+      'show disk') show_disk "${args[2]}";;
+      'show partition') show_partition "${args[2]}";;
+      'show rom') show_rom "${args[2]}";;
+      'mount partition') mount_partition "${args[2]}";;
+      'mount rom') mount_rom "${args[2]}";;
+      'mount image') mount_image "${args[2]}";;
+      'mount folder') mount_shared_folder "${args[2]}";;
+      'unmount partition') unmount_partition "${args[2]}";;
+      'unmount rom') unmount_rom "${args[2]}";;
+      'unmount image') unmount_image "${args[2]}";;
+      'unmount folder') unmount_shared_folder "${args[2]}";;
+      'format disk') format_disk "${args[2]}";;
+      'eject disk') eject_disk "${args[2]}";;
+      'scan disk') scan_disk "${args[2]}";;
+      'create encrypted') create_encrypted "${args[2]}";;
+      'create bootable') create_bootable "${args[2]}";;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/displays/main b/tools/displays/main
--- a/tools/displays/main
+++ b/tools/displays/main
@@ -26,7 +26,8 @@ show_help () {
 
   echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-  echo -e '\nCOMMANDS'  printf ' %-44s %s\n' \
+  echo -e '\nCOMMANDS'
+  printf ' %-44s %s\n' \
     'help' 'Show this help message.' \
     '' '' \
     'show status' 'Show a report of the Xorg server and active outputs.' \
@@ -65,77 +66,42 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          logs) show_logs "${cmd[2]}";;
-          output) show_output "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          outputs) list_outputs "${cmd[2]}";;
-          colors) list_colors;;
-          layouts) list_layouts;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          layout) set_layout;;
-          mode) set_mode "${cmd[2]}" "${cmd[3]}" "${cmd[4]}";;
-          primary) set_primary "${cmd[2]}";;
-          on) set_on "${cmd[2]}";;
-          off) set_off "${cmd[2]}";;
-          color) set_color "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      reset)
-        case "${cmd[1]}" in
-          color) reset_color "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      save)
-        case "${cmd[1]}" in
-          layout) save_layout;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      delete)
-        case "${cmd[1]}" in
-          layout) delete_layout "${cmd[2]}";;
-          color) delete_color "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      restore)
-        case "${cmd[1]}" in
-          layout) restore_layout;;
-          colors) restore_colors;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      rotate) rotate "${cmd[1]}" "${cmd[2]}";;
-      reflect) reflect "${cmd[1]}" "${cmd[2]}";;
-      mirror) mirror "${cmd[1]}";;
-      *) echo 'Invalid or unknown command';;
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show logs') show_logs "${args[2]}";;
+      'show output') show_output "${args[2]}";;
+      'list outputs') list_outputs "${args[2]}";;
+      'list colors') list_colors;;
+      'list layouts') list_layouts;;
+      'set layout') set_layout;;
+      'set mode') set_mode "${args[2]}" "${args[3]}" "${args[4]}";;
+      'set primary') set_primary "${args[2]}";;
+      'set on') set_on "${args[2]}";;
+      'set off') set_off "${args[2]}";;
+      'set color') set_color "${args[2]}" "${args[3]}";;
+      'reset color') reset_color "${args[2]}";;
+      'save layout') save_layout;;
+      'delete layout') delete_layout "${args[2]}";;
+      'delete color') delete_color "${args[2]}";;
+      'restore layout') restore_layout;;
+      'restore colors') restore_colors;;
+      'rotate') rotate "${args[1]}" "${args[2]}";;
+      'reflect') reflect "${args[1]}" "${args[2]}";;
+      'mirror') mirror "${args[1]}";;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -144,29 +110,22 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    restore)
-      case "${2}" in
-        layout) restore_layout;;
-        colors) restore_colors;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    fix)
-      case "${2}" in
-        layout) fix_layout;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'restore layout') restore_layout;;
+    'restore colors') restore_colors;;
+    'fix layout') fix_layout;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
diff --git a/tools/langs/main b/tools/langs/main
--- a/tools/langs/main
+++ b/tools/langs/main
@@ -44,59 +44,32 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          keymap) set_keymap "${cmd[2]}";;
-          language) set_language "${cmd[2]}";;
-          locale) set_locale "${cmd[2]}" "${cmd[3]}";;
-          options) set_options "${cmd[2]}";;
-          model) set_model "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      add)
-        case "${cmd[1]}" in
-          locale) add_locale "${cmd[2]}";;
-          layout) add_layout "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      remove)
-        case "${cmd[1]}" in
-          locale) remove_locale "${cmd[2]}";;
-          layout) remove_layout "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      order)
-        case "${cmd[1]}" in
-          layouts) order_layouts;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'set keymap') set_keymap "${args[2]}";;
+      'set language') set_language "${args[2]}";;
+      'set locale') set_locale "${args[2]}" "${args[3]}";;
+      'set options') set_options "${args[2]}";;
+      'set model') set_model "${args[2]}";;
+      'add locale') add_locale "${args[2]}";;
+      'add layout') add_layout "${args[2]}";;
+      'remove locale') remove_locale "${args[2]}";;
+      'remove layout') remove_layout "${args[2]}";;
+      'order layouts') order_layouts;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/networks/main b/tools/networks/main
--- a/tools/networks/main
+++ b/tools/networks/main
@@ -13,7 +13,8 @@ source /opt/stack/networks/commands
 show_help () {
   echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-  echo -e '\nCOMMANDS'  printf ' %-35s %s\n' \
+  echo -e '\nCOMMANDS'
+  printf ' %-35s %s\n' \
     'help' 'Show this help message.' \
     '' '' \
     'show status' 'Show the current status of networking.' \
@@ -51,80 +52,41 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          device) show_device "${cmd[2]}";;
-          connection) show_connection "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          devices) list_devices;;
-          connections) list_connections;;
-          wifis) list_wifis "${cmd[2]}" "${cmd[3]}";;
-          proxies) list_proxies;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      power)
-        case "${cmd[1]}" in
-          network) power_network "${cmd[2]}";;
-          wifi) power_wifi "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      up) up "${cmd[1]}" "${cmd[2]}";;
-      down) down "${cmd[1]}" "${cmd[2]}";;
-      add)
-        case "${cmd[1]}" in
-          connection)
-            case "${cmd[2]}" in
-              eth) add_ethernet_connection;;
-              wifi) add_wifi_connection;;
-              vpn) add_vpn_connection;;
-              *) echo 'Invalid or unknown command';;
-            esac;;
-          proxy) add_proxy "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      remove)
-        case "${cmd[1]}" in
-          device) remove_device "${cmd[2]}";;
-          connection) remove_connection "${cmd[2]}";;
-          proxy) remove_proxy "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          proxy) set_proxy "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unset)
-        case "${cmd[1]}" in
-          proxy) unset_proxy;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show device') show_device "${args[2]}";;
+      'show connection') show_connection "${args[2]}";;
+      'list devices') list_devices;;
+      'list connections') list_connections;;
+      'list wifis') list_wifis "${args[2]}" "${args[3]}";;
+      'list proxies') list_proxies;;
+      'power network') power_network "${args[2]}";;
+      'power wifi') power_wifi "${args[2]}";;
+      'up') up "${args[1]}" "${args[2]}";;
+      'down') down "${args[1]}" "${args[2]}";;
+      'add connection eth') add_ethernet_connection;;
+      'add connection wifi') add_wifi_connection;;
+      'add connection vpn') add_vpn_connection;;
+      'add proxy') add_proxy "${args[2]}";;
+      'remove device') remove_device "${args[2]}";;
+      'remove connection') remove_connection "${args[2]}";;
+      'remove proxy') remove_proxy "${args[2]}";;
+      'set proxy') set_proxy "${args[2]}";;
+      'unset proxy') unset_proxy;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/notifications/main b/tools/notifications/main
--- a/tools/notifications/main
+++ b/tools/notifications/main
@@ -59,61 +59,30 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          all) list_all "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      mute)
-        case "${cmd[1]}" in
-          all) mute_all;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unmute)
-        case "${cmd[1]}" in
-          all) unmute_all;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      clean)
-        case "${cmd[1]}" in
-          all) clean_all;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          popup) set_popup "${cmd[2]}";;
-          volume) set_volume "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      start) start;;
-      restart) restart;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'list all') list_all "${args[2]}" "${args[3]}";;
+      'mute all') mute_all;;
+      'unmute all') unmute_all;;
+      'clean all') clean_all;;
+      'set popup') set_popup "${args[2]}";;
+      'set volume') set_volume "${args[2]}";;
+      'start') start;;
+      'restart') restart;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -122,36 +91,25 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    get)
-      case "${2}" in
-        state) get_state;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    mute)
-      case "${2}" in
-        all) mute_all;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    unmute)
-      case "${2}" in
-        all) unmute_all;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    start) start;;
-    restart) restart;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+   'help') show_help once;;
+    'get state') get_state;;
+    'mute all') mute_all;;
+    'unmute all') unmute_all;;
+    'start') start;;
+    'restart') restart;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/power/main b/tools/power/main
--- a/tools/power/main
+++ b/tools/power/main
@@ -30,7 +30,8 @@ show_help () {
 
   echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
-  echo -e '\nCOMMANDS'  printf ' %-36s %s\n' \
+  echo -e '\nCOMMANDS'
+  printf ' %-36s %s\n' \
     'help' 'Show this help message.' \
     '' '' \
     'show status' 'Show the status of the system power.' \
@@ -54,46 +55,27 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          action) set_action "${cmd[2]}" "${cmd[3]}";;
-          screensaver) set_screensaver "${cmd[2]}";;
-          tlp) set_tlp "${cmd[2]}";;
-          charge) set_charge "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      reset)
-        case "${cmd[1]}" in
-          actions) reset_actions;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'set action') set_action "${args[2]}" "${args[3]}";;
+      'set screensaver') set_screensaver "${args[2]}";;
+      'set tlp') set_tlp "${args[2]}";;
+      'set charge') set_charge "${args[2]}" "${args[3]}";;
+      'reset actions') reset_actions;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -102,28 +84,25 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    init)
-      case "${2}" in
-        screensaver) init_screensaver || abort;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    shutdown) shutdown_system;;
-    reboot) reboot_system;;
-    suspend) suspend_system;;
-    blank) blank_screen;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'init screensaver') init_screensaver;;
+    'shutdown') shutdown_system;;
+    'reboot') reboot_system;;
+    'suspend') suspend_system;;
+    'blank') blank_screen;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/printers/main b/tools/printers/main
--- a/tools/printers/main
+++ b/tools/printers/main
@@ -48,76 +48,37 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          printer) show_printer "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      list)
-        case "${cmd[1]}" in
-          printers) list_printers;;
-          jobs) list_jobs;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      add)
-        case "${cmd[1]}" in
-          printer) add_printer "${cmd[2]}" "${cmd[3]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      remove)
-        case "${cmd[1]}" in
-          printer) remove_printer "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      share)
-        case "${cmd[1]}" in
-          printer) share_printer "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      unshare)
-        case "${cmd[1]}" in
-          printer) unshare_printer "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          quality) set_option "${cmd[2]}" 'Quality' "${cmd[3]}";;
-          size) set_option "${cmd[2]}" 'PageSize' "${cmd[3]}";;
-          paper) set_option "${cmd[2]}" 'MediaType' "${cmd[3]}";;
-          toner) set_option "${cmd[2]}" 'TonerSaveMode' "${cmd[3]}";;
-          onerror) set_option "${cmd[2]}" 'printer-error-policy' "${cmd[3]}";;
-          default) set_default "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      cancel)
-        case "${cmd[1]}" in
-          job) cancel_job "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      restart) restart;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'show printer') show_printer "${args[2]}";;
+      'list printers') list_printers;;
+      'list jobs') list_jobs;;
+      'add printer') add_printer "${args[2]}" "${args[3]}";;
+      'remove printer') remove_printer "${args[2]}";;
+      'share printer') share_printer "${args[2]}";;
+      'unshare printer') unshare_printer "${args[2]}";;
+      'set quality') set_option "${args[2]}" 'Quality' "${args[3]}";;
+      'set size') set_option "${args[2]}" 'PageSize' "${args[3]}";;
+      'set paper') set_option "${args[2]}" 'MediaType' "${args[3]}";;
+      'set toner') set_option "${args[2]}" 'TonerSaveMode' "${args[3]}";;
+      'set onerror') set_option "${args[2]}" 'printer-error-policy' "${args[3]}";;
+      'set default') set_default "${args[2]}";;
+      'cancel job') cancel_job "${args[2]}";;
+      'restart') restart;;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
diff --git a/tools/security/main b/tools/security/main
--- a/tools/security/main
+++ b/tools/security/main
@@ -51,42 +51,27 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      show)
-        case "${cmd[1]}" in
-          status) show_status;;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      set)
-        case "${cmd[1]}" in
-          locker) set_screen_locker "${cmd[2]}";;
-          password) set_user_password;;
-          attempts) set_faillock_attempts "${cmd[2]}";;
-          unblock) set_faillock_unblock "${cmd[2]}";;
-          interval) set_faillock_interval "${cmd[2]}";;
-          *) echo 'Invalid or unknown command';;
-        esac;;
-      *) echo 'Invalid or unknown command';; 
-    esac
-    
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'show status') show_status;;
+      'set locker') set_screen_locker "${args[2]}";;
+      'set password') set_user_password;;
+      'set attempts') set_faillock_attempts "${args[2]}";;
+      'set unblock') set_faillock_unblock "${args[2]}";;
+      'set interval') set_faillock_interval "${args[2]}";;
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
 
     REPLY=''
   done
@@ -95,34 +80,23 @@ loop () {
 }
 
 once () {
-  case "${1}" in
-    help) show_help once;;
-    init)
-      case "${2}" in
-        locker) init_screen_locker || abort;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    lock)
-      case "${2}" in
-        screen) lock_screen;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    logout)
-      case "${2}" in
-        user) logout_user;;
-        *) abort 'Invalid or unknown command';;
-      esac;;
-    *) abort 'Invalid or unknown command';;
-  esac
+  local cmd="${1}"
+  local obj="${2}"
 
-  if [[ $? -ne 0 ]]; then
-    abort
-  fi
+  case "${cmd}${obj:+ ${obj}}" in
+    'help') show_help once;;
+    'init locker') init_screen_locker;;
+    'lock screen') lock_screen;;
+    'logout user') logout_user;;
+    *)
+      echo 'Ooops, invalid or unknown command'
+      return 2;;
+  esac
 }
 
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/trash/main b/tools/trash/main
--- a/tools/trash/main
+++ b/tools/trash/main
@@ -47,33 +47,26 @@ loop () {
 
     set -f
     set_separator line
-    local cmd=($(xargs -n1 <<< "${REPLY}"))
+    local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
 
-    if [[ "${cmd[0]}" == "help" ]]; then
-      show_help
-      continue
-    elif [[ "${cmd[0]}" == "clear" ]]; then
-      clear
-      continue
-    elif [[ "${cmd[0]}" == "quit" ]]; then
-      break
-    elif [[ -z "${cmd[0]}" ]]; then
-      continue
-    fi
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
 
-    case "${cmd[0]}" in
-      list) list_files "${cmd[1]}";;
-      restore) restore_files "${cmd[1]}";;
-      remove) remove_files "${cmd[@]:1}";;
-      empty) empty_files "${cmd[1]}";;
-      *) echo 'Invalid or unknown command';; 
-    esac
-  
-    if [[ $? -eq 1 ]]; then
-      echo 'An unknown error has occurred'
-    fi
-  
+    case "${cmd}${obj:+ ${obj}}" in
+      'help') show_help;;
+      'list') list_files "${args[1]}";;
+      'restore') restore_files "${args[1]}";;
+      'remove') remove_files "${args[@]:1}";;
+      'empty') empty_files "${args[1]}";;  
+      'clear') clear && continue;;
+      'quit') break;;
+      '') continue;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
+
     REPLY=''
   done
 
@@ -88,7 +81,8 @@ once () {
     if [[ "${1}" = "-h" ]] || [[ "${1}" == "--help" ]]; then
       opts="${opts} help"
     elif [[ "${1}" =~ ^(-|--) ]]; then
-      abort 'Unknown or invalid option'
+      echo 'Ooops, unknown or invalid option!'
+      return 2
     elif [[ -n "${1}" ]]; then
       files+=("${1}")
     else
@@ -108,6 +102,6 @@ once () {
 if [[ $# -eq 0 ]]; then
   loop
 else
-  once "$@"
+  once "$@" && success || fail
 fi
 
diff --git a/tools/utils b/tools/utils
--- a/tools/utils
+++ b/tools/utils
@@ -424,3 +424,47 @@ download () {
   done
 }
 
+# Plays a success beep sound printing the optionaly
+# given message.
+# Arguments:
+#  message: a message to print
+# Returns:
+#  A zero exit code.
+success () {
+  local message="${1}"
+
+  if [[ -n "${message}" ]]; then
+    echo -e "${message}"
+  fi
+
+  pw-play --volume=0.5 /usr/share/sounds/dunst/normal.wav &
+
+  return 0
+}
+
+# Plays a failure beep sound printing the optionaly given
+# message and returning the current exit code set by the
+# previous command.
+# Arguments:
+#  message: a message to print
+# Returns:
+#  A non-zero exit code.
+fail () {
+  local exit_code=$?
+
+  local message="${1}"
+
+  # Set a generic error message only for exit code 1
+  if [[ -z "${message}" ]] && [[ ${exit_code} -eq 1 ]]; then
+    message='Ooops, an unknwon error occurred!'
+  fi
+
+  if [[ -n "${message}" ]]; then
+    echo -e "${message}"
+  fi
+
+  pw-play --volume=0.5 /usr/share/sounds/dunst/critical.wav &
+
+  return ${exit_code}
+}
+
