Make loop mode cmds to be available for once calls as well

diff --git a/tools/audio/main b/tools/audio/main
--- a/tools/audio/main
+++ b/tools/audio/main
@@ -7,39 +7,30 @@ source /opt/stack/audio/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: audio [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: audio [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-12s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-12s %s\n' \
-      'set profile' 'Set the active profile.' \
-      'set output' 'Set the active output.' \
-      '' '' \
-      'up' 'Increase the volume of active output.' \
-      'down' 'Decrease the volume of active output.' \
-      'mute' 'Mute the active output.' \
-      'unmute' 'Unmute the active output.' \
-      '' '' \
-      'restart' 'Restart the audio server.'
-
-    return 0
+    printf ' %-32s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
   printf ' %-32s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
     'show status' 'Show a report of the system audio.' \
     'show logs' 'Show the last logs of the audio service.' \
     'show card [<index>]' 'Show the data of a card.' \
@@ -61,22 +52,55 @@ show_help () {
     'restart' 'Restart the audio server.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt audio && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt audio && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'show logs') show_logs;;
       'show card') show_card "${args[2]}";;
@@ -94,55 +118,19 @@ loop () {
       'mute inputs') set_mute source 1;;
       'unmute outputs') set_mute sink 0;;
       'unmute inputs') set_mute source 0;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-once () {
-  while getopts 'hq' opt; do
-    case "${opt}" in
-     'h')
-        show_help once
-        return 0;;
-     'q') QUIET='true';;
-     *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
-    esac
-  done
-
-  shift $((OPTIND-1))
-
-  local cmd="${1}"
-  local obj="${2}"
-
-  case "${cmd}${obj:+ ${obj}}" in
-    'restart') restart;;
-    'set profile') set_profile;;
-    'set output') set_default sink;;
-    'mute') turn_default sink mute;;
-    'unmute') turn_default sink unmute;;
-    'up') turn_default sink up;;
-    'down') turn_default sink down;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
-}
-
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
diff --git a/tools/cloud/main b/tools/cloud/main
--- a/tools/cloud/main
+++ b/tools/cloud/main
@@ -7,77 +7,43 @@ source /opt/stack/cloud/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: cloud [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: cloud [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-15s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-15s %s\n' \
-      'mount remotes' 'Mount all synced cloud remotes.'
-
-    return 0
+    printf ' %-30s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-  
-  echo -e '\nCOMMANDS'
   printf ' %-30s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
     'list remotes [service]' 'List all synced remotes by service.' \
     'sync remote <service> <name>' 'Sync a remote service, where service' \
     '' 'could be drive or dropbox.' \
     'delete remote [<name>]' 'Delete a synced remote service.' \
     '' '' \
     'mount remote [<name>]' 'Mount an already synced remote.' \
-    'unmount remote [<name>]' 'Unmount an already mounted remote.'
+    'unmount remote [<name>]' 'Unmount an already mounted remote.' \
+    'mount remotes' 'Mount all synced cloud remotes.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
 
-  while true; do
-    prompt cloud && history -s "${REPLY}"
-
-    set -f
-    set_separator line
-    local args=($(xargs -n1 <<< "${REPLY}"))
-    restore_separator && set +f
-
-    local cmd="${args[0]}"
-    local obj="${args[1]}"
-
-    case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
-      'list remotes') list_remotes "${args[2]}";;
-      'sync remote drive') sync_drive "${args[3]}";;
-      'sync remote dropbox') sync_dropbox "${args[3]}";;
-      'delete remote') delete_remote "${args[2]}";;
-      'mount  remote') mount_remote "${args[2]}";;
-      'unmount remote') unmount_remote "${args[2]}";;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
-      *)
-        echo 'Ooops, invalid or unknown command!'
-        $(return 2);;
-    esac && success || fail
-
-    REPLY=''
-  done
-
-  clear
-}
-
-once () {
   while getopts 'hq' opt; do
     case "${opt}" in
      'h')
@@ -85,27 +51,65 @@ once () {
         return 0;;
      'q') QUIET='true';;
      *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
     esac
   done
 
   shift $((OPTIND-1))
 
-  local cmd="${1}"
-  local obj="${2}"
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
-  case "${cmd}${obj:+ ${obj}}" in
-    'mount remotes') mount_all;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
+  while true; do
+    if [[ "${mode}" == "loop" ]]; then
+      prompt cloud && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
+
+    set -f
+    set_separator line
+    local args=($(xargs -n1 <<< "${REPLY}"))
+    restore_separator && set +f
+    REPLY=''
+
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
+
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
+    case "${cmd}${obj:+ ${obj}}" in
+      'list remotes') list_remotes "${args[2]}";;
+      'sync remote drive') sync_drive "${args[3]}";;
+      'sync remote dropbox') sync_dropbox "${args[3]}";;
+      'delete remote') delete_remote "${args[2]}";;
+      'mount  remote') mount_remote "${args[2]}";;
+      'unmount remote') unmount_remote "${args[2]}";;
+      'mount remotes') mount_all;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
+
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
+  done
+
+  clear
 }
 
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
diff --git a/tools/desktop/main b/tools/desktop/main
--- a/tools/desktop/main
+++ b/tools/desktop/main
@@ -7,33 +7,30 @@ source /opt/stack/desktop/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: desktop [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: desktop [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-16s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-16s %s\n' \
-      'init pointer' 'Initialize the pointer.' \
-      'init tablets' 'Initialize any connected tablets.' \
-      'init wallpaper' 'Initialize the desktop wallpaper.'
-
-    return 0
+    printf ' %-35s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
-  printf ' %-36s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
+  printf ' %-35s %s\n' \
     'show status' 'Show the status of the desktop environment.' \
     'show pointer [<id>]' 'Show a pointing device.' \
     'show tablet [<name>]' 'Show a tablet device.' \
@@ -44,30 +41,68 @@ show_help () {
     '' '' \
     'set wallpaper [<name> [<mode>]]' 'Set the desktop wallpaper in center' \
     '' 'fill, scale, max or tile mode.' \
+    'init wallpaper' 'Initialize the desktop wallpaper.' \
+    '' '' \
     'speed pointer [<factor>]' 'Set the pointer speed to a factor between' \
     '' '[0, 1] where 0 means slow and 1 fast.' \
+    'init pointer' 'Initialize the pointer.' \
+    '' '' \
     'scale tablet [<name> [<factor>]]' 'Scale down the area of a tablet (e.g. 0.5)' \
     '' 'or use factor 1 to reset scaling.' \
     'map tablet [<name> [<display>]]' 'Map a tablet to a screen display' \
-    '' 'or just use desktop to reset mapping.'
+    '' 'or just use desktop to reset mapping.' \
+    'init tablets' 'Initialize any connected tablets.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt desktop && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt desktop && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
-  
+    REPLY=''
+
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'show pointer') show_pointer "${args[2]}";;
       'show tablet') show_tablet "${args[2]}";;
@@ -78,51 +113,22 @@ loop () {
       'list wallpapers') list_wallpapers;;
       'list pointers') list_pointers;;
       'list tablets') list_tablets;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
+      'init pointer') init_pointer;;
+      'init tablets') init_tablets;;
+      'init wallpaper') init_wallpaper;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-once () {
-  while getopts 'hq' opt; do
-    case "${opt}" in
-     'h')
-        show_help once
-        return 0;;
-     'q') QUIET='true';;
-     *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
-    esac
-  done
-
-  shift $((OPTIND-1))
-
-  local cmd="${1}"
-  local obj="${2}"
-
-  case "${cmd}${obj:+ ${obj}}" in
-    'init pointer') init_pointer;;
-    'init tablets') init_tablets;;
-    'init wallpaper') init_wallpaper;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
-}
-
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
diff --git a/tools/displays/main b/tools/displays/main
--- a/tools/displays/main
+++ b/tools/displays/main
@@ -7,33 +7,30 @@ source /opt/stack/displays/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: displays [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: displays [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-16s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-16s %s\n' \
-      'restore colors' 'Restore colors to currently active displays.' \
-      'restore layout' 'Restore the layout matching the current mapping.' \
-      'fix layout' 'Fix the positioning of the current layout.'
-
-    return 0
+    printf ' %-44s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
   printf ' %-44s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
     'show status' 'Show a report of the Xorg server and active outputs.' \
     'show logs [<lines>]' 'Show the last logs of the Xorg server.' \
     '' '' \
@@ -54,6 +51,7 @@ show_help () {
     'list layouts' 'List all layout settings.' \
     'delete layout [<index>]' 'Delete a layout setting.' \
     'restore layout' 'Restore the layout matching the current mapping.' \
+    'fix layout' 'Fix the positioning of the current layout.' \
     '' '' \
     'set color [<output> [<profile>]]' 'Set color profile of a display connected to an output.' \
     'reset color [<output>]' 'Reset color profile of a display connected to an output.' \
@@ -62,22 +60,55 @@ show_help () {
     'restore colors' 'Restore colors to currently active displays.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt displays && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt displays && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'show logs') show_logs "${args[2]}";;
       'show output') show_output "${args[2]}";;
@@ -99,50 +130,20 @@ loop () {
       'rotate output') rotate_output "${args[2]}" "${args[3]}";;
       'reflect output') reflect_output "${args[2]}" "${args[3]}";;
       'mirror_output') mirror_output "${args[2]}";;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
+      'fix layout') fix_layout;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-once () {
-  while getopts 'hq' opt; do
-    case "${opt}" in
-     'h')
-        show_help once
-        return 0;;
-     'q') QUIET='true';;
-     *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
-    esac
-  done
+run "$@"
 
-  shift $((OPTIND-1))
-
-  local cmd="${1}"
-  local obj="${2}"
-
-  case "${cmd}${obj:+ ${obj}}" in
-    'restore layout') restore_layout;;
-    'restore colors') restore_colors;;
-    'fix layout') fix_layout;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
-}
-
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
diff --git a/tools/langs/main b/tools/langs/main
--- a/tools/langs/main
+++ b/tools/langs/main
@@ -7,16 +7,30 @@ source /opt/stack/langs/commands
 
 # Shows the help message.
 # Arguments:
-#  None
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
-  echo -e '\nCOMMANDS'
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: langs [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
+    echo -e '\nOPTIONS'
+    printf ' %-10s %s\n' \
+      '-h' 'Show this help message.' \
+      '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+
+    echo -e '\nCOMMANDS'
+    printf ' %-35s %s\n' \
+      'help' 'Show this help message.'
+  fi
+
   printf ' %-35s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
     'show status' 'Show the system locale and keyboard status.' \
     '' '' \
     'set language [<language>]' 'Set the system language.' \
@@ -36,22 +50,55 @@ show_help () {
     'order layouts' 'Set the order of keyboard layouts.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt langs && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt langs && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'set keymap') set_keymap "${args[2]}";;
       'set language') set_language "${args[2]}";;
@@ -63,19 +110,19 @@ loop () {
       'remove locale') remove_locale "${args[2]}";;
       'remove layout') remove_layout "${args[2]}";;
       'order layouts') order_layouts;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-loop
+run "$@"
 
diff --git a/tools/networks/main b/tools/networks/main
--- a/tools/networks/main
+++ b/tools/networks/main
@@ -7,16 +7,30 @@ source /opt/stack/networks/commands
 
 # Shows the help message.
 # Arguments:
-#  None
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
-  echo -e '\nCOMMANDS'
-  printf ' %-35s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: networks [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
+    echo -e '\nOPTIONS'
+    printf ' %-10s %s\n' \
+      '-h' 'Show this help message.' \
+      '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+
+    echo -e '\nCOMMANDS'
+    printf ' %-36s %s\n' \
+      'help' 'Show this help message.'
+  fi
+
+  printf ' %-36s %s\n' \
     'show status' 'Show the current status of networking.' \
     'show device [<name>]' 'Show the data of a device.' \
     'show connection [<name>]' 'Show the data of a connection.' \
@@ -44,22 +58,55 @@ show_help () {
     'power wifi on|off' 'Set the wifi device to on or off.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt networks && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt networks && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'show device') show_device "${args[2]}";;
       'show connection') show_connection "${args[2]}";;
@@ -82,19 +129,19 @@ loop () {
       'remove proxy') remove_proxy "${args[2]}";;
       'set proxy') set_proxy "${args[2]}";;
       'unset proxy') unset_proxy;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-loop
+run "$@"
 
diff --git a/tools/notifications/main b/tools/notifications/main
--- a/tools/notifications/main
+++ b/tools/notifications/main
@@ -7,38 +7,32 @@ source /opt/stack/notifications/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
+  local mode="${1:-"once"}"
+
+  if [[ "${mode}" == "once" ]]; then
     echo 'Usage: notifications [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
     
     echo -e '\nOPTIONS'
-    printf ' %-16s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-16s %s\n' \
-      'get state' 'Return the state of the notifications stream.' \
-      '' '' \
-      'mute all' 'Pause the notifications stream.' \
-      'unmute all' 'Restore the notifications stream.' \
-      '' '' \
-      'start' 'Start the notifications service.' \
-      'restart' 'Restart the notifications service.'
-
-    return 0
+    printf ' %-36s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
-  printf ' %-35s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
+  printf ' %-36s %s\n' \
     'show status' 'Show the status of notifications.' \
+    'get state' 'Return the state of the notifications stream.' \
     '' '' \
     'list all [<sort_by> [<order>]]' 'List all notifications sorted by either the' \
     '' 'id or appname in asc or desc order.' \
@@ -54,22 +48,55 @@ show_help () {
     'restart' 'Restart the notifications service.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt notifications && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt notifications && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'list all') list_all "${args[2]}" "${args[3]}";;
       'mute all') mute_all;;
@@ -79,53 +106,21 @@ loop () {
       'set volume') set_volume "${args[2]}";;
       'start') start;;
       'restart') restart;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
+      'get state') get_state;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-once () {
-  while getopts 'hq' opt; do
-    case "${opt}" in
-     'h')
-        show_help once
-        return 0;;
-     'q') QUIET='true';;
-     *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
-    esac
-  done
+run "$@"
 
-  shift $((OPTIND-1))
-
-  local cmd="${1}"
-  local obj="${2}"
-
-  case "${cmd}${obj:+ ${obj}}" in
-    'get state') get_state;;
-    'mute all') mute_all;;
-    'unmute all') unmute_all;;
-    'start') start;;
-    'restart') restart;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
-}
-
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
 
diff --git a/tools/power/main b/tools/power/main
--- a/tools/power/main
+++ b/tools/power/main
@@ -7,86 +7,52 @@ source /opt/stack/power/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: power [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: power [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-20s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-20s %s\n' \
-      'init screensaver' 'Initialize the screen saver.' \
-      '' '' \
-      'shutdown' 'Shut the system down.' \
-      'reboot' 'Reboot the system.' \
-      'suspend' 'Set system in suspend mode.' \
-      'blank' 'Blank the screen.'
-
-    return 0
+    printf ' %-36s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
   printf ' %-36s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
-    'show status' 'Show the status of the system power.' \
+    'show status' 'Show the power status of the system.' \
     '' '' \
     'set action [<handler> [<action>]]' 'Set the action of a power handler to' \
     '' 'poweroff, reboot, suspend or ignore.' \
     'reset actions' 'Reset to default action for all power handlers.' \
     '' '' \
+    'init screensaver' 'Initialize the screen saver.' \
     'set screensaver <mins>' 'Set the interval of the screen saver,' \
     '' 'where 0 means deactivate the screensaver.' \
     '' '' \
     'set tlp on|off' 'Enable or disable power saving mode.' \
-    'set charge start|stop <percent>' 'Set the battery charge thresholds.'
+    'set charge start|stop <percent>' 'Set the battery charge thresholds.' \
+    '' '' \
+    'shutdown' 'Shut the system down.' \
+    'reboot' 'Reboot the system.' \
+    'suspend' 'Set system in suspend mode.' \
+    'blank' 'Blank the screen.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
 
-  while true; do
-    prompt power && history -s "${REPLY}"
-
-    set -f
-    set_separator line
-    local args=($(xargs -n1 <<< "${REPLY}"))
-    restore_separator && set +f
-
-    local cmd="${args[0]}"
-    local obj="${args[1]}"
-
-    case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
-      'show status') show_status;;
-      'set action') set_action "${args[2]}" "${args[3]}";;
-      'set screensaver') set_screensaver "${args[2]}";;
-      'set tlp') set_tlp "${args[2]}";;
-      'set charge') set_charge "${args[2]}" "${args[3]}";;
-      'reset actions') reset_actions;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
-      *)
-        echo 'Ooops, invalid or unknown command!'
-        $(return 2);;
-    esac && success || fail
-
-    REPLY=''
-  done
-
-  clear
-}
-
-once () {
   while getopts 'hq' opt; do
     case "${opt}" in
      'h')
@@ -94,31 +60,69 @@ once () {
         return 0;;
      'q') QUIET='true';;
      *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
     esac
   done
 
   shift $((OPTIND-1))
 
-  local cmd="${1}"
-  local obj="${2}"
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
-  case "${cmd}${obj:+ ${obj}}" in
-    'init screensaver') init_screensaver;;
-    'shutdown') shutdown_system;;
-    'reboot') reboot_system;;
-    'suspend') suspend_system;;
-    'blank') blank_screen;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
+  while true; do
+    if [[ "${mode}" == "loop" ]]; then
+      prompt power && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
+
+    set -f
+    set_separator line
+    local args=($(xargs -n1 <<< "${REPLY}"))
+    restore_separator && set +f
+    REPLY=''
+
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
+
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
+    case "${cmd}${obj:+ ${obj}}" in
+      'show status') show_status;;
+      'set action') set_action "${args[2]}" "${args[3]}";;
+      'set screensaver') set_screensaver "${args[2]}";;
+      'set tlp') set_tlp "${args[2]}";;
+      'set charge') set_charge "${args[2]}" "${args[3]}";;
+      'reset actions') reset_actions;;
+      'init screensaver') init_screensaver;;
+      'shutdown') shutdown_system;;
+      'reboot') reboot_system;;
+      'suspend') suspend_system;;
+      'blank') blank_screen;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
+
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
+  done
+
+  clear
 }
 
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
diff --git a/tools/printers/main b/tools/printers/main
--- a/tools/printers/main
+++ b/tools/printers/main
@@ -7,16 +7,30 @@ source /opt/stack/printers/commands
 
 # Shows the help message.
 # Arguments:
-#  None
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
-  echo -e '\nCOMMANDS'
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: printers [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
+    echo -e '\nOPTIONS'
+    printf ' %-10s %s\n' \
+      '-h' 'Show this help message.' \
+      '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
+
+    echo -e '\nCOMMANDS'
+    printf ' %-40s %s\n' \
+      'help' 'Show this help message.'
+  fi
+
   printf ' %-40s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
     'show status' 'Show a report of cups service and printers.' \
     'show printer [<name>]' 'Show the data of a printer.' \
     '' '' \
@@ -40,22 +54,55 @@ show_help () {
     'restart' 'Restart the cups service.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
+
+  while getopts 'hq' opt; do
+    case "${opt}" in
+     'h')
+        show_help once
+        return 0;;
+     'q') QUIET='true';;
+     *)
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
+    esac
+  done
+
+  shift $((OPTIND-1))
+
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
   while true; do
-    prompt printers && history -s "${REPLY}"
+    if [[ "${mode}" == "loop" ]]; then
+      prompt printers && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
 
     set -f
     set_separator line
     local args=($(xargs -n1 <<< "${REPLY}"))
     restore_separator && set +f
+    REPLY=''
 
     local cmd="${args[0]}"
     local obj="${args[1]}"
 
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
     case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
       'show status') show_status;;
       'show printer') show_printer "${args[2]}";;
       'list printers') list_printers;;
@@ -72,19 +119,19 @@ loop () {
       'set default') set_default "${args[2]}";;
       'cancel job') cancel_job "${args[2]}";;
       'restart') restart;;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
       *)
         echo 'Ooops, invalid or unknown command!'
         $(return 2);;
     esac && success || fail
 
-    REPLY=''
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
   done
 
   clear
 }
 
-loop
+run "$@"
 
diff --git a/tools/security/main b/tools/security/main
--- a/tools/security/main
+++ b/tools/security/main
@@ -7,34 +7,30 @@ source /opt/stack/security/commands
 
 # Shows the help message.
 # Arguments:
-#  mode: once or none
+#  mode: loop or once
 # Outputs:
 #  A long help message.
 show_help () {
-  if [[ "${1}" == "once" ]]; then
-    echo 'Usage: security [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+  local mode="${1:-"once"}"
 
+  if [[ "${mode}" == "once" ]]; then
+    echo 'Usage: security [OPTIONS] COMMAND [OBJECT] [ARGUMENTS]...'
+    
     echo -e '\nOPTIONS'
-    printf ' %-16s %s\n' \
+    printf ' %-10s %s\n' \
       '-h' 'Show this help message.' \
       '-q' 'Stay quiet and do not play beep sounds.'
+  
+    echo -e '\nCOMMANDS'
+  else
+    echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
 
     echo -e '\nCOMMANDS'
-    printf ' %-16s %s\n' \
-      'init locker' 'Initialize the screen locker.' \
-      '' '' \
-      'lock screen' 'Lock the screen.' \
-      'logout user' 'Logout the user.'
-
-    return 0
+    printf ' %-28s %s\n' \
+      'help' 'Show this help message.'
   fi
 
-  echo 'Usage: COMMAND [OBJECT] [ARGUMENTS]...'
-
-  echo -e '\nCOMMANDS'
-  printf ' %-25s %s\n' \
-    'help' 'Show this help message.' \
-    '' '' \
+  printf ' %-28s %s\n' \
     'show status' 'Show the status of the system security.' \
     '' '' \
     'set password' 'Set a new user password.' \
@@ -43,46 +39,16 @@ show_help () {
     'set interval <time>' 'Set consecutive password fails interval in secs.' \
     '' '' \
     'set locker <mins>' 'Set the interval of the screen locker,' \
-    '' 'where 0 means deactivate the locker.'
+    '' 'where 0 means deactivate the locker.' \
+    'init locker' 'Initialize the screen locker.' \
+    '' '' \
+    'lock screen' 'Lock the screen.' \
+    'logout user' 'Logout the user.'
 }
 
-loop () {
-  clear
+run () {
+  local opt=''
 
-  while true; do
-    prompt security && history -s "${REPLY}"
-
-    set -f
-    set_separator line
-    local args=($(xargs -n1 <<< "${REPLY}"))
-    restore_separator && set +f
-
-    local cmd="${args[0]}"
-    local obj="${args[1]}"
-
-    case "${cmd}${obj:+ ${obj}}" in
-      'help') show_help;;
-      'show status') show_status;;
-      'set locker') set_screen_locker "${args[2]}";;
-      'set password') set_user_password;;
-      'set attempts') set_faillock_attempts "${args[2]}";;
-      'set unblock') set_faillock_unblock "${args[2]}";;
-      'set interval') set_faillock_interval "${args[2]}";;
-      'clear') clear && continue;;
-      'quit') break;;
-      '') continue;;
-      *)
-        echo 'Ooops, invalid or unknown command!'
-        $(return 2);;
-    esac && success || fail
-
-    REPLY=''
-  done
-
-  clear
-}
-
-once () {
   while getopts 'hq' opt; do
     case "${opt}" in
      'h')
@@ -90,29 +56,67 @@ once () {
         return 0;;
      'q') QUIET='true';;
      *)
-      echo 'Ooops, invalid or unknown option'
-      return 2;;
+      fail 'Ooops, invalid or unknown option'
+      return $?;;
     esac
   done
 
   shift $((OPTIND-1))
 
-  local cmd="${1}"
-  local obj="${2}"
+  local mode='once'
+  if [[ $# -eq 0 ]]; then
+    mode='loop'
+    clear
+  fi
 
-  case "${cmd}${obj:+ ${obj}}" in
-    'init locker') init_screen_locker;;
-    'lock screen') lock_screen;;
-    'logout user') logout_user;;
-    *)
-      echo 'Ooops, invalid or unknown command'
-      return 2;;
-  esac
+  while true; do
+    if [[ "${mode}" == "loop" ]]; then
+      prompt security && history -s "${REPLY}"
+    else
+      REPLY="$@"
+    fi
+
+    set -f
+    set_separator line
+    local args=($(xargs -n1 <<< "${REPLY}"))
+    restore_separator && set +f
+    REPLY=''
+
+    local cmd="${args[0]}"
+    local obj="${args[1]}"
+
+    if [[ "${mode}" == "loop" ]]; then
+      case "${cmd}${obj:+ ${obj}}" in
+        'help') show_help loop && continue;;
+        'clear') clear && continue;;
+        'quit') break;;
+        '') continue;;
+      esac
+    fi
+
+    case "${cmd}${obj:+ ${obj}}" in
+      'show status') show_status;;
+      'set locker') set_screen_locker "${args[2]}";;
+      'set password') set_user_password;;
+      'set attempts') set_faillock_attempts "${args[2]}";;
+      'set unblock') set_faillock_unblock "${args[2]}";;
+      'set interval') set_faillock_interval "${args[2]}";;
+      'init locker') init_screen_locker;;
+      'lock screen') lock_screen;;
+      'logout user') logout_user;;
+      *)
+        echo 'Ooops, invalid or unknown command!'
+        $(return 2);;
+    esac && success || fail
+
+    local exit_code=$?
+    if [[ "${mode}" == "once" ]]; then
+      return ${exit_code}
+    fi
+  done
+
+  clear
 }
 
-if [[ $# -eq 0 ]]; then
-  loop
-else
-  once "$@" && success || fail
-fi
+run "$@"
 
