Add the exclamation mark to the possible password characters

diff --git a/tools/security/commands b/tools/security/commands
--- a/tools/security/commands
+++ b/tools/security/commands
@@ -162,6 +162,12 @@ set_user_password () {
 
   ask_secret 'Enter new password:' || return $?
   is_empty "${REPLY}" && echo 'New password cannot be blank' && return 2
+  
+  while not_match "${REPLY}" '^[a-zA-Z0-9@&!#%\$\?_-]{4,}$'; do
+    ask_secret 'Please enter a stronger user password:' || return $?
+    is_empty "${REPLY}" && echo 'New password cannot be blank' && return 2
+  done
+
   local new_password="${REPLY}"
   
   ask_secret 'Retype new password:' || return $?
