Make sure to handle failures gracefully in config scripts

diff --git a/airootfs/home/user/.config/bspwm/resize b/airootfs/home/user/.config/bspwm/resize
--- a/airootfs/home/user/.config/bspwm/resize
+++ b/airootfs/home/user/.config/bspwm/resize
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-set -Eeo pipefail
+set -o pipefail
 
 source /opt/stack/commons/validators.sh
+source /opt/stack/commons/logger.sh
+source /opt/stack/commons/error.sh
 
 # Resizes the windows according to the given direction
 # and delta factors.
@@ -44,6 +46,13 @@ run () {
 
   bspc node -z "${direction}" "${x}" "${y}" ||
     bspc node -z "${opposite}" "${x}" "${y}"
+  
+  if has_failed; then
+    log 'Failed to resize the focused window.'
+    return 1
+  fi
+
+  return 0
 }
 
 run "$@"
diff --git a/airootfs/home/user/.config/bspwm/rules b/airootfs/home/user/.config/bspwm/rules
--- a/airootfs/home/user/.config/bspwm/rules
+++ b/airootfs/home/user/.config/bspwm/rules
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-set -Eeo pipefail
+set -o pipefail
 
 source /opt/stack/commons/validators.sh
+source /opt/stack/commons/logger.sh
+source /opt/stack/commons/error.sh
 
 # Sets the size of any file chooser dialog.
 # Arguments:
@@ -12,10 +14,17 @@ rule_file_chooser () {
 
   local class=''
   class="$(xprop -id "${wid}" | awk '/WM_WINDOW_ROLE/ {print $3}')"
+
+  if has_failed; then
+    log 'Failed to set the size of file chooser.'
+    return 1
+  fi
   
   if equals "${class}" '"GtkFileChooserDialog"'; then
     echo 'rectangle=900x500+0+0'
   fi
+
+  return 0
 }
 
 rule_file_chooser "$@"
diff --git a/airootfs/home/user/.config/bspwm/scratchpad b/airootfs/home/user/.config/bspwm/scratchpad
--- a/airootfs/home/user/.config/bspwm/scratchpad
+++ b/airootfs/home/user/.config/bspwm/scratchpad
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-set -Eeo pipefail
+set -o pipefail
 
 source /opt/stack/commons/validators.sh
+source /opt/stack/commons/logger.sh
+source /opt/stack/commons/error.sh
 
 # Toggles the scratchpad terminal window on and off,
 # if none running terminal is found, a new instance
@@ -12,13 +14,28 @@ run () {
   local current_desktop=''
   current_desktop="$(bspc query -D -d focused)"
 
+  if has_failed; then
+    log 'Failed to find the current focused desktop.'
+    return 1
+  fi
+
   local pids=''
   pids="$(xdotool search --class 'scratch')"
+
+  if has_failed; then
+    log 'Failed to find any scratchpad windows.'
+    return 1
+  fi
 
   for pid in "${pids}"; do
     # Find to which desktop the scratchpad window is now
     local scratchpad_desktop=''
     scratchpad_desktop="$(bspc query -D -n "${pid}")"
+
+    if has_failed; then
+      log 'Failed to find the desktop the scratchpad is shown.'
+      return 1
+    fi
 
     # Toggle scratchpad on/off or bring it to the currently focused desktop
     if equals "${current_desktop}" "${scratchpad_desktop}"; then
@@ -26,7 +43,14 @@ run () {
     else
       bspc node "${pid}" --flag hidden=off -d "${current_desktop}" -f
     fi
+
+    if has_failed; then
+      log 'Failed to handle the scratchpad window in current desktop.'
+      return 1
+    fi
   done
+
+  return 0
 }
 
 run "$@"
diff --git a/airootfs/home/user/.config/bspwm/swap b/airootfs/home/user/.config/bspwm/swap
--- a/airootfs/home/user/.config/bspwm/swap
+++ b/airootfs/home/user/.config/bspwm/swap
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-set -Eeo pipefail
+set -o pipefail
+
+source /opt/stack/commons/logger.sh
+source /opt/stack/commons/error.sh
 
 # Swaps the windows in the currently focused desktop
 # with those of the given desktop.
@@ -20,17 +23,39 @@ run () {
   
   while read -r node; do
     bspc node "${node}" -g sticky
+
+    if has_failed; then
+      log "Failed to set window ${node} to not sticky."
+      return 1
+    fi
   done <<< "${nodes}"
   
   bspc desktop -s "${target}" --follow
 
+  if has_failed; then
+    log "Failed to set focused desktop to ${target}."
+    return 1
+  fi
+
   # Set windows back to sticky mode
   while read -r node; do
     bspc node "${node}" -g sticky
+
+    if has_failed; then
+      log "Failed to set window ${node} back to sticky."
+      return 1
+    fi
   done <<< "${nodes}"
 
   # Fix any desktop inconsistencies caused by the swap
   desktop -qs fix workspaces
+
+  if has_failed; then
+    log 'Failed to fix desktop workspaces.'
+    return 1
+  fi
+
+  return 0
 }
 
 run "$@"
diff --git a/airootfs/home/user/.config/dunst/hook b/airootfs/home/user/.config/dunst/hook
--- a/airootfs/home/user/.config/dunst/hook
+++ b/airootfs/home/user/.config/dunst/hook
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-set -Eeo pipefail
+set -o pipefail
 
 source /opt/stack/commons/validators.sh
+source /opt/stack/commons/logger.sh
+source /opt/stack/commons/error.sh
 
 # Plays the popup sound for the incoming notification
 # based on the notification's parameters.
@@ -30,9 +32,14 @@ run () {
     LC_ALL=en_US.UTF-8 pw-play --volume=0.5 "${sound_file}" &> /dev/null
   elif command -v aplay &> /dev/null; then
     aplay "${sound_file}" &> /dev/null
-  else
-    return 0
   fi
+
+  if has_failed; then
+    log 'Failed to play the notification sound.'
+    return 1
+  fi
+
+  return 0
 }
 
 run "$@"
